iot.yaml
=> Update F30 Iot noarch package list

eln-base.yaml
Based on the Base Runtime and Host & Platform concepts.
=> Defining ELN base

configs/sst_cs_stacks-perl-LDAP.yaml, configs/sst_cs_stacks-perl-libwww-perl.yaml, configs/sst_cs_stacks-unwanted.yaml
Add perl-LDAP and perl-libwww-perl work loads. Remove some Perl
packages.
=> Perl refinements

configs/sst_platform_tools-go-toolset.yaml, configs/sst_platform_tools-llvm-toolset-exclusion.yaml, configs/sst_platform_tools-rust-toolset.yaml
Updates to go, llvm, and rust toolset workloads.
=> Toolset updates

configs/sst_cs_apps-apps-cronie.yaml, configs/sst_cs_apps-apps-mutt.yaml, configs/sst_cs_apps-apps-unsorted.yaml, configs/sst_cs_apps-archiving.yaml, configs/sst_cs_apps-autotools.yaml, configs/sst_cs_apps-db-mariadb.yaml, configs/sst_cs_apps-db-mysql.yaml, configs/sst_cs_apps-db-postgresql.yaml, configs/sst_cs_apps-embedded.yaml, configs/sst_cs_apps-images.yaml, configs/sst_cs_apps-jdbc.yaml, configs/sst_cs_apps-nodejs.yaml, configs/sst_cs_apps-odbc.yaml, configs/sst_cs_apps-python-db-connectors.yaml, configs/sst_cs_apps-ruby-db-connectors.yaml, configs/sst_cs_apps-ruby-rspec.yaml, configs/sst_cs_apps-ruby.yaml, configs/sst_cs_apps-scm.yaml, configs/sst_cs_apps-unwanted-mariadb.yaml, configs/sst_cs_apps-unwanted-nis.yaml, configs/sst_cs_apps-unwanted-python2.yaml, configs/sst_cs_apps-unwanted-ruby.yaml, configs/sst_cs_apps-unwanted.yaml
Data based on https://docs.google.com/spreadsheets/d/1gPHVLu8S4ITFxL3tslmsNktEMGYcrd2wHd4_E-e9Vj4/edit#gid=2026456282
=> Bulk add of CS Apps SST components

configs/sst_networking-sctp.yaml
Basically, just lksctp-tools is needed.
=> Workload to support SCTP usage

configs/sst_networking-management-core.yaml, configs/sst_networking-management-devel.yaml, configs/sst_networking-management-server.yaml
Use package name instead of provides.
=> Rename iproute2 to iproute

configs/sst_cs_infra_services-unwanted.yaml
First draft of unwanted packages list.
Signed-off-by: Tomas Hozza <thozza@redhat.com>
=> CS Infra Services SST: Add list of unwanted packages

configs/sst_platform_security-smart-cards.yaml
pull request created by rrelyea@redhat.com
=> Add workload for smart card enablement.

configs/sst_networking-openvswitch-exclusion.yaml
Exclude Open vSwitch packages.
=> Exclude Open vSwitch packages.

configs/sst_networking-fast-packet-processing.yaml
The tuned is required to set up the system for best performance.
=> Add tuned to fast packet processing.

configs/sst_cs_infra_services-accessibility-tools.yaml, configs/sst_cs_infra_services-base-os-packages.yaml, configs/sst_cs_infra_services-databases.yaml, configs/sst_cs_infra_services-dhcp-server.yaml, configs/sst_cs_infra_services-dns-server.yaml, configs/sst_cs_infra_services-dns-utilities.yaml, configs/sst_cs_infra_services-file-synchronization.yaml, configs/sst_cs_infra_services-ftp-server.yaml, configs/sst_cs_infra_services-geoip.yaml, configs/sst_cs_infra_services-graph-visualization.yaml, configs/sst_cs_infra_services-graphical-toolkits.yaml, configs/sst_cs_infra_services-http-ftp-cli-clients.yaml, configs/sst_cs_infra_services-i2c-tools.yaml, configs/sst_cs_infra_services-ip-routing.yaml, configs/sst_cs_infra_services-mda.yaml, configs/sst_cs_infra_services-messaging-clients.yaml, configs/sst_cs_infra_services-mta.yaml, configs/sst_cs_infra_services-network-dbg-tools.yaml, configs/sst_cs_infra_services-performance-tuning.yaml, configs/sst_cs_infra_services-power-management.yaml, configs/sst_cs_infra_services-printing-stack.yaml, configs/sst_cs_infra_services-scanning-stack.yaml, configs/sst_cs_infra_services-spam-filtering.yaml, configs/sst_cs_infra_services-tcl.yaml, configs/sst_cs_infra_services-terminal-emulator.yaml, configs/sst_cs_infra_services-testing.yaml, configs/sst_cs_infra_services-text-editors.yaml, configs/sst_cs_infra_services-time-synchronization.yaml, configs/sst_cs_infra_services-tunneling.yaml, configs/sst_cs_infra_services-unwanted.yaml
Changes to CS Infra Services Unwanted packages & 1st draft of workloads definition
=> Changes to CS Infra Services Unwanted packages & 1st draft of workloads definition

configs/sst_i18n_langpacks.yaml
This workload contains langpacks packages. As langpacks uses weak dependencies, this workload also enabled option to install weak dependencies.
=> Added sst_i18n Langpacks workload

configs/sst_kernel_maintainers-kernel-base.yaml, configs/sst_kernel_maintainers-kernel-develdebug.yaml, configs/sst_kernel_maintainers-kernel-unwanted.yaml
Signed-off-by: Jan Stancek <jstancek@redhat.com>
=> sst_kernel_maintainers: add initial workload/unwanted sets

configs/sst_virtualization_cloud-3rdparty_hypervisors.yaml, configs/sst_virtualization_cloud-cloud.yaml, configs/sst_virtualization_cloud-cloud_azure.yaml
Userspace agents and tools to run RHEL on 3rd party hypervisors (ESXi, Hyper-V) and public/private clouds.
=> Sst virtualization cloud content

configs/sst_i18n-input-methods.yaml
This is a list of input method metapackages for RHEL9.
=> I18n input methods

configs/sst_i18n-tools.yaml
workload for some misc i18n tools
=> initial sst_i18n-tools workload

configs/sst_virtualization_windows-subsystem.yaml
Signed-off-by: Vadim Rozenfeld <vrozenfe@redhat.com>
=> Add virtualization Windows subsystem workload

configs/sst_platform_tools-debuggers.yaml, configs/sst_platform_tools-performance-tools-unwanted.yaml, configs/sst_platform_tools-performance-tools.yaml
Adding Platform Tools debugger packages.
=> Added Platform Tools debugger packages.

configs/sst_kernel_rats-tpm-exclusion.yaml, configs/sst_kernel_rats-tpm.yaml
=> TPM package updates

configs/sst_kernel_rats-kernel-rt-base.yaml, configs/sst_kernel_rats-kernel-rt-develdebug.yaml, configs/sst_kernel_rats-kernel-rt-unwanted.yaml
=> sst_kernel_rats: add initial workload/unwanted sets for kernel-rt

configs/sst_kernel_rats-perf.yaml, configs/sst_kernel_rats-tools.yaml, configs/sst_kernel_rats-tracing.yaml
Please pull these yaml files for realtime userspace programs to be included in rhel-9
=> realtime userspace

configs/sst_cs_infra_services-base-os-packages.yaml, configs/sst_cs_infra_services-development-packages.yaml, configs/sst_cs_infra_services-graph-visualization.yaml, configs/sst_cs_infra_services-printing-stack.yaml, configs/sst_cs_infra_services-testing.yaml, configs/sst_cs_infra_services-unwanted.yaml
CS Infra Services: Updated SST workloads based on team review; added Development pkgs workload
Signed-off-by: Tomas Hozza <thozza@redhat.com>
=> CS Infra Services: Updated SST workloads based on team review; added Development pkgs workload

configs/sst_networking-firewall-tools.yaml, configs/sst_networking-firewall-unwanted.yaml
=> Add firewall related workloads

configs/sst_kernel_rats-opae.yaml
Signed-off-by: Tom Rix <trix@redhat.com>
=> OPAE package updates

configs/sst_kernel_rats-setup.yaml
Signed-off-by: Clark Williams <williams@redhat.com>
=> Realtime setup package

configs/sst_cs_stacks-httpd.yaml
=> Enable httpd:2.4 for httpd ELN workload.

configs/sst_middleware-unwanted.yaml
`Signed-off-by: Alexander Scheel <ascheel@redhat.com>`
---
/cc @csutherl -- Coty is the Fedora maintainer of Tomcat.
=> Mark Tomcat as a removed package

configs/sst_platform_security_compliance-installation.yaml, configs/sst_platform_security_compliance-library.yaml, configs/sst_platform_security_compliance-scanner.yaml, configs/sst_platform_security_compliance-sce.yaml, configs/sst_platform_security_compliance-security_content.yaml, configs/sst_platform_security_compliance-utilities.yaml, configs/sst_platform_security_compliance-workbench.yaml
SCAP and Compliance related workflows
=> Initial OpenSCAP-related workflows

configs/sst_coreos.yaml
=> Add definition for coreos

configs/sst_kernel_ft-rasdaemon.yaml
Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>
=> Adding rasdaemon

configs/sst_kernel_tps-microcode.yaml
Add dwarves to the bpf-devel workload.
Add new microcode workload.
=> Update sst_kernel_tps workloads

configs/sst_high_availability-userspace.yaml
pexpect
python3-jwt
libknet1
libknet1-devel
libnozzle1
libnozzle1-devel
omping
=> SST_HIGH_AVAILABILITY - Added more packages for content set.

configs/sst_kernel_ft-kpatch.yaml
Signed-off-by: Joe Lawrence <joe.lawrence@redhat.com>
=> Adding kpatch

configs/sst_identity_management-python-gssapi.yaml
=> Add python-gssapi workload

configs/sst_cs_stacks-perl-5.32.yaml
perl:5.32 becomes a default perl stream.
=> Add perl:5.32

configs/sst_cs_apps-unwanted-python3.yaml
Related to https://github.com/minimization/content-resolver-input/issues/162
cc @torsava
=> Mark all alternate Python packages as unwanted

configs/sst_desktop-gtk2.yaml, configs/sst_desktop-libreoffice.yaml, configs/sst_desktop_applications-inkscape.yaml, configs/sst_desktop_applications-nautilus.yaml
Add more packages to workflows
=> Update the sst_desktop(_applications) worflows

configs/sst_dotnet_java-java.yaml, configs/sst_dotnet_java-unwanted.yaml
Further changes from the Java team folllowing internal discussion.
=> Drop icedtea-web from .NET/Java list & explicitly add Rhino and Byteman

configs/sst_desktop_applications-qt5.yaml
See https://github.com/minimization/content-resolver-input/pull/185#issuecomment-672975429
=> Remove qt5 package and it's not built anymore

configs/sst_identity_management-idm-client-tools.yaml
Cockpit module providing session recording configuration and playback.
=> Add cockpit-session-recording

configs/sst_cs_infra_services-base-os-packages.yaml, configs/sst_cs_infra_services-development-packages.yaml, configs/sst_cs_infra_services-i2c-tools.yaml, configs/sst_cs_infra_services-power-management.yaml
Fixed all failures of workload package resolution for our SST workloads.
Fixed a typo in workload description.
=> Multiple fixes for sst_cs_infra_services workloads

configs/sst_kernel_ft-kpatch.yaml
Signed-off-by: Joe Lawrence <joe.lawrence@redhat.com>
=> mark kpatch package as RHEL-only

configs/sst_kernel_ft-libhugetlbfs.yaml
Signed-off-by: Rafael Aquini <aquini@redhat.com>
=> Adding libhugetlbfs

configs/sst_kernel_ft-memkind.yaml
Signed-off-by: Rafael Aquini <aquini@redhat.com>
=> Adding memkind

configs/sst_platform_tools-compat.yaml, configs/sst_platform_tools-gcc-toolset.yaml
As reported here:
<https://tiny.distro.builders/maintainer--sst_platform_tools.html>.
=> Fix issues in sst_platform_tools-compat, sst_platform_tools-gcc-toolset.

configs/sst_platform_security_compliance-authoring.yaml, configs/sst_security_compliance-authoring.yaml, configs/sst_security_compliance-installation.yaml, configs/sst_security_compliance-library.yaml, configs/sst_security_compliance-scanner.yaml, configs/sst_security_compliance-sce.yaml, configs/sst_security_compliance-security_content.yaml, configs/sst_security_compliance-unwanted.yaml, configs/sst_security_compliance-utilities.yaml, configs/sst_security_compliance-workbench.yaml
One new workflow, and change of the sst handle, as there is a separate security compliance sst now :)
=> Openscap update

configs/sst_virtualization_windows-subsystem.yaml
Signed-off-by: Vadim Rozenfeld <vrozenfe@redhat.com>
=> virtualization windows subsystem add Fedora related part

configs/sst_kernel_rats-kernel-rt-develdebug.yaml, configs/sst_kernel_rats-perf.yaml
Signed-off-by: Clark Williams <williams@redhat.com>
=> removed duplicate package references

configs/sst_graphics_infrastructure-X11-server.yaml
=> remove openchrome ddx driver

configs/sst_openstack.yaml
These track a subset of packages that Openstack needs from the
underlying OS
=> Add initial openstack dependencies

configs/sst_virtualization_windows-subsystem.yaml
Signed-off-by: Vadim Rozenfeld <vrozenfe@redhat.com>
=> virtualization windows subsystem move mingw under buildrequires

configs/sst_cs_infra_services-geoip.yaml, configs/sst_cs_infra_services-unwanted.yaml
CS Infra Serv:  Added avahi and nss-mdns to printing stack workload
=> CS Infra Serv:  Added avahi and nss-mdns to printing stack workload 

configs/sst_kernel_rats-opae.yaml
Signed-off-by: Tom Rix <trix@redhat.com>
=> sst_kernel_rats-opae.yaml: add opae-devel to package list

configs/sst_arch_hw-unwanted.yaml, configs/sst_arch_hw.yaml
Adding arch hw packages for @jdonohue2
=> Add arch hardware configs

configs/sst_nic_rdma-bluefield.yaml
Adding bluefield smartnic packages for @jdonohue2
=> Add Bluefield smartnic packages

configs/sst_arch_portfolio.yaml
Adding arch portfolio for @jdonohue2
=> Add architecture specific packages

configs/eln-repo-split.yaml
List some of the intial content split packages for the various
repos.  We'll start small and adjust from here.
=> Add initial split

configs/sst_kernel_debug-kdump.yaml, configs/sst_kernel_debug-misc.yaml, configs/sst_kernel_debug-unwanted.yaml
Hi Adam,
I made some changes to sst_kernel_debug files, please help review and consider merging if it's OK to you.
=> Sst kernel debug rhel9

configs/sst_security_special-nbde.yaml
=> Updated NBDE workload

configs/sst_security_special-libcap.yaml
=> Added libcap and libcap-ng workloads

configs/sst_security_special-audit.yaml
=> Added audit workload

configs/sst_security_special-rsyslog.yaml
=> Updated rsyslog workflow

configs/sst_security_special-usbguard.yaml
=> Updated usbguard workload

configs/sst_cs_apps-odbc.yaml
It is requested to be part of RHEL in https://issues.redhat.com/browse/RHELBU-929
=> Add pyodbc to the ODBC workload

configs/sst_cs_apps-odbc.yaml
Thanks @asamalik for spotting the issue.
=> Fix name for the pyodbc package

configs/cee-support-workload.yaml, configs/cee_support_unwanted.yaml
Signed-off-by: Chris Williams <cww@redhat.com>
=> Added rig to workload, moved RHST packages to unwanted.

configs/sst_kernel_rats-tpm.yaml
=> sst_kernel_rats-tpm: update list for subpackages

configs/sst_coreos.yaml
See https://github.com/coreos/fedora-coreos-config/commit/8be272008a8ca58cc0ec53fb8301b50df3b1d899#diff-5d2a56392c73a744578b94f48544e03031836077d7030313d655f6d688687c94
=> coreos: Add bootupd

configs/sst_coreos.yaml
And while we have the patient open, clarify the comment.
=> coreos: Fix bootupd name

configs/sst_cs_apps-scm.yaml
Add git-lfs and drop Mercurial.
=> Update SCM package set

configs/sst_desktop_applications-unwanted.yaml
=> Specify gtk3 subpackages for libappindicator, libindicator and libdbusmenu

configs/cee-support-workload.yaml, configs/sst_cs_plumbers-math.yaml, configs/sst_cs_system_management-depsonly.yaml
Hello,
Reading some files failed for me with YAML syntax errors. I believe this is how they should be fixed.
=> Fix YAML syntax

configs/sst_kernel_rats-dma-iommu.yaml
=> accel-config: Add accel-config and subpackages to ELN

configs/sst_cs_apps-unwanted-python3.yaml
=> We don't want this

configs/sst_i18n-fonts.yaml
This is the request to add missing fonts in fonts workload
=> Add Carlito and Caladea fonts

configs/sst_cs_apps-python.yaml
cc @torsava @encukou 
@asamalik Am I doing it right? python-pip is the source name, the other two are subpackages.
=> Add a placeholder for pip to filter out many tests deps

configs/sst_cs_apps-java-ant.yaml, configs/sst_cs_apps-java-maven.yaml
Add Apache Ant 1.10 and Apache Maven 3.6 workloads for sst_cs_apps.
CC @voxik
=> Add sst_cs_apps Java workloads

configs/sst_desktop-unwanted.yaml, configs/sst_desktop_applications-nautilus.yaml
=> libmtp is wanted

configs/sst_desktop-gnome-desktop.yaml, configs/sst_desktop_applications-unwanted.yaml
See https://src.fedoraproject.org/rpms/glib2/c/c64ee0c537621934f9b35e4d3bb33eae5de0d441
=> Drop gamin and glib2-fam

configs/sst_virtualization-all.yaml
=> Virt SST: Update Content Set to resolve Workload errors

configs/sst_desktop-gtk2.yaml, configs/sst_desktop-gtk3.yaml
By not specifying it in any workload
=> Make gtk-doc a buildroot package

configs/sst_filesystems-userspace.yaml
- inih for xfsprogs to work.
- inih-devel to build xfsprogs.
=> SST_FILESYSTEMS: Added "inih" packages for xfsprogs dependency resolution

configs/sst_cs_infra_services-databases.yaml
Signed-off-by: Tomas Korbar <tkorbar@redhat.com>
=> Add memcached-selinux package to sst_cs_infra_services-databases.yaml

configs/sst_kernel_ft-kpatch.yaml
Fixes: #268
Signed-off-by: Joe Lawrence <joe.lawrence@redhat.com>
=> Add entry for new kpatch-dnf subpackage

configs/sst_identity_management-smart-cards.yaml
`Signed-off-by: Alexander Scheel <ascheel@redhat.com>`
/cc: @jmagne
=> Add ESC as a desired package

configs/sst_desktop-unwanted.yaml
They do have new package owners in RHEL
=> Don't mark some lua packages as unwanted

configs/sst_cs_apps-unwanted-perl.yaml
This delists 3 packages from an unwanted list and documents reasons for the rest of them.
=> Update unwanted perl packages

configs/stream-httpd.yaml
Virtual provides for compatibility? Bah, who wants those.
=> Change names for CentOS Linux 8/stream.

configs/sst_virtualization_spice-exclusion.yaml, configs/sst_virtualization_spice.yaml
=> SPICE: packages that are to be included

configs/sst_virtualization-all.yaml, configs/sst_virtualization-exclusion.yaml
Two new changes were decided in virtualization sst
=> Update sst_virtualization workflow

configs/sst_networking-mptcpd.yaml
since now it's available for f34 and eln
=> replace mptcpd placeholder with real package

configs/sst_kernel_rats-perf.yaml, configs/sst_kernel_rats-setup.yaml
I regenerated the patches without the buildroot changes.
=> change rt-tests to realtime-tests and rt-setup to realtime-setup

configs/sst_kernel_rats-tools.yaml
Signed-off-by: Clark Williams <williams@redhat.com>
=> add stalld package to configs/sst_kernel_rats-tools.yaml

configs/sst_nic_rdma-wireless.yaml
Somehow, we overlooked some basic wireless LAN packages for RHEL9 until now...
Signed-off-by: John W. Linville <linville@redhat.com>
=> Add workload covering fundamental tools for wireless LAN usage.

configs/sst_cs_apps-unwanted-python3.yaml
=> We don't want twisted

configs/sst_cs_system_management-sys-management.yaml
please remove liboggz, it has been effectively dead for more 7 years now. It doesn't make any sense to include it
=> please remove liboggz

configs/sst_kernel_ft-redfish-finder.yaml
Signed-off-by: Joel Savitz <jsavitz@redhat.com>
=> add redfish-finder config file

configs/sst_cs_apps-unwanted-python3.yaml
=> Another batch of unwanted Python packages

configs/sst_desktop-gnome-desktop.yaml, configs/sst_desktop_applications-unwanted.yaml
See https://bugzilla.redhat.com/show_bug.cgi?id=1913643 for more information
=> Drop gnome-online-miners

configs/sst_desktop-unwanted_eln.yaml
Comment should be self-explanatory.
=> Add glew to desktop unwanted ELN packages

configs/sst_virtualization-all.yaml
A userspace management tool for environments utilizing AMD Secure Encrypted
Virtualization.
Signed-off-by: Connor Kuehl <ckuehl@redhat.com>
=> sst_virtualization: Add sevctl

configs/sst_virtualization-all.yaml, configs/sst_virtualization_spice-exclusion.yaml
1. spice-vdagent is wanted
2. Remove some SPICE packages from sst_virtualization-all
=> spice-vdagent is wanted

configs/sst_cs_apps-apps-unsorted.yaml, configs/sst_cs_infra_services-dns-utilities.yaml
=> Move whois between RHEL teams.

configs/sst_cs_system_management-sys-management.yaml
Adding packages openexr, imath and watchdog
=> Add new package

configs/sst_front_door-x3270.yaml
=> Create the x3270 workload

configs/automotive-c8s-image-manifest.yaml
Added packages for the automotive base image
=> Updated packaged for automotive base image

configs/automotive-c8s-image-manifest.yaml
Updated the typo in package name
=> Updated the typo in package name

get_pkgs_sst.py
It is also possible to use it for finding differences between the compose content
and the content definition config (see the comment in the script).
=> Add a script for filter packages by sst

configs/sst_virtualization-all.yaml
We are agoing to split ksmtuned files from qemu-kvm package to separate package.
Signed-off-by: Miroslav Rezanina <mrezanin@redhat.com>
=> Add ksmtuned package

configs/sst_kernel_rts-dma-iommu.yaml, configs/sst_kernel_rts-kernel-rt-base-eln.yaml, configs/sst_kernel_rts-kernel-rt-base.yaml, configs/sst_kernel_rts-kernel-rt-develdebug-eln.yaml, configs/sst_kernel_rts-kernel-rt-develdebug.yaml, configs/sst_kernel_rts-kernel-rt-unwanted.yaml, configs/sst_kernel_rts-opae.yaml, configs/sst_kernel_rts-perf.yaml, configs/sst_kernel_rts-setup.yaml, configs/sst_kernel_rts-sysfsutils.yaml, configs/sst_kernel_rts-tools.yaml, configs/sst_kernel_rts-tpm-exclusion.yaml, configs/sst_kernel_rts-tpm.yaml
This change renames all occurrences of rats with rts.
=> Rename rats to rts

configs/automotive-base-c8s-env-maximum.yaml, configs/automotive-base-c8s-env-minimal.yaml, configs/automotive-base-c8s-view-bootloader-grub2.yaml, configs/automotive-base-c8s-view-maximal.yaml, configs/automotive-base-c8s-workload-bootloader-grub2.yaml, configs/automotive-base-c8s-workload-maximal.yaml, configs/automotive-base-c8s-workload-neptune.yaml, configs/automotive-base-c8s-workload-podman.yaml, configs/automotive-base-c9s-env-maximum.yaml, configs/automotive-base-c9s-env-minimal.yaml, configs/automotive-base-c9s-view-bootloader-grub2.yaml, configs/automotive-base-c9s-view-maximal.yaml, configs/automotive-base-c9s-view-neptune.yaml, configs/automotive-base-c9s-workload-all.yaml, configs/automotive-base-c9s-workload-bootloader-grub2.yaml, configs/automotive-base-c9s-workload-maximal.yaml, configs/automotive-base-c9s-workload-neptune.yaml, configs/automotive-base-c9s-workload-ostree.yaml, configs/automotive-base-c9s-workload-podman.yaml
This updates the content-resolver-input for the automotive base group. It also adds a maximal which may be a useful tree for determining the workload for automotive toolchain
=> Automotive base 2021110

configs/sst_security_special_projects-rsyslog.yaml
See https://bugzilla.redhat.com/show_bug.cgi?id=1992155 for more details.
=> Add new subpackage rsyslog-logrotate

configs/automotive-toolchain-c8s-env.yaml, configs/automotive-toolchain-c9s-env.yaml
This should add in the last of the missing itmes.
=> Automotive base 2021112a: finish up items for toolchain

configs/sst_cs_apps-apps-cronie.yaml
More details https://bugzilla.redhat.com/show_bug.cgi?id=2029495
=> Add cronie-anacron and cronie-noanacron sub-packages

configs/automotive-c9s-env-minimum.yaml, configs/automotive-c9s-view-imagebuilder.yaml, configs/automotive-c9s-workload-development.yaml, configs/automotive-c9s-workload-imagebuilder.yaml
This will merge some changes I have seen between what we are using and what image-builder pulls into images. Working to resolve if they need to go into minimization or can be a separate file for right now.
=> Automotive minimal 20220111

configs/sst_arch_hw.yaml
=> Add libzdnn, s390x only library, in to arch_hw

configs/mingw-pkg-config-exclusion.yaml
Signed-off-by: Kostiantyn Kostiuk <kkostiuk@redhat.com>
=> Add MinGW pkg-config exclusion

configs/sst_cs_apps-java-log4j.yaml, configs/sst_cs_apps-unwanted-java.yaml
Add new Apache Log4j 2 workload.
Also remove log4j and disruptor (dependency of log4j) from unwanted packages.
=> Add Apache Log4j 2 workload

configs/sst_platform_storage-packages.yaml
Signed-off-by: Andrew Walsh <awalsh@redhat.com>
=> Added python3-wcwidth to stratis packages.

configs/eln_extras_meta.yaml
=> Update ELN Extras for Meta workload

configs/automotive-environment.yaml
Signed-off-by: Pierre-Yves Chibon <pingou@pingoured.fr>
=> Automotive-environment: add the linux-firmware-automotive package

configs/sst_cs_apps-unwanted-java.yaml
jsoup packgae is unwanted by sst_cs_apps
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/NALKM5PMXE7FLALO6IBAPYOO74IL6K3R/
=> Add jsoup to unwanted packages for sst_cs_apps

configs/sst_arch_hw.yaml
=> Add libnxz for RHEL9

configs/sst_installer-anaconda.yaml
This is related to https://github.com/rhinstaller/anaconda/pull/4196 .
Up for discussion if this is actually needed.
=> Add anaconda environment metapackage

configs/sst_virtualization-all-eln.yaml, configs/sst_virtualization-all.yaml
https://bugzilla.redhat.com/show_bug.cgi?id=2089785
Signed-off-by: Gerd Hoffmann <kraxel@redhat.com>
=> Virtualization: add virt-firmware

configs/acg-level1-el9.yaml
Signed-off-by: Stephen Gallagher <sgallagh@redhat.com>
Extracted from the [Package listing for Red Hat Enterprise Linux 9](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html-single/package_manifest/index)
=> Add ACG Level 1 for RHEL 9

configs/sst_program-unwanted.yaml
GraphicsMagick shouldn't be in RHEL and ELN
=> Treat GraphicsMagick as ImageMagick

configs/sst_desktop-unwanted-eln.yaml
See https://fedoraproject.org/wiki/Changes/libsoup_3:_Part_One and https://fedoraproject.org/wiki/Changes/libsoup_3:_Part_Two for the background.
=> Deprecate libsoup in favor of libsoup3

configs/sst_arch_hw.yaml
=> Add s390x only package libzpc

configs/sst_accelerators-opae.yaml
Signed-off-by: Tom Rix <trix@redhat.com>
=> accelerators sst own opae

configs/eln_extras_kde.yaml
Signed-off-by: Troy Dawson <tdawson@redhat.com>
=> Cleanup kde

configs/eln_extras_meta.yaml
Add some more packages we need.
=> Update ELN Extras workload for Meta

configs/eln_extras_cinnamon.yaml, configs/eln_extras_gnome_flashback.yaml, configs/eln_extras_yselkowitz.yaml
- Add Cinnamon to ELN Extras
- Add GNOME Flashback to ELN Extras
- Add my assorted packages to ELN Extras
=> Add my packages to ELN Extras

configs/sst_cs_system_management-text-processing.yaml, configs/sst_cs_system_management-unwanted.yaml
Remove librx from ELN and c10s.
=> Mark librx as unwanted in ELN and c10s

configs/eln_extras_ffmpeg.yaml, configs/eln_extras_gedit.yaml
- Add ffmpeg-free related packages to ELN Extras
- Add gedit to ELN Extras
=> Add ffmpeg-free and gedit to ELN Extras

configs/sst_high_availability-userspace.yaml
CR was not designed to mix and match placeholders and real (subpackages) from the same SRPM.
/cc @asamalik
=> Fix HA placeholders

configs/sst_kernel_security-code-tools.yaml, configs/sst_kernel_security-crypto.yaml, configs/sst_kernel_security-intel-qat.yaml
Also add newer required packages to sst_kernel_security-intel-qat.yaml.
=> Move packages from sst_kernel_tps to sst_kernel_security

configs/sst_cs_system_management-gimp.yaml, configs/sst_cs_system_management-unwanted-eln.yaml
and split c9s and ELN unwanted list for system management.
=> Remove GIMP from ELN

configs/sst_cs_infra_services-httpd.yaml
=> - Explicitly reference httpd-core

configs/eln_extras_meta.yaml
=> Add trousers to the ELN Extras workload for Meta

configs/sst_desktop-libreoffice.yaml
See the following Fedora announcement -
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/46ZZ6GZ2W3G4OJYX3BIWTAW75H37TVW6/
=> LibreOffice won't be part of RHEL 10

configs/sst_security_compliance_cc-base-noweak.yaml, configs/sst_security_compliance_cc-base-weak.yaml, configs/sst_security_compliance_cc-core-noweak.yaml, configs/sst_security_compliance_cc-core-weak.yaml
Move the maintainership of the sst_security_readiness to sst_security_compliance.
=> Moving security_readiness mapping under compliance

configs/eln-repo-split.yaml, configs/sst_program-lorax-template-eln.yaml, configs/sst_program-unwanted.yaml
Take assignment for a few things and reflect some font changes made in Rawhide that affect the lorax workload.
=> Update program workloads

configs/sst_cs_system_management-text-processing-c9s.yaml
per https://github.com/fedora-eln/eln/issues/53
/cc @ngothan
=> Drop texlive CJK components from ELN

configs/sst_storage_io-packages-unwanted.yaml
@yselkowitz this appears to be the only difference. Did I get everything this time?
=> Fixup the storage_io unwanted packages

configs/eln_extras_meta.yaml
Need these to test out the plugin API
=> Add more dnf5 packages to the ELN Extras workload for Meta

configs/sst_cs_system_management-text-processing.yaml
removed texlive-texlive-docindex, texlive-updmap-map as both were dropped by texlive upstream
=> removed texlive-texlive-docindex, texlive-updmap-map

configs/sst_java-java.yaml, configs/sst_logical_storage-packages.yaml, configs/sst_platform_tools-llvm-toolset.yaml, configs/sst_program-lorax-template-eln.yaml
- Fix llvm-toolset warnings
- Fix ELN lorax-template warning
- Fix Platform Storage warning
- Fix Java debug package warnings
=> Fix some ELN warnings

configs/sst_cs_system_management-text-processing.yaml
remove texlive-arabxetex, texlive-xetex-tibetan from ELN
=> remove texlive-arabxetex, texlive-xetex-tibetan from ELN

configs/sst_cs_apps-db-postgresql-libs.yaml, configs/sst_cs_apps-db-postgresql.yaml, configs/sst_cs_infra_services-httpd.yaml, configs/sst_networking-firewall-tools.yaml
- Fix firewall-tools package list
- Placehold httpd mod_proxy_cluster
- Separate postgresql libs workload
=> Fix more ELN warnings and issues

configs/mingw-pkgs-exclusion.yaml, configs/sst_virtualization_windows-subsystem.yaml
Fixes: [RHELMISC-969 - Review existing workloads targeting ELN/RHEL 10](https://issues.redhat.com/browse/RHELMISC-969)
=> Updates for sst_virtualization_windows 

configs/sst_desktop-flatpak-eln.yaml
Be more explicit about dependencies.
=> Extend the Flatpak workload

configs/sst_i18n-fonts-eln.yaml, configs/sst_program-lorax-template-eln.yaml
https://fedoraproject.org/wiki/Changes/Noto_CJK_Variable_Fonts
=> Replace google-noto-sans-cjk-ttc-fonts

configs/sst_desktop-brasero-eln.yaml, configs/sst_desktop_applications-evince-eln.yaml
Until the following upstream changes are merged:
https://gitlab.gnome.org/GNOME/brasero/-/merge_requests/21 https://gitlab.gnome.org/GNOME/evince/-/merge_requests/561
=> Temporarily disable Nautilus plugins

configs/sst_cs_infra_services-s-nail.yaml
=> Moving s-nail to the Infra team who owns it now

configs/sst_container_tools.yaml, configs/sst_container_tools_eln.yaml
This adds container-tools' related content amendments and preparation for RHEL10.
=> Add RHEL10 and RHEL9 content amendments.

configs/sst_cs_apps-unwanted-eln.yaml
More context: https://fedoraproject.org/wiki/Changes/AspellDeprecation
=> Let's try to use different implementations for aspell

configs/sst_i18n-langpacks-eln.yaml
Update langpacks workload to include newly added langpacks packages.
=> Update for newly added subpackages in langpacks

configs/ssg_platform_tools-misc-c9s.yaml, configs/sst_kernel_rts-setup.yaml
- Unplacehold realtime-setup
- Update annobin packages
=> Fix annobin warnings in ELN

configs/sst_java-java-c9s.yaml, configs/sst_java-java.yaml, configs/sst_java-unwanted-c9s.yaml, configs/sst_java-unwanted.yaml
=> Drop java-1.8.0-openjdk & java-11-openjdk from ELN

configs/ssg_platform_tools-unwanted.yaml
This patch improves the comments describing the nasm and yasm packages in the platform tools unwanted list.
=> More comments about nasm and yasm

configs/sst_cs_infra_services-time-synchronization.yaml
This is going to be a RHEL-specific package not built in Fedora or ELN, per the maintainer: https://github.com/minimization/content-resolver-input/pull/941#issuecomment-1643361560
=> Placehold gpsd-minimal

configs/sst_cloud_experience.yml
This package adds integrations for Elastic File System (EFS) on AWS which allows users to mount and manage EFS much more efficiently.
=> cloud experience: add efs-utils

configs/sst_insights.yaml, configs/sst_subscription_manager-subscription-manager.yaml
See the individual commits for more details.
=> Update subscription-manager & Insights

configs/sst_cs_system_management-sys-management-c9s.yaml, configs/sst_cs_system_management-sys-management.yaml
=> Drop modulemd-tools from ELN

configs/sst_network_drivers-appstream-arch.yaml, configs/sst_network_drivers-appstream.yaml, configs/sst_network_drivers-baseos.yaml, configs/sst_network_drivers-bluefield.yaml, configs/sst_network_drivers-rhel-only.yaml, configs/sst_network_drivers-unwanted.yaml, configs/sst_network_drivers-wireless.yaml
JIRA: https://issues.redhat.com/browse/PTT-2950
=> rename sst_nic_rdma -> sst_network_drivers

configs/eln_extras_meta.yaml
Looks like this was dropped but we need it
=> Add nss-pam-ldapd to the ELN Extras workload for Meta

configs/ssg_idm-smb-client.yaml
See https://issues.redhat.com/browse/RHEL-13739
=> Add cepces package

configs/sst_cs_infra_services-time-synchronization.yaml
gpsd-minimal is replaced by gpsd in eln.
=> Remove gpsd-minimal from ELN

configs/sst_cs_infra_services-scanning-stack-c9s.yaml, configs/sst_cs_infra_services-scanning-stack.yaml, configs/sst_cs_infra_services-unwanted-c10s.yaml
Do not ship xsane until it is ported to GTK3.
=> Remove xsane from c10s

configs/sst_desktop-plymouth-c9s.yaml
https://src.fedoraproject.org/rpms/plymouth/c/6534ca93a154ef3c49bbfe7406a63aac5120d2cf
/cc @tpopela
=> Remove plymouth-theme-charge from ELN

configs/sst_gpu-X11-server.yaml, configs/sst_gpu-unwanted-eln.yaml
https://www.redhat.com/en/blog/rhel-10-plans-wayland-and-xorg-server
=> Remove Xorg from ELN

configs/sst_bootc-eln.yaml
- Add in initoverlayfs
- Test to see if c9s is possible or not.
=> Test potential bootc changes

configs/sst_desktop_applications-unwanted-eln.yaml
Followup commit after
https://github.com/minimization/content-resolver-input/commit/0387abd where I've removed TigerVNC from ELN, but I didn't mark it as unwanted.
=> Mark TigerVNC as unwanted

configs/sst_cs_system_management-text-processing.yaml
please remove tex-fonts-hebrew from ELN
=> remove tex-fonts-hebrew from ELN

configs/sst_i18n-bash-color-prompt-eln.yaml
=> add bash-color-prompt

configs/sst_program-lorax-template-eln.yaml
I found that sst_program-lorax-template-eln.yaml needs some update for fonts package list as per written in https://github.com/weldr/lorax/blob/master/share/templates.d/99-generic/runtime-install.tmpl file.
This PR will update the fonts package list.
@bstinsonmhk I see you are maintainer of this lorax template packages workload. 
Can you please review and merge this PR?
Thanks
=> Update fonts package list as per current lorax runtime-install.tmpl file

configs/sst_dotnet-dotnet-c9s.yaml, configs/sst_dotnet-dotnet-eln.yaml, configs/sst_dotnet-unwanted-c9s.yaml, configs/sst_dotnet-unwanted-eln.yaml
- Add .NET 8
- Drop .NET 6, and 7
=> Update .NET workload for CentOS Stream 10

configs/sst_kernel_maintainers-kernel-base-eln.yaml
based on recent builds of:
kernel-6.8.0-0.rc1.12.eln134
linux-firmware-20240115-2.eln134
=> kernel-base-eln: update eln set

configs/sst_i18n-extra-fonts-eln.yaml, configs/sst_i18n-fonts-eln.yaml
https://issues.redhat.com/browse/RHEL-14087
=> Move redhat-fonts from extra

configs/sst_security_compliance-reporting.yaml
Add a new workload to add the `openscap-report` package to ELN.
=> Add openscap-report to ELN

configs/eln_extras_kde.yaml
=> remove ksysguard

configs/sst_gpu-Wayland-Infrastructure-eln.yaml
=> Add gnome-ponytail-daemon in eln

configs/sst_cs_apps-perl-XML-Simple.yaml
It was required in JIRA RHEL-24166
=> Add perl-XML-Simple to ELN

configs/sst_cloud_experience.yaml
Adding a package for the opentelemetry collector as well as AWS Cloudwatch configuration files.
=> [sst_cloud_experience] Add opentelemetry-collector

configs/sst_cs_infra_services-performance-tuning-cs9.yaml
=> For CS10 add tuned-ppd, replacing power-profiles-daemon

configs/sst_cs_apps-apps-unsorted-c9s.yaml, configs/sst_cs_apps-apps-unsorted-eln.yaml
=> Add pcre2-tools as for the customer RFE

configs/sst_cs_apps-apps-unsorted-c9s.yaml, configs/sst_cs_apps-apps-unsorted-eln.yaml
=> Add libzip-tools as for the customer RFE

configs/sst_cs_software_management-package-manager-dnf5.yaml
Part of https://github.com/fedora-eln/eln/issues/175
=> Add DNF 5 to RHEL 11

configs/sst_desktop_applications-nautilus-eln.yaml
Resolves: https://issues.redhat.com/browse/CS-2020
/cc @tpopela
=> Drop sushi from c10s and eln

configs/ssg_idm-freeradius-server.yaml
These subpackages should be checked as well when running content resolver.
=> Add FreeRADIUS subpackages

configs/sst_network_management-main.yaml, configs/sst_network_management-nispor.yaml, configs/sst_network_management-unwanted-c10s.yaml
=> Drop nispor from c10s and ELN

configs/sst_desktop_applications-qt6.yaml
Part of Qt 6.7
See internal to RH https://issues.redhat.com/browse/DESKTOP-882
=> This is part of Qt 6 now

configs/sst_cs_apps-man-pages-c9s.yaml
=> Remove man-pages-overrides from ELN and c10s

configs/sst_storage_management-packages.yaml
- restore forgotten `mtx` package
- update `libblockdev` subpackages
=> storage management updates

configs/sst_storage_io-packages.yaml
This adds the libnvme and nvme-cli packages to sst_storage_io-packages
=> Add libnvme and nvme-cli to sst_storage_io-packages

configs/sst_cs_infra_services-valkey.yaml
=> Add valkey

configs/cee-support-workload-c9s.yaml
Also, fix the RPM name of ptyprocess.
Related: CS-2178
=> Drop rig from ELN and c10s

configs/sst_security_special_projects-keylime.yaml
Remove all dependencies that are not unique to Keylime
=> Fix Keylime workload packages

configs/sst_filesystems-userspace.yaml
JIRA: https://issues.redhat.com/browse/RHEL-39058
=> sst_filesystems-userspace: add ktls-utils

configs/sst_storage_management-packages.yaml
@prajnoha can you please verify I have these right?
=> Update sid subpackages for sst_storage_management

configs/sst_arch_hw.yaml, configs/sst_arch_hw_eln.yaml
=> sst_arch_hw: add missing pcm

configs/sst_cs_system_management-sys-management.yaml
remove opal-prd  from eln and c10s
https://issues.redhat.com/browse/RHELMISC-4838
=>     remove opal-prd from eln and c10s

configs/sst_i18n-extra-fonts-eln.yaml
We found that we can remove these 3 unwanted font packages as no other package need them.
=> Remove these leaf font packages as no other package need them

configs/sst_i18n-fonts-eln.yaml
=> Drop sil-mingzat-fonts

configs/sst_cs_apps-python-crb-c10s.yaml, configs/sst_cs_apps-python-crb-eln.yaml
=> Pull hatchling into CRB

configs/sst_i18n-gnome-desktop-testing.yaml
Resolves: RHEL-36177
/cc @fujiwarat
=> Add gnome-desktop-testing

configs/sst_arch_hw.yaml
Intel has dropped maintenance of this project and archived it.
@dledford please confirm
=> Drop dptfxtract

configs/sst_ccs-desktop-documentation.yaml, configs/sst_cs_apps-scm.yaml, configs/sst_cs_system_management-sys-management.yaml, configs/sst_desktop-branding.yaml, configs/sst_desktop-gnome-classic-session.yaml, configs/sst_kernel_security-intel-qat.yaml, configs/sst_kernel_security-kpatch.yaml, configs/sst_network_drivers-bluefield.yaml, configs/sst_network_drivers-rhel-only.yaml, configs/sst_openstack.yaml, configs/sst_program-lorax-template.yaml, configs/sst_sap.yaml, configs/sst_security_crypto-openssl.yaml
=> Convert all placeholders to new syntax, add openssl-fips-provider

configs/sst_desktop_applications-ptyxis.yaml
=> Replace gnome-terminal with ptyxis

configs/sst_system_roles-rhel_mgmt.yaml
=> Add ansible-collection-redhat-rhel_mgmt placeholder

configs/eln_extras_kde.yaml, configs/repository-fedora-eln-extras.yaml, configs/repository-fedora-eln.yaml, configs/sst_kernel_maintainers-kernel-base.yaml, configs/sst_virtualization-all.yaml
This depends on bluez-obexd which is not shipped for s390x.
/cc @tdawson
=> Fix bluedevil arches

configs/eln_extras_automotive.yaml
Adding Automotive SIG packages to ELN Extras.
=> Add automotive packages to ELN extras

configs/sst_filesystems-userspace-unwanted.yaml, configs/sst_filesystems-userspace.yaml, configs/sst_program-lorax-template.yaml
gfs2 is being removed in RHEL 10
=> Drop gfs2-utils

configs/sst_desktop-unwanted.yaml, configs/sst_desktop_applications-unwanted.yaml, configs/sst_desktop_firmware_bootloaders-unwanted.yaml, configs/sst_desktop_platform_technologies-unwanted.yaml
=> Mark totem-pl-parser as unwanted

configs/sst_i18n-langpacks.yaml
Let's add remaining 2 langpacks metapackages as well
langpacks-mni
langpacks-sat
=> We want to add remaining langpacks-mni and langpacks-sat packages also

configs/sst_pt_llvm_rust_go-rust-toolset.yaml
=> Add rust debugger and wasm32 subpackages

configs/eln_extras_fedora-packager.yaml, configs/eln_extras_kde.yaml, configs/repository-fedora-eln.yaml
=> kde: marknote replaces knotes

configs/repository-fedora-eln-extras.yaml, configs/repository-fedora-eln.yaml
https://pagure.io/pungi-fedora/pull-request/1304
=> Update compose location for ODCS decommissioning

configs/sst_cs_system_management-text-processing.yaml
* add texlive-count1to, texlive-everyshi, texlive-multitoc, texlive-everysel, texlive-pdfcolfoot, texlive-pdfmanagement-testphase, texlive-xfrac
* remove texlive-xmltexconfig
=> add deps for texlive-2024

configs/eln_extras_python.yaml
The packages are unwanted in eln, but desired in eln extras. I hope that's alright.
=> Initial ELN Extras Python config

configs/sst_dotnet-dotnet.yaml
=> Add dotnet9.0

.github/workflows/config-check.yml, configs/sst_cs_apps-nodejs.yaml, configs/sst_cs_base_utils-text-processing.yaml
https://gitlab.com/redhat/centos-stream/release-engineering/comps/-/merge_requests/532
/cc @ngothan
=> Update texlive subpackages for 2024

configs/sst_container_tools-unwanted.yaml, configs/sst_container_tools.yaml
https://gitlab.com/redhat/centos-stream/release-engineering/pungi-centos/-/merge_requests/818
/cc @jnovy
=> slirp4netns is still wanted in RHEL 10

configs/sst_cs_base_utils-text-processing.yaml
Add new subpackages texlive-firstaid and texlive-hypcap to AppStream
Resolves: RHEL-65862
=> Add new subpackages texlive-firstaid and texlive-hypcap to AppStream

configs/sst_display_i18n-bash-color-prompt.yaml, configs/sst_display_i18n-extra-fonts.yaml, configs/sst_display_i18n-fonts.yaml, configs/sst_display_i18n-gnome-desktop-testing.yaml, configs/sst_display_i18n-hunspell-dictionaries.yaml, configs/sst_display_i18n-hyphenation-rules.yaml, configs/sst_display_i18n-input-methods.yaml, configs/sst_display_i18n-langpacks.yaml, configs/sst_display_i18n-tools.yaml
at this point the files are not renamed
=> rename sst_i18n to sst_display_i18n

configs/sst_desktop_applications-papers.yaml
=> papers replaces evince in RHEL 10

configs/repository-fedora-eln.yaml
https://docs.fedoraproject.org/en-US/packaging-guidelines/Python/#_linters
=> Filter python3-coverage in ELN

configs/sst_cs_infra_services-printing-stack.yaml
=> Add pappl-retrofit library into c10s

configs/sst_cs_base_utils-text-processing.yaml
https://src.fedoraproject.org/rpms/texlive/c/ea82da9a7682ba995140b23c8faf47fcf0aac249?branch=eln
https://gitlab.com/redhat/centos-stream/rpms/texlive/-/commit/ea82da9a7682ba995140b23c8faf47fcf0aac249
/cc @ngothan
=> Drop texlive-xdvi

configs/sst_kernel_livepatching-kpatch.yaml, configs/sst_kernel_livepatching-tpm.yaml
kpatch and tpm were moved under a new sst
=> move kpatch and tpm under sst_kernel_livepatching

configs/eln_extras_mailman3.yaml
- drop standalone hyperkitty and postorius
- add python3-mailman-web which pulls in the above two
- add python3-mailman-hyperkitty
- generate sorted list with poi-tracker
=> Update mailman3 config

configs/sst_network_firewall-tools.yaml, configs/sst_network_firewall-unwanted.yaml
=> Splitting sst-network-firewall from sst-networking-core

configs/eln_extras_meta.yaml
https://src.fedoraproject.org/rpms/sedutil/c/5a431de8d73b061bf53349017149e037b8ec2c96
/cc @davide125 @michel-slm
=> Drop sedutil on ppc64le

configs/sst_display_window_management-Wayland-Infrastructure.yaml
https://issues.redhat.com/browse/RHEL-66307
/cc @tpelka83
=> Drop egl-wayland

configs/eln_extras_meta.yaml
Also manage the inventory with poi-tracker, which sorts the output
=> meta: add poi-tracker

configs/sst_display_productivity-thunderbird.yaml
thunderbird is not build on s390x so make everything arch_packages.
=> thunderbird is not build on s390x

configs/sst_pt_perf_debug-performance-tools.yaml
https://src.fedoraproject.org/rpms/dyninst/c/15cf32d088a98a08df8d1cd3db2dd6390829a3e8
/cc @codonell
=> Drop dyninst-testsuite

configs/sst_cs_base_utils-java-maven-c10s.yaml
See: https://fedoraproject.org/wiki/Changes/Maven4
=> Add maven4 to ELN

configs/eln_extras_meta.yaml, configs/eln_extras_meta_tracing_profiling.yaml
Move retsnoop here and start tracking perfetto
=> meta: split off tracing packages

configs/rhel-sst-ansible--core.yaml
=> Fix ansible-core workload

configs/eln_extras_meta_hw.yaml
=> [eln_extras][meta_hw] track e_smi_tool

configs/rhel-sst-security-crypto--crypto-policies.yaml
=> Add crypto-policies-pq-preview

configs/eln_extras_wsl.yaml, configs/fedora_eln_only.yaml
eln_extras_wsl.yaml has wsl-setup for eln-extras
fedora_eln_only.yaml has fedora-eln-backgrounds for eln
=> Add eln_extras_wsl.yaml and fedora_eln_only.yaml

configs/rhel-sst-logical-storage--packages.yaml
Add snapshot manager packages for ELN and c10s.
=> Add snapm packages to sst-logical-storage workload

configs/rhel-sst-display-i18n--hunspell-dictionaries.yaml
This PR will add new hunspell-ka package in RHEL 11.
=> Add new hunspell-ka package in ELN

configs/rhel-sst-virt-tools--subsystem.yaml
Related: https://issues.redhat.com/browse/RHEL-92064
=> Add new libguestfs-fssupport package (RHEL only)

configs/rhel-sst-centos-stream-wsl.yaml
wsl-setup is now being added to RHEL 9/10.
Change config to move it from eln-extras to eln
=> Change wsl-setup to eln

configs/rhel-sst-kernel-maintainers--kernel-base.yaml
Related: https://issues.redhat.com/browse/RHEL-87452
=> Ship new kernel-modules-extra-matched meta package

configs/rhel-sst-pt-python-ruby-nodejs--unwanted-python3-eln.yaml
=> Mark python3.13 unwanted

configs/rhel-sst-cs-infra-services--development-packages.yaml
https://src.fedoraproject.org/rpms/ghostscript/c/f2e54de211fdacd9a5a38d3042abb1db13ea0e24
/cc @notroj
=> Update ghostscript-tools-fontutils name

configs/eln_extras_kde.yaml
These packages are all in EPEL 10 and listed in comps but were missing from ELN Extras.
/cc @tdawson
=> Add missing KDE packages

configs/rhel-sst-display-desktop-foundation--gnome-text-editor.yaml, configs/rhel-sst-display-productivity--flatpak.yaml
Rebase of #1355 
/cc @tpopela @owtaylor
=> Add libspelling, flatpak-rpm-macros, flatpak-runtime-config

configs/rhel-sst-pt-python-ruby-nodejs--python-crb-eln.yaml
See https://github.com/fedora-eln/eln/issues/278#issuecomment-3094715629
=> Add python3-build to desired ELN Python CRB packages

configs/rhel-sst-high-availability--userspace.yaml
See https://src.fedoraproject.org/rpms/pcs/c/096aab967fd057eee595319516871b334f5a33e4?branch=rawhide
=> pcs no longer needs python3-wheel
