freeipa-client-samba.yaml
freeipa-client.yaml
freeipa-trust-controller.yaml
freeipa.yaml
samba-domain-controller.yaml

As discussed with @asamalik, add a number of FreeIPA and Samba related use cases.
They differ by intended usage:
- a basic FreeIPA master, with CA and DNS roles
- a basic FreeIPA trust controller (CA, DNS, trust to Active Directory)
- a basic FreeIPA client (SSSD + a number of tools to enable NFS automount, etc)
- Samba running as a domain member in FreeIPA domain
- Samba running as an Active Directory domain controller on its own

Add FreeIPA and Samba-related use cases

---

eln-compose.yaml

Mono hasn't been carried in RHEL and there are no plans to add it.  Exclude it from ELN for now.

Remove mono

---

eln-compose.yaml

These packages are subpackages of the ARK kernel in ELN, but separate
packages in Fedora.  We need to make sure that we are using the packages
from the kernel packages in ELN.
Signed-off-by: Justin M. Forbes <jforbes@fedoraproject.org>

Remove kernel-headers and kernel-tools

---

eln-compose.yaml

The packages added in this PR are unwanted either because they are bad cryptography implementation, unmaintained, or simply not certifiable or redundant (same functionality already present in multiple crypto packages already and we do not want to add more).
Suggestions about some of the packages:
- libsodium:
seem to be dragged in only by dovecot to implement argon2, dovecot should be configured w/o libsdium for now, and readded later by using openssl interfaces once available there (being worked on for openssl 3.0)
- libssh2
seem to be dragged in only by libvirt, but is not required, the libvirt config for RHEL exclude use of libssh2
- libtomcrypt
seem to be dragged in only by mailman 2!
please use a common library like openssl instead, if not possible please exclude mailman2
also …

Crypto-related unwanted packages

---

configs/view-eln.yaml

Enterprise doesn't support btrfs, so there should be no need for btrfs-progs

Mark btrfs-progs as unwanted

---

configs/view-eln.yaml

Python 2.7 not maintained upstream, and marked as `deprecated()` in Fedora.
Python 3.6 is quickly becoming obsolete, and might presumably be pulled into a RHEL-like environment.

Mark python2.7 and python3.6 as unwanted

---

configs/sst_dotnet_java-dotnet.yaml
configs/sst_dotnet_java-java.yaml

I don't know what I am doing. This is me asking for advice.
1. Am I supposed to modify these files that say they are generated from rhel 8 appstream? Is there some other workload file where I should be placing things we want as candidates for ELN? Should I be creating new ones?
1. OpenJDK exists in a couple of locations:
```
configs/prototype-eln-buildroot-workload.yaml          
470:        - java-11-openjdk-devel                                                                                    
471:        - java-1.8.0-openjdk-javadoc                                                                               
472:        - java-1.8.0-openjdk-javadoc-zip
configs/rhel-8-appstream-comps-additional-devel.yaml
26:  - java-1.8.0-openjdk-devel …
```

Update .NET/Java ELN configuration

---

configs/sst_front_door-unwanted.yaml
configs/sst_front_door-web-console.yaml

I have some things that are still unclear to me:
* cockpit-podman is part of the "container-tools" module. Should that still live here, or are modules handled specially?
* The "cockpit" package already has a few "Recommends", like cockpit-packagekit. We definitively want them in RHEL 9. Should they be repeated explicitly in the yaml here, or is it fine to rely on `Recommends:`?
Thanks!

Add sst_front_door web console workload

---

configs/sst_dotnet_java-jmc.yaml

Hi, this adds JMC which is also under sst_dotnet_java. I copied from what was done in https://github.com/minimization/content-resolver-input/pull/22
JMC is delivered as a module in Fedora, does that change anything?

Update jmc ELN configuration

---

configs/unwanted-eln-packages.yaml

See https://fedoraproject.org/wiki/Changes/DeprecatePytoml
Sorry for the unrelated newline change, I've used the integrated GitHub editor and it just does this.

pytoml is deprecated and hence unwanted in ELN

---

configs/sst_ansible_automation_platform.yaml

Adding an Ansible automation workload with the packages that team knows
they currently need, which they will augment as their needs become more
well understood
Signed-off-by: Neil Horman <nhorman@redhat.com>

Add a stub workload for Ansible Automation (RHAAP)

---

configs/sst_front_door-composer.yaml
configs/sst_front_door-podman.yaml
configs/sst_front_door-web-console.yaml

Create separate workloads for supported applications (podman and
composer), to better see and track their dependency trees.

Split Front Door web console workload

---

configs/sst_networking-core-network-management.yaml

Adds NetworkManager and a wider range of packages, that are optional dependencies.

add sst_networking-core-network-management.yaml

---

configs/sst_platform_security-crypto-policies.yaml

Although crypto-policies should be pulled by dependencies
this adds an explicit requirement to have them included.

Add crypto policies workload

---

configs/sst_networking-management-desktop.yaml

It's actually packaged as 'iproute'.
@cathay4t @thom311

sst_networking-management-desktop: Fix iproute2/iproute name

---

configs/sst_networking-fast-packet-processing.yaml

The documentation is also required.

Add dpdk-doc to fast packet processing.

---

configs/sst_networking-fast-packet-processing.yaml

The tuned-profiles-nfv-host-bin performance gain over
tuned-progiles-nfv-host profile is minimal.

sst_networking-fast-packet-processing: Remove nfv-host-bin.

---

configs/sst_networking-management-server.yaml

It is already included in desktop workload, but as it is carrying
the names "server" and "desktop", lets make it explicit that this
package is also expected on server as well.
Noticed by Davide.
@thom311 @cathay4t

sst_networking-management-server: add wpa_supplicant

---

configs/sst_kernel_debug-kdump.yaml
configs/sst_kernel_debug-misc.yaml

One workload is adding packages for vmcore dumping and analysing.
The other workload is adding packages for misc system admin tools which are maintained by kernel debug sst.

Sst_kernel_debug adds two workloads

---

configs/sst_virtualization_cloud-cloud_azure.yaml

Fix a copy-paste error and rename "RHEL on public and private clouds"
to "RHEL on Microsoft Azure". "RHEL on public and private clouds" name
is already used by another workload.

sst_virtualization_cloud: rename Azure workload

---

configs/sst_networking-management-server.yaml

On RHEL-8, the networking SST maintains jimctl as a dependency of
usb_modeswitch (2.5.x). Since usb_modeswitch 2.6.0, it no longer
depends on jimtcl but tcl (/usr/bin/tclsh). Drop the package.

sst_networking: mark "jimtcl" package as unwanted

---

configs/sst_networking-tools.yaml

Drop netsniff-ng from networking tools

---

configs/sst_virtualization_cloud-cloud.yaml
configs/sst_virtualization_cloud-cloud_azure.yaml

cloud-utils (unlike cloud-utils-growpart) is not really needed and
not currently shipped with RHEL8, drop it.

sst_virtualization_cloud: drop cloud-utils from packages

---

configs/unwanted-eln-packages.yaml

specifying beakerlib as unwanted for customer visibility

make beakerlib unwanted

---

configs/mingw-pkgs-exclusion.yaml

I used a script similar to the one below to gather RPMs
given a list of packages ($PKGS)
for pkg in $PKGS; do
b=$(koji latest-build --quiet f33 $pkg | cut -d" " -f1) # build
v=$(echo $b | sed "s/$pkg-\(.*\).fc3./\1/") # version
rpms=$(koji buildinfo $b | grep '^.mnt.koji' | grep -v debug |
grep -v src.rpm | grep -E 'x86_64|noarch' |
cut -f1)
echo "  # $pkg"
for rpm in $rpms; do
n=$(echo $rpm | sed "s/-$v.*rpm//" |
sed 's,^.mnt.koji.*fc3..[^/]*/,,')
echo "  - $n"
done
done

mingw packages not to be included

---

configs/sst_kernel_rats-tpm-exclusion.yaml
configs/sst_kernel_rats-tpm.yaml

tpm2-abrmd and tpm2-abrmd-selinux are still needed for gating tests.

TPM packages fixup

---

configs/sst_platform_tools-c++-development-full.yaml
configs/sst_platform_tools-c++-development.yaml
configs/sst_platform_tools-c++-runtime.yaml
configs/sst_platform_tools-c-development-full.yaml
configs/sst_platform_tools-c-development.yaml
configs/sst_platform_tools-c-runtime.yaml
configs/sst_platform_tools-libffi.yaml
configs/sst_platform_tools-ltrace.yaml
configs/sst_platform_tools-make.yaml
configs/sst_platform_tools-parsegen.yaml
configs/sst_platform_tools-tzdata.yaml
configs/sst_platform_tools-unwanted.yaml

The following commits contribute coverage from Platform Tools for: glibc, tzdata, libffi, ltrace, make, bison, byacc, flex.
I have additionally provided workloads to cover minimum C and C++ runtime environments, minimum C and C++ development environments, and a slightly more than minimum C and C++ development environment (includes static linking support). The development environments are very minimal and cover only the required compiler, assembler, linker, headers, objects etc. that would be required to compile, assemble, and link a C or C++ dynamic or statically linked binary or library.
In addition I have, at the request of Jeff Law, added mcpp to our unwanted_packages list and cleaned up the ownership of that list to reflect ownership by sst_platform_tools.

Add Platform Tools workloads for: glibc, tzdata, libffi, ltrace, make, bison, byacc, flex, and C/C++ runtime/dev.

---

configs/sst_identity_management-unwanted.yaml

`Signed-off-by: Alexander Scheel <ascheel@redhat.com>`
----
I maintain `freeradius` (the server package) and co-maintain `pam_radius` in EPEL and Fedora. We're keeping FreeRADIUS Server, but have no intention of pulling in `pam_radius` or `freeradius-client`. These currently aren't required by any packages in the content set, so I'm not sure if it is necessary to open a PR removing them.

Mark pam_radius and freeradius-client as unwanted

---

configs/sst_networking-firewall-unwanted.yaml

Force other workloads to use "ebtables" so when we fix the alternatives
we get the correct ebtables-nft variant.

firewall: add unwanted ebtables-legacy

---

configs/sst_i18n-input-methods.yaml

ibus-m17n will be used instead of ibus-sayura since RHEL9.
Signed-off-by: Takao Fujiwara <tfujiwar@redhat.com>

Delete ibus-sayura from sst_i18n-input-methods.yaml

---

configs/sst_kernel_debug-kdump.yaml

Remove
- makedumpfile because it is included in kexec-tools package;
- snappy-devel because it is part of snappy, not a package;
- crash-ptrace-command because it is actually crash-trace-command.
Add
- crash-ptdump-command

Make changes to the kdump workload

---

configs/sst_kernel_rats-perf.yaml

- Change to rt-tests, since renaming doesn't occur at this stage.
- put packages not in Fedora in a package_placeholders: section
- update yaml spacing
Signed-off-by: John Kacur <jkacur@redhat.com>

kernel_rats-perf.yaml: Update for packages not in fedora

---

configs/sst_networking-tools.yaml

It is a better fit for EPEL or so.

sst_networking-tools: drop socat

---

configs/sst_cs_apps-unwanted-ruby.yaml

rubypick is not needed if Ruby is configured properly:
https://src.fedoraproject.org/rpms/ruby/blob/master/f/ruby.spec#_71

Remove rubypick

---

configs/sst_dotnet_java-unwanted.yaml

java-latest-openjdk is a rolling package of the latest version of OpenJDK, which we want to make sure is explicitly excluded from RHEL.
java-17-openjdk will eventually provide the next long term support release for RHEL.

Make sure java-latest-openjdk does not end up in RHEL 9.

---

configs/sst_filesystems-userspace-unwanted.yaml
configs/sst_filesystems-userspace.yaml
configs/sst_platform_storage-packages.yaml

After cross-checking a few more things, these updates were made.
Filesystems:
- Added numerous packages that were overlooked.  
- Moved system-storage-manager back to the 'claimed' status.
Platform Storage:
- Fixed a typo in 'udisks', as it should be 'udisks2'.
- Added a dependent package that was not previously listed.

Fast content set updates

---

configs/sst_dotnet_java-dotnet.yaml

Upstream expects to release this around Nov 2021. It will be an LTS release. It's probably a good idea to add it to ELN for now.

Add .NET 6.0

---

configs/sst_kernel_rats-kernel-rt-base.yaml
configs/sst_kernel_rats-kernel-rt-develdebug.yaml

Use package_placeholders to specify details of kernel-rt packages
that are not yet in fedora.

sst_kernel_rats-kernel-rt: Update for packages not in fedora

---

configs/sst_kernel_rats-perf.yaml
configs/sst_kernel_rats-setup.yaml

rteval-loads was not showing up, I believe because the indentation in the yaml file was not consistent, so this fixes it.
rt-setup was not showing up, because it is not in fedora, and lacked a package-placeholders section, this fixes that.

2 more changes for the sst_kernel_rats team

---

configs/sst_dotnet_java-java.yaml

Added the future long-term support release of OpenJDK, java-17-openjdk. The dependencies are based on the current java-latest-openjdk in Fedora. java-17-openjdk will initially need java-latest-openjdk to bootstrap, but once built, it can depend on itself.

Add placeholder for java-17-openjdk

---

sst_identity_management-hesiod.yaml

Hesiod is not present in Fedora, and is marked deprecated in RHEL.  Accordingly, the binary package is called compat-hesiod.  It might be worth double-checking I got the source vs. binary distinction right in the yaml.

Add hesiod placeholder

---

configs/sst_i18n-hunspell-dictionaries.yaml

This will fix typo in the workload and thus the package list error.

Fix the typo in hunspell workload and rename filename

---

configs/sst_desktop-totem.yaml
configs/sst_desktop_applications-gnome-photos.yaml
configs/sst_desktop_applications-qt5.yaml

* Remove a totem subpackage that doesn't exist anymore
* Explicitly require exiv2 from GNOME Photos workflow
* Be explicit about all the required Qt 5 packages

Update sst_desktop(_applications) workflows

---

configs/sst_kernel_tps-criu.yaml

crit is used to analyze CRIU image files

Extend criu workload to include crit

---

configs/sst_desktop_applications-tigervnc.yaml

The tigervnc-selinux doesn't exist yet on Fedora, so we had to create
a package_placeholder entry, but I forget to remove it from the packages
section.

Fix the TigerVNC workflow

---

configs/sst_platform_tools-compat.yaml
configs/sst_platform_tools-gcc-toolset.yaml

We might need gcc-libraries to support applications built with the GCC Toolset, if a new toolset requires libraries not present in the system gcc.

gcc-toolset: Add gcc-libraries to package_placeholders.

---

configs/sst_kernel_ft-rasdaemon.yaml

Since ExclusiveArch in the RPM isn't being used.
Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>

rasdaemon: list every supported architecture

---

configs/sst_filesystems-userspace.yaml
configs/sst_platform_storage-packages.yaml

Adjusted the content set based on some errors in the platform storage workload [0] for ELN+Rawhide.
[0] https://tiny.distro.builders/workload-overview--sst_platform_storage-packages--repository-fedora-eln.html

FAST: Update the content set definitions for Platform Storage and Filesystems

---

configs/sst_coreos.yaml

Remove `cri-o` since that is provided via OpenShift.
Fixed the `systemd-container` requirement.

Update coreos definition to fix resolver errors.

---

configs/sst_kernel_maintainers-kernel-develdebug.yaml

*-debuginfo packages are not part of the repositories.
Signed-off-by: Jan Stancek <jstancek@redhat.com>

sst_kernel_maintainers: remove debuginfo packages

---

configs/sst_kernel_rats-perf.yaml

Limit the rt-tests suite to the x86_64 architecture.
Signed-off-by: John Kacur <jkacur@redhat.com>

sst_kerenl_rats-perf: Limit rt-tests to x86_64 architecture

---

configs/sst_high_availability-userspace.yaml

Removing pexpect from HA package list as this will not be needed in RHEL 9 (the python3-pexpect package takes care of everything we need).

Remove pexpect from HA package list

---

configs/sst_desktop_applications-nautilus.yaml

It was removed from Fedora and dropped upstream - https://src.fedoraproject.org/rpms/nautilus-sendto/c/740c0bf3323bff3f62f4dfc3d2e996b1843e5295?branch=master

Remove nautilus-sendto

---

configs/sst_desktop_applications-unwanted.yaml

mozjs78 is the current version that gjs and polkit use and we shouldn't
include the older ones.

Add mozjs68 to sst_desktop(_applications) unwanted list

---

configs/sst_desktop_applications-unwanted.yaml

GNOME Remove Desktop sounds unlikely to be good. :)

Fix typo in sst_desktop_applications-unwanted.yaml

---

configs/sst_high_availability-userspace.yaml

The packages listed below are provided in RHEL only.
fence-agents-aliyun
python3-gflags
resource-agents-aliyun
resource-agents-gcp

SST_HIGH_AVAILABILITY: Moved some packages to placeholders

---

configs/sst_platform_tools-c++-development-full.yaml
configs/sst_platform_tools-c++-development.yaml
configs/sst_platform_tools-c-development-full.yaml

Fixes commit eeb21a2ef008ba5353d14ef4c717864ca8fe1ce9 ("Add Platform
Tools C and C++ Runtime/Devel.") and commit
107af77ef635c4975283e09a41e5614b50356fe3 ("Add Platform Tools C
Runtime and Development.").
Suggested by Troy Dawson.

Replace glibc-headers-x86_64 with glibc-headers-x86

---

configs/sst_cs_infra_services-geoip.yaml
configs/sst_cs_infra_services-unwanted.yaml

The package is unusable without 3rd party subscription and it downlopads proprietary content. There is no way to properly test this and support
Signed-off-by: Tomas Hozza <thozza@redhat.com>

CS Infra Serv: moved geoipupdate to unwanted packages

---

configs/sst_dotnet_java-jmc.yaml

Use stream 7 instead of latest. There were green koji builds for f33 and f34 tags so also hoping for the package set stuff to be seen now.
https://koji.fedoraproject.org/koji/buildinfo?buildID=1604357
https://koji.fedoraproject.org/koji/buildinfo?buildID=1604333

Update jmc ELN configuration to use stream 7

---

configs/sst_edge.yaml

ignition is speculative, but worth including for now.
ostree,rpm-ostree are really just to ensure another usecase is logged
for those packages

Add edge packages

---

configs/sst_kernel_rats-kernel-rt-develdebug.yaml
configs/sst_kernel_rats-perf.yaml

Fix a package name typo
Try moving the kernel-rt-debuginfo-common-x86_64 block in an attempt to address resolver failure to see it

address resolver errors for perf and devel/debug workloads 

---

configs/sst_platform_tools-c++-development-full.yaml
configs/sst_platform_tools-c++-development.yaml
configs/sst_platform_tools-c-development-full.yaml
configs/sst_platform_tools-c-development.yaml

These packages are available on all architectures, but are only
installable on x86_64 and s390x.  On other architectures, they
have file conflicts with glibc-devel.
Red Hat GmbH, https://de.redhat.com/ , Registered seat: Grasbrunn,
Commercial register: Amtsgericht Muenchen, HRB 153243,
Managing Directors: Charles Cachera, Brian Klemm, Laurie Krebs, Michael O'Neill

Do not explicitly list glibc-headers-x86, glibc-headers-s390

---

configs/sst_arch_portfolio.yaml

set the maintainer to sst_arch_portfolio and add the missing 11
to openssl-ibmpkcs as the package is called openssl-ibmpkcs11
Signed-off-by: Dennis Gilmore <dennis@ausil.us>

arch_portfolio updates

---

configs/sst_arch_portfolio.yaml

s390utils-cmsfs does not exist so remove it from being required on s390x
Signed-off-by: Dennis Gilmore <dennis@ausil.us>

remove non-existant s390utils-cmsfs package

---

configs/sst_security_selinux-base.yaml
configs/sst_security_selinux-devel.yaml
configs/sst_security_selinux-tools.yaml

And also rename the maintainer to sst_security_selinux
Please let me know when this change is propagated so I can re-check the diff between rhel8 and this.

Add missing packages to SELinux workloads

---

configs/sst_cs_stacks-perl-5.30.yaml
configs/sst_cs_stacks-perl-5.32.yaml

List all binary non-debugging packages. That includes non-API package.
Because perl module is a root module for all Perl modules, it cannot
require other Perl modules. Thus the non-API packages cannot be moved
out of the perl module, hence perl workloads is the only meaningful
place for them.
Also the listing was updated from the current Fedora 34.

Fix perl modules package sets

---

configs/sst_dotnet_java-jmc.yaml
configs/sst_dotnet_java-unwanted.yaml

From checking the resolved contents, the build dependency on tycho and eclipse was not caught. This updates the content set to include them. Eclipse will need ecj so that is removed from the unwanted packages.

Update jmc package sets with explicit listing of tycho and eclipse

---

configs/sst_networking-fast-packet-processing.yaml

The workload is only supported in three arches, so
move all packages under them to avoid problems with
noarch packages not available on unsupported arches.
Signed-off-by: Flavio Leitner <fbl@redhat.com>

fast-packet-processing: Move all packages under arches.

---

configs/sst_networking-management-core.yaml
configs/sst_networking-management-desktop.yaml
configs/sst_networking-management-devel.yaml
configs/sst_networking-management-server.yaml

This content resolver is meant to list binary rpm package names instead,
so s/dhclient/dhcp-client/
Signed-off-by: Marcelo Ricardo Leitner <mleitner@redhat.com>
@cathay4t @thom311

Mention package name instead of rpm provides for dhclient

---

configs/sst_rhgs-unwanted.yaml

Resolution of where glusterfs libs and -devel packages come from
in RHEL 9 is required.
Josh Boyer and I have been having a discusion on the hallway track.
This is intended to surface the issue.

sst_rhgs-unwanted: remove glusterfs RPMs from ELN

---

configs/sst_kernel_tps-microcode.yaml

It is ridiculous it cannot be pulled from any other content set
definition that already exists.
Signed-off-by: Eugene Syromiatnikov <esyr@redhat.com>

configs/sst_kernel_tps-microcode.yaml: make microcode_ctl package x86_64-only

---

configs/sst_networking-firewall-tools.yaml
configs/sst_networking-firewall-unwanted.yaml

As per the documentation (like in the Cheat Sheet screenshot), it should
be the SST name, so that the workloads show up in places such as [1].
1.https://tiny.distro.builders/maintainer--sst_networking.html
Signed-off-by: Marcelo Ricardo Leitner <mleitner@redhat.com>
@erig0

Update the maintainer field to be the SST name

---

configs/sst_virtualization-all.yaml

As virt is not a module in Fedora, remove the line that enables the
virt module and update the filename for sst_virtualization to '_all'
as this file contains all Virt packages which will later be split
into BaseOS and AppStream

sst_virtualization: Update filename and remove module definition

---

configs/sst_kernel_tps-tracing.yaml

The bpftrace package does not exist on armv7hl

Update sst_kernel_tps-tracing workload

---

configs/sst_nic_rdma-appstream-arch.yaml
configs/sst_nic_rdma-appstream.yaml

Confirmed with Mellanox that mstflint, libvma, and ucx do not
support s390x.
Signed-off-by: Honggang Li <honli@redhat.com>

RDMA stack architecture specific packages

---

configs/sst_program-lorax-template.yaml

rdma-core isn't built on armv7hl and libmlx4 is actually
provided by libibverbs now.  Make this explicit.

Fix rdma-core packages

---

configs/sst_dotnet_java-java.yaml
configs/sst_dotnet_java-unwanted.yaml

Our original submissions only listed the packages by spec filename, and didn't include any subpackages produced by the same spec file. This adds the missing subpackages for java-1.8.0-openjdk, java-11-openjdk & byteman.
We also add the *-slowdebug & *-fastdebug packages to the unwanted list. Although these will be built, these should not be part of the package listings, as they are only used on demand from specific customer cases.

Add OpenJDK subpackages (including listing unshipped debug packages in unwanted)

---

configs/sst_nic_rdma-appstream.yaml
configs/sst_nic_rdma-baseos.yaml

rdma-core has ExcludeArch: %{arm}

sst_nic_rdma: no RDMA on armv7hl

---

configs/sst_kernel_rats-kernel-rt-base.yaml

This package is marked as unwanted in el9 content set and we do not want
to ship it to customers.

sst_kernel_rats-kernel-rt: Remove unwanted tuned-profiles-nfv-host-bin

---

configs/sst_desktop_applications-firefox.yaml
configs/sst_desktop_applications-thunderbird.yaml

See https://src.fedoraproject.org/rpms/firefox/c/8be51c4c516e8c1c244097307d4e28ae089f7fcc?branch=master and
https://src.fedoraproject.org/rpms/thunderbird/c/ba38d87f3a0110ed0ec4fe0b837a1857feaa8484?branch=master.

Builds for Firefox and Thunderbird are now enabled on s390x in Fedora

---

configs/sst_cs_apps-python-crb.yaml

New packages in RHEL8 that should carry over to RHEL9 as well.

Adding py3c-devel and py3c-doc to a workload for CRB

---

configs/sst_virtualization-all.yaml
configs/sst_virtualization-exclusion.yaml

- Updating package names to match Fedora
- Moving xorg-x11 package to it's supported arches
- Moving the rhevm-guest-agent package to the exclusion list
- Adding a package_placeholder for libguestfs-winsupport 

Virt SST: more minor updates to the Virtualization Content Set

---

configs/view-eln.yaml

These are useful for building Fedora, but we don't want them built
for ELN.

Add more packages to confirmed unwanted

---

configs/sst_kernel_rats-kernel-rt-unwanted.yaml

kernel-rt uses bpftool built by kernel, but it still wants the package.

sst_kernel_rats-kernel-rt: Remove bpftool from unwanted list

---

configs/sst_desktop-gnome-desktop.yaml

We actually do have it in the unwanted list as the polkit dialog is being provided by GNOME Shell nowadays.

Remove the polkit-gnome from requirements

---

configs/sst_openstack.yaml

This is retired in Rawhide, so even though there is an ELN build
it doesn't get pulled into a compose and doesn't show up in
Content Resolver

Adjust libcroco

---

configs/sst_cs_infra_services-mda.yaml

Cyrus-imapd-vzic is deprecated with cyrus-timezones package and not
built anymore. Cyrus-timezones is weak dependency of the main package.

Remove cyrus-imapd-vzic package

---

configs/sst_cs_infra_services-mda.yaml

Cyrus-timezones replaces vzic timezones compiler.
cyrus-imapd-utils depends on main package and main package depends on
utils subpackage thus it's enough to specify main package only.

Add cyrus-timezones to MDA content definition

---

configs/sst_platform_tools-unwanted.yaml

The only user of jsoncpp and rhash is CMake and we fix that up
so we don't need these packages.  Therefore we place them on the
unwanted list.

Add jsoncpp and rhash to the unwanted list.

---

configs/sst_cs_apps-unwanted-libcgroup.yaml

libcgroup doesn't support cgroupv2 and has been effectively dead for a long time.
However, I can see it being listed as [openstack dependency](https://github.com/minimization/content-resolver-input/blob/01838f97eb7c542ac500349b3a0eca00f229d70d/configs/sst_openstack.yaml#L47). @jwboyer Do you happen to know why is it there/where it comes from?

Explicitly mark libcgroup as unwanted

---

configs/sst_security_special_projects-aide.yaml
configs/sst_security_special_projects-application-whitelisting.yaml
configs/sst_security_special_projects-audit.yaml
configs/sst_security_special_projects-libcap.yaml
configs/sst_security_special_projects-nbde.yal
configs/sst_security_special_projects-rsyslog.yaml
configs/sst_security_special_projects-scrub.yaml
configs/sst_security_special_projects-sudo.yaml
configs/sst_security_special_projects-usbguard.yaml

Correct full name of Security Special Projects is
sst_security_special_projects not sst_security_special.
CC @radosroka

Fix sst_security_special_projects SST name

---

configs/sst_cs_apps-scm.yaml

Git-lfs pulls a lot of golang dependencies that we want to bundle in RHEL 9.
Making a conditional in Fedora package would make spec file larger and worse readable.
We decided to make git-lfs a "package placeholder" and pull only dependencies that we want.

Add git-lfs placeholder

---

configs/sst_openstack.yaml

Some of these packages are known to be not desired in the OS itself,
but are provided elsewhere.  Comment them out for now and we'll
adjust how to account for them in a different way later.

Adjust openstack workload

---

configs/sst_kernel_tps-unwanted.yaml

It was decided that we do not really need rtl-sdr* in the RHEL9, since it is
a software for quite a narrow range of hardware (Realtek RTL2832 based DVB-T
dongles). Currenly only rng-tools need rtl-sdr* and this dependency is being
removed.

Explicitly mark rtl-sdr{,-devel} as unwanted

---

configs/sst_platform_storage-packages.yaml

SID package with its sub-packages are new addition to F33+ (https://fedoraproject.org/wiki/Changes/SID) and planned for RHEL9+. Please, add these packages to the list.

Add SID to Platform Storage Supported Packages

---

configs/sst_kernel_tps-xdp.yaml

I will still be maintaining xdp-tools going forward, so let's move it into
sst_kernel_tps (but keep it as its own workload).
Signed-off-by: Toke Høiland-Jørgensen <toke@redhat.com>
----
#

XDP: Move from sst_networking to sst_kernel_tps

---

configs/sst_kernel_rats-tpm.yaml

Already have a request to add tpm2-pkcs11 to rhel8, so go ahead
and get it into rhel9.

sst_kernel_rats-tpm: Add tpm2-pkcs11 packages

---

configs/unwanted-eln-packages.yaml

In reality, we want to have `rubygems`, which is subpackage of `ruby`. It just needs different treatment then mark it unwanted. This is related to #165.

Remove from `rubygems` unwanted.

---

configs/sst_cs_apps-ruby.yaml

Tilt has gazillion dependencies and what is worser, half of them are circular. Luckily, they test just possible runtime dependencies which will be unused at the end. They are enabled on Fedora, just because they can be enabled. Therefore cut them off to reduce the Ruby dependency chain.
Also note that when dependency is not available, the tests are just skipped.

Use rubygem-tilt placeholder to reduce Ruby dependency chain.

---

configs/sst_desktop_applications-unwanted.yaml

Put qt (version 4) to unwanted list as only qt5 will be in RHEL 9

Add qt to unwanted packages

---

configs/sst_virtualization-all.yaml

Remove packages such as libguestfs, qemu-kvm, qemu-guest-agent and others that are packaged differently in RHEL v. Fedora ELN. Also, remove dependencies such as meson, ninja-build, ocaml that will be pulled in by other SRPMs.
And add 'package_placeholders' for qemu-kvm, libguestfs, virt-v2v, and update the definition for libguestfs-winsupport

Virt SST: Update 'required' list and add RHEL-only package_placeholders

---

configs/sst_desktop-gnome-desktop.yaml
configs/sst_desktop-unwanted.yaml

Currently some packages still require tracker, but will be ported soon.

tracker was replaced by tracker3

---

configs/sst_virtualization-all.yaml

Move some packages from package_placeholder to arch_packages to facilitate
arch specific builds of RHEL-only packages

Virt SST: Update arch_packages

---

configs/sst_virtualization-all.yaml

Virt SST: Remove amtterm and move mingw-* packages to virt-v2v placeholder

---

configs/sst_security_selinux-python-networkx-unwanted.yaml

A lot of unnecessary dependencies were originally used as BR and as weak
dependencies. As the optional functionality provided by these packages
is not needed for setools, we decided to drop them from BR and leave
them as weak dependencies only, see
https://src.fedoraproject.org/rpms/python-networkx/pull-request/7
Also we want to be sure that these components are not assigned to
sst_security_selinux and therefore mark them as unwanted even though
Recommends: should be ignored.
Signed-off-by: Petr Lautrbach <plautrba@redhat.com>

Add unwanted python-networkx dependencies

---

configs/sst_cs_system_management-text-processing.yaml

tthe workload failed (https://tiny.distro.builders/workload-overview--sst_cs_system_management-text-processing--repository-fedora-eln.html)  because  texlive-wasy2-ps and texlive-texconfig are removed in texlive-2020 upstream.

texlive-wasy2-ps and texlive-texconfig obsoleted in texlive-2020

---

configs/sst_rh_samba_storage.yaml
configs/sst_security_crypto-gnupg.yaml

This mostly summarizes list of dependencies of gnupg2 in RHEL, but also moves `pinentry` package from samba as agreed with Boris and Simo. Adding also @jwboyer as he is marked as a maintainer of the current samba "workload".

Move pinentry to the rest of GPG packages in crypto team

---

configs/sst_cs_system_management-other.yaml

AFAIK we want to add tracer only because of Cockpit so I am not
creating a separate workload but adding it here.

Add tracer to the sst_cs_system_management-other workload

---

configs/sst_cs_system_management-other.yaml

Adding the `modulemd-tools` package,
upstream is here https://github.com/rpm-software-management/modulemd-tools

Add modulemd-tools to the sst_cs_system_management-other workload

---

configs/sst_cs_software_management-unwanted.yaml

librhsm stays because it's not going to be merged with subscription-manager
plugins in the near feature.

Remove librhsm from sst_cs_software_management unwanted packages

---

configs/sst_cs_software_management-unwanted.yaml

python3-hawkey will be fully replaced with python3-libdnf
in the DNF 5 stack which has been postponed to the next release

Remove python3-hawkey from sst_cs_software_management unwanted packages

---

configs/sst_openstack.yaml

According to #rhos-delivery it might not be needed anymore

Drop libcroco from the Openstack workload

---

configs/sst_cs_infra_services-mda.yaml

While cyrus-imapd has built-in index and search engine it's broken
badly since 3.0 release. Xapian is stable supported replacement

Add xapian-core to the MDA workload

---

configs/sst_cs_infra_services-base-os-packages.yaml
configs/sst_cs_infra_services-unwanted.yaml

The initial plan was to deprecate hostname and replace it with
hostnamectl. In reallity hostnamectl is not drop-in replacement
and has few issues which block application from using it at early
stages (no dbus etc)

Drop hostname from the list of unwanted packages

---

configs/sst_cs_software_management-unwanted.yaml

We decided to keep the "lua" binary package (the CLI interpreter) around
after all.  It's built from the same Lua SRPM that we already own (as an
embedded interpreter in RPM), so there's not much additional maintenance
burden associated with the CLI interpreter itself (which alone can be
quite useful).

sst_cs_software_mgmt: bring Lua CLI back

---

configs/sst_cs_system_management-sys-management.yaml

opal-prd is missing in sst_cs_system_management-sys-management. It should be included so it can be built.

add missing opal-prd into /sst_cs_system_management-sys-management

---

configs/sst_virtualization_spice-exclusion.yaml

The Virt team requested for usbredir to stay.
It already appears in sst_virtualization-all.yaml, so
just remove it from spice-exclusion.

usbredir is wanted

---

configs/sst_cs_apps-unwanted.yaml

Since there were multiple bugs filed for missing libuv-devel in EL8, I suggest we include libuv and libuv-devel.
https://bugzilla.redhat.com/show_bug.cgi?id=1895872
@voxik @hhorak @jwboyer

Remove libuv from unwanted due to many bugs and issues (#1895872)

---

configs/sst_desktop_applications-unwanted.yaml

They do have new owners in RHEL 9

Don't mark qrencode and yajl as unwanted

---

configs/sst_cs_infra_services-unwanted.yaml

a2ps is brought in by perl-Font-AFM package, because it needs a font from a2ps. perl-Font-AFM can skip the test and remove a2ps dependency or require a font from RHEL - see https://src.fedoraproject.org/rpms/perl-Font-AFM/pull-request/1 .

Add a2ps as an unwanted package

---

configs/sst_cs_apps-unwanted-ruby.yaml

In ELN, we want only the rubygem-bundler which is build from ruby package, while in Fedora, there is also independent rubygem-bundler, which we don't want. It seems that content-resolver cannot make good enough distinction between these two. OTOH, independent rubygem-bundler is hopefully removed already, so we should be able to drop this.

rubygem-bundler is wanted, while it is not wanted as independent package

---

configs/sst_kernel_rats-tpm-exclusion.yaml
configs/sst_kernel_rats-tpm.yaml

We do not plan to support TPM1.2 in RHEL9 so drop the userspace packages.

Drop tpm1.2 support

---

configs/sst_networking-firewall-tools.yaml

This is to hopefully avoid a superficial issue in content resolver in
which packages Require "ebtables", but that makes content resolver think
package "ebtables-legacy" is wanted. Package "iptables-nft" has a
Provides for "ebtables".

firewall: add iptables-nft

---

configs/sst_cs_infra_services-printing-stack.yaml

cups-printerapp contains the printer application for supporting older devices which needs a driver.

Add cups-printerapp

---

configs/sst_cs_infra_services-printing-stack.yaml

nss-mdns can be added during the life cycle, if the solution with systemd-resolved + Avahi doesn't work.

printing-stack.yaml: don't require nss-mdns

---

configs/sst_kernel_rats-perf.yaml
configs/sst_kernel_rats-tools.yaml

python-schedutils (python3-schedutils) is no longer required by
rteval and tuna so drop the dependency
Signed-off-by: John Kacur <jkacur@redhat.com>

kernel_rats: python-schedutils not required

---

configs/sst_high_availability-userspace-unwanted.yaml
configs/sst_high_availability-userspace.yaml

It turns out that we don't want to include python3-clufter.  This will also
resolve an open dependancy chain that was pulling in clufter-{bin,cli,common}
when they shouldn't be.

SST_HIGH_AVAILABILITY: Moved python3-clufter to unwanted.

---

configs/sst_virtualization_spice-exclusion.yaml

In Fedora libphodav is required by spice-gtk.
This change may break spice-gtk build, until its spec file is modified.

SPICE: do not pull phodav

---

configs/sst_cs_apps-db-mariadb.yaml

package mariadb-server requires (mysql-selinux if selinux-policy-targeted)

Specify mysql-selinux explicitly because conditionals are not handled correctly

---

configs/sst_cs_apps-db-mysql.yaml

It was mentioned a correct thing is to put it to both, mariadb and also mysql workloads.

Add mysql-selinux specifically to mysql-server workload as well

---

configs/sst_openstack.yaml

I'm updating this list with the list of:
- Runtime requirements for OpenStack packages
- Packages installed in Dockerfiles for OpenStack containers
- Packages installed in overcloud and ironic-python-agent images

Fix the list of dependencies for OpenStack

---

configs/sst_platform_tools-unwanted.yaml

The list contains packages the team does not maintain in RHEL 8.
@codonell As discussed off-PR.

sst_platform_tools-unwanted.yaml: Update description

---

configs/sst_platform_tools-unwanted-future.yaml
configs/sst_platform_tools-unwanted.yaml

nscd should be removed from future ELN, but not the c9s iteration.
@codonell Internal records need updating as well.

sst_platform_tools-unwanted.yaml: Do not mark nscd as unwanted

---

configs/sst_platform_tools-unwanted.yaml

This continues a tradition I started with Red Hat Enterprise Linux 7. The concerns are pretty much unchanged (the `fgetln` implementation changed radically, but still has problems).
@codonell @JeffreyALaw As discussed internally.

sst_platform_tools-unwanted.yaml: Mark libbsd as unwanted

---

configs/sst_virtualization-exclusion.yaml

In RHEL, we use qemu-kvm that is different than qemu in fedora.
qemu-kvm is successfully added but qemu is still listed as included
in content resolver.
Explicitly exclude qemu to not include it RHEL.

Exclude qemu

---

configs/sst_networking-tools.yaml

It is already not included, but lets have it flagged otherwise.

sst_networking: mark dropwatch as unwanted

---

configs/sst_desktop-gnome-desktop.yaml

On RHEL all the supported GNOME Shell extensions are bundled and shipped in the
gnome-shell-extensions package.

Only list the gnome-shell-extensions package for GNOME Shell extensions

---

configs/sst_cs_apps-ruby-db-connectors.yaml
configs/sst_cs_apps-ruby.yaml

* Add binary RPMs from ruby SRPM except ruby-doc.
* Remove rubygem-bson, rubygem-mongo as we do not ship it.
As seeing the nodejs config file, nodejs-docs was not added to the `<packages>`, I did not add ruby-doc to the `<packages>` too.
https://github.com/minimization/content-resolver-input/blob/master/configs/sst_cs_apps-nodejs.yaml
@voxik review please.

Update Ruby related config files.

---

configs/sst_cs_apps-unwanted-ruby.yaml

Add rubygem-bson and rubygem-mongo to the unwanted source packages.
The comment style is like https://github.com/minimization/content-resolver-input/blob/253dabe7f9a1f750be471c585d008e4498a778c4/configs/sst_cs_apps-unwanted-perl.yaml#L9
@voxik review please.

Update unwanted Ruby packages.

---

configs/sst_openstack.yaml

OpenStack requires ebtables which is included in iptables-nft in
Fecora/ELN.

Add iptables-nft

---

configs/sst_cs_apps-scm-eln.yaml
configs/sst_cs_apps-scm.yaml

https://github.com/minimization/content-resolver-input/issues/490#issuecomment-779743596

split sst_cs_apps-scm workload into two

---

configs/sst_desktop-gnome-desktop.yaml

Revert the previous change as the gnome-shell-extensions is an SRPM and not RPM

Fix the gnome-desktop workload

---

configs/sst_desktop-unwanted.yaml

It was moved to another subsystem

Drop libaec from sst_desktop unwanted

---

configs/sst_i18n-input-methods.yaml

https://fedoraproject.org/wiki/Changes/ibus-anthy_for_default_Japanese_IME

i18n input-methods: change Japanese IME from ibus-kkc to ibus-anthy

---

configs/sst_ccs-desktop-documentation.yaml

It was retired in upstream in GNOME 40

Drop gnome-getting-started-docs

---

configs/sst_desktop-gnome-desktop.yaml

Be explicit about the version that we depend on.

Include mozjs78 in the GNOME Desktop workload

---

configs/sst_desktop-gnome-classic-session.yaml
configs/sst_desktop-unwanted.yaml

GNOME 40 uses horizontal workspaces by default, so this is not needed anymore.

Drop gnome-shell-extension-horizontal-workspaces from GNOME Classic workload

---

configs/sst_desktop-gnome-desktop.yaml

On RHEL it isn't a separate package, but part of gnome-shell-extensions

Move gnome-shell-extension-dash-to-dock to package placeholders

---

configs/sst_kernel_debug-kdump.yaml

Both two packages are supported in rhel7 and rhel9, but not added into
Fedora in the past. Recently their ahthor and maintainer has added them
into Fedora, so add them into rhel9 content-set.
https://src.fedoraproject.org/rpms/crash-trace-command
https://src.fedoraproject.org/rpms/crash-gcore-command
The supportd ARCHes are:
crash-trace-command:
- aarch64
- ppc64le
- s390x
- x86_64
crash-gcore-command:
- aarch64
- ppc64le
- x86_64

sst_kernel_debug: add crash-trace-command and crash-gcore-command

---

configs/sst_cs_apps-python-devel.yaml

We support building Python RPM packages so these tools should be included in AppStream.
CC @encukou @hroncok

Add new workload for packages needed to build Python RPM packages

---

configs/sst_kernel_debug-unwanted.yaml

Package crash-ptdump-command is not supported any more, so discard it from
Fedora and RHEL9.

sst_kernel_debug: mark crash-ptdump-command as unwanted

---

configs/sst_nic_rdma-unwanted.yaml

qperf is almost dead in upstream.
Signed-off-by: Honggang Li <honli@redhat.com>

make 'qperf' as unwanted package

---

configs/sst_desktop_applications-nautilus.yaml
configs/sst_desktop_applications-unwanted.yaml

file-roller isn't needed anymore as the functionality was (mostly) moved
to Nautilus.

Mark file-roller as unwanted

---

configs/sst_security_crypto-unwanted.yaml

cc @simo5, please ack
(This package just got assigned to Python Maint under a incorrect reason, so before I move it back to @lnykryn / @kdudka, I also went ahead and explicitly marked is as unwanted.)

python-crypto is bad crypto

---

configs/sst_dotnet_java-java.yaml
configs/sst_dotnet_java-unwanted.yaml

Removing the fake build dependency in java-17-openjdk should allow java-latest-openjdk to be dropped
We do want debug packages, which are now included in CRB (already the case for RHEL 8.4.0)

We don't want rhino or java-latest-openjdk

---

configs/sst_program-lorax-template.yaml

This package is retired in F34, and would have been brought in by dependencies anyway, so stop listing it explicitly.

lorax-template: Remove xorg-x11-server-utils

---

configs/sst_cs_apps-db-postgresql.yaml

Requested to RHEL-8, so let's have it in RHEL-9 as well: https://bugzilla.redhat.com/show_bug.cgi?id=1935889

Add pg_repack to the postgresql workload

---

configs/sst_networking-firewall-unwanted.yaml

We want the iptables-nft variants in RHEL-9.

firewall: unwanted: add iptables-legacy{,-libs}

---

configs/sst_identity_management-hesiod.yaml

This field was made mandatory in
aad1697129d260f852259610d891539766abdd95 but not added to existing
packages, resulting in hesiod not showing up.

Add `srpm` entry to hesiod

---

configs/sst_security_special_projects-rsyslog.yaml

Requested to RHEL-8, so let's have it in RHEL-9 as well: https://bugzilla.redhat.com/show_bug.cgi?id=1869874

Add rsyslog-udpspoof to rsyslog workload

---

configs/sst_kernel_ft-redfish-finder.yaml

redfish-finder parses the output of dmidecode and this is only a relevant workflow on x86_64 and aarch64.
Signed-off-by: Joel Savitz <jsavitz@redhat.com>

redfish-finder: add x86_64 and aarch64 arch exclusivity

---

configs/sst_conatiner_tools.yaml

The python-podman-api package is no longer required in RHEL9 as it's not part of the container-tools module.

Remove python-podman-api

---

configs/sst_kernel_tps-tracing.yaml

OpenCSD is a library for parsing ARM CoreSight traces in perf.

sst_kernel_tps-tracing: add opencsd library

---

configs/sst_platform_storage-packages.yaml

The specification of kmod-kvdo for the SRPM to the 'vdo' package was by
mistake.  This change fixes that typo.

SST_PLATFORM_STORAGE: Fixed SRPM definition for vdo placeholder.

---

configs/sst_identity_management-ansible-freeipa.yaml
configs/sst_identity_management-freeipa-client-samba.yaml
configs/sst_identity_management-freeipa-client.yaml
configs/sst_identity_management-freeipa-server-dc.yaml
configs/sst_identity_management-freeipa-server-full.yaml
configs/sst_identity_management-freeipa-server.yaml
configs/sst_identity_management-idm-client-tools.yaml

distrobaker now renames "freeipa" and "freeipa-healthcheck" in both ELN and C9S. Use the new names directly.
This is a follow up to my discussion with @asamalik .

Rename freeipa to ipa

---

configs/sst_cs_system_management-sys-management.yaml
configs/sst_cs_system_management-sys-monitoring.yaml

When adjusting workloads, forgot to make some packages arch specific, thus make them failing. Fixed with this commit (mostly s390x and ppc64le only packages)

sst_cs_system_management : Some packages in workloads need to be arch specific

---

configs/sst_nic_rdma-appstream.yaml

qperf is dead in upstream. It had been included in rdma-unwanted and
rdma-appstream. Let's fix this mistake.
Signed-off-by: Honggang Li <honli@redhat.com>

remove qperf from rdma appstream

---

configs/sst_cs_system_management-sys-management.yaml
configs/sst_desktop-gnome-desktop.yaml

Move lcms2 to the gnome-desktop workload

---

configs/sst_desktop-cheese.yaml
configs/sst_desktop-totem.yaml
configs/sst_desktop-unwanted_eln.yaml

We won't have time to move Cheese and Totem away from using them, so we
are targeting RHEL 10 there, hence create a new unwanted_eln file and
move the definitions there.

Make clutter* and cogl package wanted again on RHEL 9

---

configs/sst_platform_tools-unwanted.yaml

Comment it out in sst_platform_tools unwanted file, but leave is there
for clarity (as requested by Tilmann Scheller)

cppunit is owned by sst_desktop

---

configs/sst_kernel_tps-perf.yaml
configs/sst_kernel_tps-tracing.yaml

The perf package currently conflicts with libtraveevent.

sst_kernel_tps: move perf into its own workload

---

configs/sst_graphics_infrastructure-Wayland-Infrastructure.yaml

Theres are debugging tools that may need to be run on a customer machine and,
more importantly, they have additional Requires that we need to pull in.
cc @csoriano1618

Add libinput-utils to the Wayland workload

---

configs/sst_kernel_maintainers-kernel-base.yaml

We were listing only linux-firmware, but there are other packages
created by linux-firmware src.rpm that we were not listing, and
that are installed by default or there is at the moment a kernel module
which is built and requires the firmware provided by them.
There is one exception here though, I'm not adding libertas-sd8787-firmware,
because it seems we probably should not be building on centos/rhel the kernel
modules that require it anymore (mwifiex_sdio, btmrvl_sdio), so leaving this
out for now. And on errata this specific firmware package also falls
into the "not in Product Listings" category already.
See also https://issues.redhat.com/browse/RHELPLAN-46582
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>

Add missing binary packages created by linux-firmware component

---

configs/sst_kernel_maintainers-kernel-unwanted.yaml

Some firmware packages are not needed anymore, as the firmware they
provide are not used by latest kernels in RHEL (eg. due module not
being built or disabled). Thus add them to the unwanted.
See https://issues.redhat.com/browse/RHELPLAN-46582 for more details.
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>

Add unwanted firmware packages to the kernel unwanted list

---

configs/sst_kernel_maintainers-kernel-base.yaml

The kernel src.rpm creates a binary kernel "meta" package that has no
files, it just pulls/requires kernel-core and kernel-modules (this was
done after the kernel was split into -core/-modules/-modules-extra on
Fedora). Just noted that we are missing it on the kernel-base list, thus
add it.
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>

Add missing kernel "meta" package to the sst_kernel_maintainers-kernel-base

---

configs/sst_edge.yaml

We need the installer to be part of the system to be used in edge.
cc @nullr0ute
Signed-off-by: Antonio Murdaca <runcom@linux.com>

configs: add coreos-installer to sst_edge

---

configs/sst_virtualization-all.yaml

Dropping the packages as they are no longer required in RHEL 9

Virt SST: drop fuse-sshfs and SLOF

---

configs/sst_cs_apps-ruby.yaml

We don't explicitly need rubygem-tilt. This was just failed attempt to provide placeholder providing limited set of BRs, otherwise rubygem-tilt pulls in almost "everything".

Remove references to rubygem-tilt

---

configs/sst_graphics_infrastructure-codecs.yaml

It was pulling `vorbis-tools` into the compose despite `vorbis-tools` is on the list of unwanted packages of `sst_cs_plumbers`.

sst_graphics_infrastructure-codecs: remove vorbis

---

configs/sst_edge.yaml

In practice, rpm-ostree requires this today.  It's not
expressed as a hard dependency because we may do something else
in the future.

edge: Require nss-altfiles

---

configs/sst_subscription_manager-subscription-manager.yaml

subscription-manager-initial-setup-addon is deprecated, not working with
the newer Anaconda APIs, and thus being removed from RHEL 9:
https://bugzilla.redhat.com/show_bug.cgi?id=1941904
Newer versions of Anaconda can register systems during the installation,
so this is less of a concern.
rhsm-gtk is removed too, as it is build only in RHEL because
subscription-manager-initial-setup-addon is too.

rhsm: drop subscription-manager-initial-setup-addon

---

configs/sst_openstack.yaml

Based on the mail discussion (May 2021), pymongo will either not
be needed in OSP17 or will be shipped for OSP outside of RHEL.

Removing pymongo from openstack workload

---

configs/sst_kernel_rats-sysfsutils.yaml

- sysfsutils needs to be included in RHEL 9.

sst_kernel_rats: Add sysfsutils config workload

---

configs/sst_cs_apps-ruby.yaml

There is not ABRT in ELN (AFAIK) therefore there is no use for Ruby ABRT support.

Drop rubygem-abrt from Ruby package set.

---

configs/sst_kernel_maintainers-kernel-develdebug.yaml

We miss the kernel-debug* packages on the list. They are being always
built on eln now, so we should list them too.
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>

sst_kernel_maintainers: add kernel-debug* packages to develdebug list

---

configs/automotive-c8s-image-manifest.yaml
configs/automotive-c8s-package-manifest.yaml

As discussed with @asamalik added an empty environment for the automotive workload based on c8s

Add an environment with empty package list for automotive and refer the same in automotive workload

---

configs/sst_identity_management-unwanted.yaml

IPA 4.9.6 no longer depends on python3-custodia.
See: https://pagure.io/freeipa/issue/8882
Signed-off-by: Christian Heimes <cheimes@redhat.com>

sst IdM: Mark custodia as unwanted

---

configs/sst_platform_storage-packages-unwanted.yaml

This came up in a couple of threads while talking about ownership for python-psutil.  This commit will clearly indicate that we are not willing to take ownership of this component.

SST_PLATFORM_STORAGE Marked python-psutil as unwanted.

---

configs/sst_networking-management-desktop.yaml
configs/sst_networking-management-server.yaml

`ModemManager-vala` should be in buildroot repo as it was in RHEL8
till customer requested.

sst_networking: Remove ModemManager-vala from explicit list

---

configs/cee-support-workload.yaml

The python-pexpect and python-ptyprocess packages are needed by sos so
that the `collect` function of that package is functional.
Signed-off-by: Jake Hunsaker <jhunsake@redhat.com>

Add pexpect and ptyprocess to CEE support tools

---

configs/sst_platform_storage-packages-unwanted.yaml

This package should not be tagged against platform_storage as there are no more dependencies.

SST_PLATFORM_STORAGE: Marked rust-packaging as unwanted.

---

configs/sst_cs_apps-java-ant.yaml

ant-apache-log4j package was removed [from Fedora](https://src.fedoraproject.org/rpms/ant/c/53cd5c1e0878eb050686e638f23a2511b8cc566c) and [from CentOS Stream](https://gitlab.com/redhat/centos-stream/rpms/ant/-/commit/99c07787fbbebbd705e3060302f4e49ac49c002a)

Remove ant-apache-log4j from Apache Ant workload

---

configs/sst_security_compliance-unwanted.yaml

- Add `oval-graph` to list of unwanted packages
- `oval-graph` will be repurposed and its inclusion is postponed

Add oval-graph to sst_security_compliance unwanted

---

configs/sst_filesystems-userspace-unwanted.yaml

These packages were assigned to sst_filesystems as the dependencies for
ceph in RHEL 9 but we no longer require these to build ceph, marking
them as unwanted.
Signed-off-by: Boris Ranto <branto@redhat.com>

sst_filesystems: Add unwanted packages

---

configs/sst_filesystems-userspace-unwanted.yaml

This package was assigned to  sst_filesystems as the dependency for ceph
in RHEL 9. We managed to remove that dependency so I am marking the
package as unwanted.
Signed-off-by: Boris Ranto <branto@redhat.com>

sst_filesystems: Add fmt to unwanted packages

---

configs/sst_kernel_maintainers-kernel-base.yaml

Signed-off-by: Cestmir Kalina <ckalina@redhat.com>

Rename kernel-abi-whitelists -> kernel-abi-stablelists

---

configs/sst_kernel_tps-tracing.yaml

Bcc-tools package is missing from the compose since we replaced the
hard dependancy on bcc-tools from bcc package by a soft one
(Recommends). Let's add it explicitly to the workload.
Resolves: rhbz#1991897

Add bcc-tools to the tracing workload

---

configs/sst_graphics_infrastructure-graphics-development-libraries.yaml

Libdecor is a new dependency of SDL2; add it to the same config as SDL2.
Signed-off-by: Jonas Ådahl <jadahl@redhat.com>

Add libdecor

---

configs/sst_cockpit-podman.yaml
configs/sst_cockpit-unwanted.yaml
configs/sst_cockpit-web-console.yaml
configs/sst_image_builder-composer.yaml
configs/sst_image_builder-weldr-client.yaml
configs/sst_installer-anaconda.yaml
configs/sst_installer-unwanted.yaml
configs/sst_installer-x3270.yaml

The previous sst_front_door got changed into an ssg_front_door group
with individual to sst_cockpit, sst_image_builder and sst_installer
teams.

Split sst_front_door into installer/image_builder/cockpit

---

.github/workflows/config-check.yml

Hi @asamalik!
Here's the GitHub Actions workflow for CI for testing the config files. 
The CI checks the config files using `test_config_files.py` from the code repository content-resolver. It then prints the output to a body of PR comment. Which means you should be able to see if the checks passed right away. Here's a demonstration: https://github.com/regexowl/content-resolver-input/pull/50
The `test_config_files.py` runs the `get_configs` function from the `feedback_pipeline.py` to check the configs, so all the code stays in one place.
Let me know what you think :)

Added a CI workflow

---

configs/sst_coreos.yaml

The 'labels' field is mandatory, so I just set it as empty so it does what it was supposed to, but without failing.

Fix the sst_coreos.yaml

---

configs/sst_cs_apps-images-compat.yaml

See more at https://bugzilla.redhat.com/show_bug.cgi?id=1990361

Remove a placeholder for compat-libtiff3 as this package is no longer needed

---

configs/sst_desktop_applications-unwanted-eln.yaml
configs/sst_desktop_applications-unwanted.yaml

There was only ever an autoconf213 for mozjs78, firefox
and thunderbird. The use of autoconf231 is a typo (transposed
1 and 3) in the unwanted packages lists. Fixing unwanted packages
is important because we do not want autoconf213 to continue to be
used as a compat package.

Fix typo in unwanted packages list for autoconf213

---

configs/sst_subscription_manager-subscription-manager.yaml

This PR adds the optional "unwanted_packages" entry to the sst_subscription_manager config in order to mark libXpresent as unwanted.

Mark libXpresent as unwanted by sst_subman

---

configs/sst_networking-tools-plotnetcfg.yaml

The Skydive service is a better alternative for exploring complex
OpenStack/Kubernetes network topology. The plotnetcfg tool is useful mostly
for the kernel developers. It's not actively maintained upstream at the
moment.

Mark plotnetcfg as unwanted

---

configs/sst_desktop-gnome-desktop-eln.yaml
configs/sst_desktop-gnome-desktop.yaml

Package will be used in RHEL 9 to display RH logo.

Add gnome-shell-extension-background-logo to ELN/RHEL9

---

configs/sst_cs_apps-java-log4j.yaml

log4j-jcl and log4j-slf4j subpackages of log4j should also be in AppStream in CS 9 and ELN.

Add more log4j subpackages to log4j workload

---

configs/automotive-environment.yaml
configs/automotive-workload-off.yaml

Moving this to the off-vehicle workload.  We don't expect interactive
root shell sessions to be happening in vehicle.

Remove rootfiles from the Automotive environment

---

configs/automotive-environment.yaml
configs/automotive-repositories-c9s.yaml

This replaces the standard kernel with kernel-automotive from CBS.  Also
dropping kernel-tools as the package doesn't provide anything required
in the automotive context.  Supossedly.
Also adding priorities to the repositories, so that we prioritize CentOS
Stream content, only using CBS, EPEL, the buildroot or COPR as
fallbacks.

Automitive: Use CBS & switch to kernel-automotive

---

configs/automotive-environment.yaml
configs/automotive-workload-off.yaml

The platform is expected to provide a hardware RNG.  We're still
including rng-tools in the off vehicle set as a fallback, especially for
image builds.

Automotive: Drop rng-tools from the environment

---

configs/automotive-environment.yaml
configs/automotive-workload-off.yaml

This adds a bunch of packages based on new requirements from an
automotive vendor.  This generally covers C++, compression and
multimedia.
Development subpackages were added for requested libraries to the
off-vehicle workload.
Some base libraries are required explicitly to denote their nature of
providing top-level APIs in the automotive context.

Update the automotive environment and workloads

---

configs/eln_extras_meta.yaml

This is an initial set of packages that we (myself and @michel-slm, with our Meta hats on) would like to track for ELN. We're happy to sign up for keeping these in good shape. I put the placeholder FAS group we have for this (which is currently just used for copr, it's not a real SIG nor it plans to be) as maintainer, as it seemed better than just listing individuals.
This is just an initial package set to test how the process works and we plan to augment it down the road.

Add initial ELN Extras workload for Meta

---

configs/eln_extras_hyperscale.yaml

This is an initial set of packages that the [CentOS Hyperscale SIG](https://sigs.centos.org/hyperscale/) depends upon and/or cares about and would like to see tracked in ELN. We're happy to sign up for keeping these in good shape, I put the SIG FAS group as the maintainer.

Add initial ELN Extras workload for the CentOS Hyperscale SIG

---

configs/automotive-environment.yaml
configs/automotive-workload-off.yaml

Remove packages not available in Stream or CBS, namely yasm and
hmaccalc.  Additionally, drop fake packages such as grub2 and
greenboot-*.  These don't really exist at this point.
grub2 functionality is provided by the arch-dependent packages, while
the greenboot package provides the commands previously listed as
explicit packages.
With this commit, everything is either in Stream or CBS.

Automotive package cleanup

---

configs/automotive-repositories-c9s.yaml

Switches the CS9 repositories to the production compose as the
development compose is unstable. Currently the annobin packages in the
development compose have bugs that block it from reaching the production
compose and is a case where we would be introducing a buggy state by
using the development compose as an input.
Also drops buildroot and epel as we don't want to introduce non c9s
content into the AutoSD distribution by default.
Also adds the autosd CBS packages and shift that plus the Automotive CBS
packages to a higher priority layer (would make sense that what they fork
take priority over C9S).

automotive-repositories: switch to production c9s composes

---

configs/automotive-repositories-c9s.yaml

The previous commit 2975421c missed to change the urls of the c9s repos
from development composes to production composes.

automotive-repositories: actually switch to production c9s repos

---

configs/sst_desktop-gtk2.yaml
configs/sst_desktop-unwanted-eln.yaml

gtk2:
GTK 2 served us for a long time, but it's time to say good bye to it.
Applications had plenty of time to move to newer toolkits that support
the current technologies (Wayland, HiDPI displays, ..).
gnome-common:
Applications had plenty of time to move away from intltool to gettext
and the packages that currently require it in ELN are on their way to
drop the gnome-common dependency.
RH Internal tracking issue: https://issues.redhat.com/browse/DESKTOP-481

Drop gtk2 and gnome-common from ELN/RHEL 10+

---

configs/eln_extras_meta.yaml

This is needed to be able to build drgn on ELN in PackIt (see https://github.com/osandov/drgn/issues/188).

Add libkdumpfile-devel to ELN Extras for Meta workload

---

configs/eln_extras_pablomh.yaml

This way we can configure OpenVPN from Gnome.

Add initially only NetworkManager-openvpn-gnome to ELN extras

---

configs/acg-level1-el7.yaml

ELN is tracking RHEL 10, which is not affected by RHEL 7's ACG level-1 list.

Drop eln from RHEL 7 ACG1 list

---

configs/sst_cs_apps-python-data-formats-c9s.yaml
configs/sst_cs_apps-python-data-formats-eln.yaml

See d70542ac44b9beb5502347550ee7395c7a674afd
Do I need to create a copy of this file for c9s only that has python3-toml because python3-toml is still wanted there, or do I need to remove to c9s label, or do I not care about c9s here, because packages are never removed from there?

python3-toml is unwnated but was also required

---

configs/sst_program-lorax-template-eln.yaml

There are a few packages marked as unwanted that are in the lorax-template workgroup.
Double check that these packages are no longer in the actual lorax-template before merging this pull request.
Signed-off-by: Troy Dawson <tdawson@redhat.com>

Unwanted packages in lorax-template

---

configs/sst_i18n-extra-fonts-eln.yaml
configs/sst_i18n-fonts-eln.yaml

1) smc fonts renamed to rit fonts
2) write redhat-fonts binary packages explicitly instead of its source package name

Few font package name updates

---

configs/automotive-environment.yaml

include libgpiod and libi2c in automotive
Signed-off-by: Brian Masney <bmasney@redhat.com>

include libgpiod and libi2c in automotive

---

configs/eln_extras_rhel_packager.yaml

During the early days of CentOS Stream bootstrapping, it is useful for RHEL maintainers to be able to dogfood it (use the distro to develop the distro).  Let's add a specific workload for this to ensure the necessary packages stay compatible.
I spoke with @pablomh about this already over email, and he agreed to allow us to repurpose his single-package workload since it already contained one of the packages we need to include.
cc: @bstinsonmhk

Create RHEL packager workload (converted from pablomh workload)

---

configs/eln_extras_meta.yaml

- Drop dcrpm for the time being
- Add binary packages for duo_unix
- Add binary packages for btrfs-progs

Update ELN Extras workload for Meta

---

configs/sst_kernel_maintainers-kernel-base-eln.yaml

It's needed for Intel Wi-Fi 6 AX2xx cards functionality.

Add `iwlax2xx-firmware` package

---

configs/sst_desktop-gnome-screenshot.yaml
configs/sst_desktop-unwanted-eln.yaml

The functionality was moved to GNOME Shell. See:
https://pagure.io/fedora-workstation/issue/277
https://issues.redhat.com/browse/DESKTOP-673

Drop GNOME Screenshot from ELN/RHEL 10

---

configs/eln_extras_hyperscale.yaml

These are unshipped subpackages, but they _are_ build, so it should be possible to add them to ELN Extras this way.

Add systemd-networkd and iptables-legacy to ELN Extras workload for Hyperscale

---

configs/sst_kernel_maintainers-kernel-base.yaml

This request complements the followin MRs:
https://gitlab.com/redhat/centos-stream/src/kernel/centos-stream-9/-/merge_requests/1736  
https://gitlab.com/cki-project/kernel-ark/-/merge_requests/2175  
'kernel-core' package is split into 'kernel-core' and 'kernel-core-modules' and 'kernel-uki-virt' sub-package is introduced.
Signed-off-by: Vitaly Kuznetsov <vkuznets@redhat.com>

st_kernel_maintainers-kernel-base: add kernel-uki-virt and kernel-modules-core

---

configs/sst_desktop-unwanted-eln.yaml

Obsoleted by geocode-glib2(-devel) that is using libsoup3, instead of
the already unwanted libsoup2.

Mark geocode-glib(-devel) as unwanted

---

configs/sst_edge.yaml

Update the el9 package set for RHEL for Edge.
Signed-off-by: Peter Robinson <pbrobinson@redhat.com>

sst_edge: Update SST Edge package set for el9

---

configs/sst_cs_infra_services-varnish-eln.yaml

Removing module dependency so this workload can be properly resolved.

There will be no modules in the initial RHEL 10.0

---

configs/sst_cs_infra_services-printing-stack-c10s.yaml

lprint provides support for common label printers, which don't support any driverless standards.
ipp-usb enables driverless printing for USB printers, which have support for IPP-over-USB protocol.

Add lprint and ipp-usb to ELN and C10S

---

configs/sst_cockpit-web-console.yaml

We introduce this into ELN (RHEL 10) now, and soon into RHEL 9.
---
Is that kosher like that, or will that break RHEL 9 builds? We haven't done any bureaucracy around RHEL 9 inclusion yet, nor is the current package version ready for it. Do we need to split this into a new file with only a "eln" tag?

sst_cockpit-web-console: Add cockpit-ostree

---

configs/sst_kernel_maintainers-kernel-base.yaml
configs/sst_kernel_maintainers-kernel-develdebug.yaml
configs/sst_kernel_maintainers-kernel-unwanted.yaml

We had more changes than usual this time between RHEL 9.1 and 9.2, update the package lists reflecting those changes.

Update sst_kernel_maintainers package lists for kernel (9.1->9.2)

---

configs/sst_cs_apps-python-data-formats-c9s.yaml

See https://bugzilla.redhat.com/2175213
This is explicitly needed for EL < 10 only, EL 10+ has tomllib in the Python 3.11+ standard library.

Add python3-tomli to c9s

---

configs/automotive-environment.yaml

Hi, 
Opening this PR for the ostree-compliance-mode package. I've added to the automotive-environment.yaml file, but please let me know if it's better suited to automotive-workload-off.
Thank you,
Ian Mullins

Automotive-environment: Add the ostree-compliance-mode package

---

configs/sst_i18n-input-methods-gtk2.yaml
configs/sst_i18n-input-methods.yaml

Split out gtk2 input methods

---

configs/sst_cs_infra_services-unwanted-c10s.yaml

gtk2 is not in C10S, remove the dependent gutenprint subpackage.

Remove gutenprint-libs-ui from C10S

---

configs/automotive-workload-off.yaml

Developer images need the man-pages and other tools to help developers have better understanding of supported APIs.

Add in man-pages to the extras

---

configs/automotive-environment.yaml
configs/automotive-repositories-c9s.yaml

The AutoSD project is using the content-resolver output to define the product definition (contents) of the AutoSD repositories (aka product-build). This commit strips the automotive-sig repositories and packages from the content-resolver workload/repositories because they're not considered part of the AutoSD product and are dirtying the product definition (and muddying the line between automotive-sig and AutoSD).
This is needed to create a cleaner divide between the AutoSD project and the automotive-sig project. Later if these packages are needed in AutoSD, they need to be properly promoted to the autosd tag in order to add them here.

Remove automotive-sig from automotive-repositories

---

configs/sst_platform_tools-debuggers-unwanted.yaml

commit d90e73f943b04d62221e6af5c0bf2a541f86f4c8 added gdb-minimal for the primary architectures but leaving it unwanted on i686.  However, the general unwanted declaration was not removed, seemingly mistakenly.

gdb-minimal is unwanted only on i686

---

configs/automotive-environment.yaml

The removal of linux-firmware-automotive leaves a gap that needs to be filled. Put linux-firmware in its place.

automotive-environment: add linux-firmware

---

configs/rhel-8-appstream-comps-performance.yaml
configs/sst_platform_tools-pcp-grafana.yaml
configs/sst_program-lorax-template-eln.yaml
configs/sst_program-lorax-template.yaml

sst_filesystems-userspace declares these packages unsupported on aarch64 for both C9S and ELN.

Do not list any gfs2 packages for aarch64

---

configs/sst_desktop_applications-qt5.yaml
configs/sst_desktop_applications-qt6.yaml
configs/sst_desktop_applications-unwanted-eln.yaml

We are only supporting one Qt version per major release of RHEL and as Qt 5 is on the end of its development cycle, we are removing it from RHEL 10 and bringing Qt 6 there which is the current stable Qt release in development that will see more of the Wayland specific features developed there. See https://issues.redhat.com/browse/DESKTOP-734 for internal ticket.

Drop Qt 5 from ELN and introduce Qt 6 there

---

configs/sst_high_availability-userspace.yaml

These packages are built with bundled dependencies in RHEL, and using the Rawhide versions in ELN is pulling in a lot of unwanted Python and Ruby packages.
- Placeholder pcs
- Placeholder more fence-agents

Placeholder more HA packages

---

configs/sst_desktop-accessibility-eln.yaml
configs/sst_desktop-unwanted-eln.yaml

Together with people from the Red Hat's Linux accessibility group, we've agreed on only shipping the espeak-ng speech synthetizer (owned by sst_cs_infra_services) in RHEL 10 and drop flite and festival - both are no longer maintained upstream for some time and they do have their set of problems. espeak-ng is actively maintained upstream and has a brighter future in RHEL 10. The only downside of this plan is that espeak-ng sounds "robotic" in opposed to festival that is using the natural voice. If there will be demands in the future for the natural voice synthetizer, then we might look into how RHVoice is doing (currently not even in Fedora). See https://issues.redhat.com/browse/DESKTOP-660 for the internal discussion.
Drop at-spi2-atk as it has been merged into at-spi2-core.
Explicitly …

Update the accessibility workload

---

configs/sst_java-java.yaml

* Move `java-17-openjdk` to packages now it exists in both Fedora & RHEL
We've started the PRP process to add `java-21-openjdk` to RHEL 8 & 9 for the next release in November. OpenJDK 21 is expected to be the next long term support release of OpenJDK and is due for release in September.
This also updates `java-17-openjdk` to be listed with `java-1.8.0-openjdk` and `java-11-openjdk`. When this file was originally added, it was only a placeholder in RHEL 9, but it is now a regular package in Fedora and RHEL 8 & 9.

Add OpenJDK 21 - https://issues.redhat.com/browse/RHELPLAN-156269

---

configs/sst_desktop-gnome-text-editor.yaml

Follow what we've done in Fedora Workstation as well, see https://issues.redhat.com/browse/DESKTOP-737 and
https://pagure.io/fedora-workstation/issue/248

Replace Gedit with GNOME Text Editor

---

configs/sst_platform_tools-rust-toolset.yaml

The new `rust-analyzer` has replaced `rls` and its supporting files in `rust-analysis`.

Rust: replace rls with rust-analyzer

---

configs/sst_desktop_applications-unwanted-eln.yaml

Triggered by noticing that we've previously marked python-qt5 as unwanted, but this is an SPRM and not the RPM (which is a python3-qt5).

Rely on unwanted_source_packages when specifying unwanted Qt 5 packages

---

configs/sst_kernel_security-kpatch.yaml

A new Kernel Security SST was formed out of the Kernel FT SST.  Update the kpatch content accordingly.

Move kpatch from sst_kernel_ft to sst_kernel_security

---

configs/sst_cs_apps-unwanted-python3.yaml

python-tornado was re-added to RHEL 9 post-GA for the Keylime workload.

Fix python-tornado status

---

configs/eln_extras_qt6.yaml
configs/sst_desktop_applications-qt6.yaml

Add new Qt6 components in 6.5.1, and limit the Qt6 ELN Extras workload to packages not in ELN proper.
/cc @tdawson @tpopela

Update Qt6 workloads in ELN

---

configs/sst_networking-management-server.yaml

Rawhide now contains the changes needed to use vendored dependencies in ELN builds of nispor, so there is no further reason to placehold it.

Unplacehold nispor

---

configs/sst_i18n-fonts-eln.yaml

ht-caladea-fonts was retired in F38+.

Update caladea-fonts package name for ELN

---

configs/sst_cs_apps-embedded.yaml
configs/sst_cs_apps-unwanted.yaml

SInce libdb is deprecated and probably will be unwanted, so we should highlight it.
@hhorak PTAL

Remove libdb from supported packages

---

configs/sst_cs_apps-python-crb.yaml

Depends-on: https://src.fedoraproject.org/rpms/python-pyproject-hooks/pull-request/2
cc @torsava

Add python3-installer and python3-pyproject-hooks to Python CRB workload

---

configs/sst_platform_tools-misc.yaml
configs/sst_platform_tools-tbb-exclusion.yaml
configs/sst_platform_tools-tbb.yaml

tbb is currently listed as both required and unwanted in ELN as a result of #822.  This avoids that by splitting tbb out into its own c9s-only workload.
Note that dyninst still requires tbb, so further work is required to actually drop tbb from ELN.
/cc @nickclifton

Split tbb listings for c9s and eln

---

configs/eln_extras_meta.yaml

Gate arch packages to the arches where they actually exist

Fix warnings in ELN Extras workload for Meta

---

configs/sst_storage_io-packages-unwanted.yaml

Intel is dropping support for these libraries.  It's not clear whether other maintainers will step up to develop/maintain them.

Remove pmem libraries

---

configs/unwanted-eln-packages.yaml

IPv6 support is in standard libraries (perl-Socket, perl-IO-Socket-IP) and we are in process of removing this depdencies.

Add deprecated Perl modules for IPv6

---

configs/sst_cs_infra_services-development-packages.yaml
configs/sst_cs_infra_services-printing-stack-c10s.yaml
configs/sst_cs_infra_services-unwanted-c10s.yaml

ghostscript-x11 no longer in c10s
qpdf and qpdf-devel are in CRB in c9s+ now
add new packages from cups-filters 2.0 generation

Changes regarding c10s/c9s printing stack

---

configs/sst_desktop-unwanted-eln.yaml
configs/sst_desktop_applications-evolution-eln.yaml
configs/sst_desktop_applications-gnome-photos.yaml
configs/sst_desktop_applications-inkscape.yaml
configs/sst_desktop_applications-unwanted-eln.yaml

Drop evolution-mapi, gnome-photos, inkscape, libgdata and mark enchant, dbus-glib as unwanted.

More RHEL 10 desktop removals

---

configs/sst_kernel_rts-kernel-rt-base.yaml
configs/sst_kernel_rts-kernel-rt-develdebug.yaml

kernel-rt-core has been split into kernel-rt-core and kernel-rt-modules-core.
Reflect the change in the kernel-rt workloads.

sst_kernel_rts-kernel-rt: add kernel-rt-{,debug-}modules-core

---

configs/sst_filesystems-userspace-c9s.yaml

This is based on libpmem becoming dropped from ELN in #850. pmemblk was already dropped in fio 3.34, and https://src.fedoraproject.org/rpms/fio/pull-request/7 will disable the rest from building in ELN.
/cc @JeffMoyer @rhawalsh

Remove pmem-dependent fio-engine subpackages from ELN

---

configs/sst_platform_tools-go-toolset.yaml

go-srpm-macros is now a sub package of go-rpm-macros, and packages in the wider distribution depend on both

Update sst_platform_tools-go-toolset.yaml (add go-rpm-macros)

---

configs/sst_desktop_firmware_bootloaders-fwupd-eln.yaml

This should fix the warning in this workload.
/cc @tpopela

fwupd-efi is only for UEFI architectures

---

configs/sst_edge.yaml

At one point these were planned for c9s but were never added.

Remove can-utils, libiio

---

configs/ssg_platform_tools-unwanted.yaml

This patch adds a comment to the ssg_platform_tools-unwanted file explaining why the nasm and yasm tools are needed, and why we would like to drop them.

Explain why nasm and yasm are unwanted

---

configs/sst_cs_apps-apps-unsorted-c9s.yaml
configs/sst_cs_apps-apps-unsorted-eln.yaml
configs/sst_cs_apps-unwanted-eln.yaml

Pcre project has been deprecated and unsupported by upstream since Fedora 38 Fedora Change: https://fedoraproject.org/wiki/Changes/PcreDeprecation

Add pcre and pcre-devel as unwanted

---

configs/sst_kernel_debug-misc-eln.yaml
configs/sst_kernel_debug-unwanted-eln.yaml

The upstream of python-dmidecode is inactive, and there are almost no users. To reduce the development burden, we decided to drop it.

python-dmidecode is unwanted

---

configs/sst_program-unwanted.yaml

It's not properly dep-pruned for EL so let's be sure we notice if it shows up again.

bind9-next is unwanted

---

configs/sst_security_crypto-openssl-c9s.yaml

We do not plan on supporting OpenSSL 1.1 in 10, so drop it from the package set. There should be no users of this in the distribution since we did not ship the development package.

Remove compat-openssl11

---

configs/sst_security_crypto-unwanted-eln.yaml

openssl-pkcs11 provides an OpenSSL ENGINE implementation for PKCS#11, but OpenSSL 3.0 has deprecated ENGINEs in favour of using providers. Since we are working on bringing an OpenSSL PKCS#11 Provider into Fedora [\[1\]][1] and want to use that in ELN, mark openssl-pkcs11 as unwanted.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=2211754

Mark openssl-pkcs11 as unwanted in ELN

---

configs/sst_cs_plumbers-cli-tools-c9s.yaml
configs/sst_desktop_applications-unwanted-eln.yaml
configs/sst_kernel_maintainers-kernel-base-eln.yaml
configs/sst_kernel_maintainers-kernel-base.yaml
configs/sst_kernel_maintainers-kernel-develdebug.yaml
configs/sst_pt_pcp-pcp-grafana.yaml
configs/sst_virtualization-all-eln.yaml

- Fix state of autoconf-archive in ELN
- kernel-uki-virt is x86_64 specific
- ninfod was dropped from iputils
- No pcp-pmda-bpf on s390x
- Placehold libguestfs-winsupport
- Drop sgabios from ELN

Another round of ELN warning fixes

---

configs/sst_cs_apps-containers.yaml

This list does not include packages installed in some particular images, like the list in https://github.com/sclorg/s2i-python-container/blob/master/3.11/Dockerfile.fedora#L41-L42
I'm not clear whether we need a full list for the purpose of content resolver or whether we can be fine with this initial packages set.
@pkubatrh @phracek WDYT?

Add an initial content for most common components used in container images

---

configs/sst_cs_system_management-text-processing.yaml

hypdoc.sty, pdfcol.sty, hopatch.sty are moved from oberdiek package into separates
packages hypdoc, pdfcol, hopatch since texlive 2023

add missing texlive-hopatch, texlive-hypdoc, texlive-pdfcol

---

configs/sst_desktop-gtk3.yaml
configs/sst_desktop-gtk4.yaml

Be explicit about packages that we are already shipping in RHEL 9 in AppStream (and will continue to do so in RHEL 10).

Extend the GTK workloads

---

configs/sst_desktop-gnome-desktop-eln.yaml
configs/sst_desktop-gnome-desktop.yaml

Explicitly list some packages that we are shipping in AppStream/BaseOS and also list libproxy that is needed and we're actually moving it to our subsystem for RHEL 10.

Extend the GNOME Desktop workload

---

configs/sst_kernel_tps-tracing.yaml

bpftrace was originally listed in each architecture b/c it was not present on the armv7hl. AFAIK, this arch is not supported in ELN/CentOS Stream anymore, so move bpftrace to the common list of packages.

System tracing: move bpftrace to common packages

---

configs/sst_cs_plumbers-cli-tools-c9s.yaml

The `eln` tag was left accidently in the split-out c9s config from #888.

Fix cli-tools split

---

configs/sst_networking-xdp.yaml

Update sst_kernel_tps-xdp.yaml to move the workload to the networking sst where it belongs (since I maintain all the mentioned packages anyway).

Move XDP workload to networking SST

---

configs/sst_security_compliance-installation.yaml
configs/sst_security_compliance-unwanted-eln.yaml
configs/sst_security_compliance-workbench.yaml

There are two expected changes within the RHEL10 timeframe
* change of the way how we harden installation
* removal of the old SCAP Workbench GUI tool

Update of the Security Compliance workflows for 10

---

configs/ssg_idm-hesiod.yaml

Hesiod has been deprecated since RHEL 7 and was on ACG Level 1 compatibility. It can finally be removed in RHEL10.

Remove Hesiod workload

---

configs/sst_storage_io-packages-unwanted-c9s.yaml
configs/sst_storage_io-packages-unwanted-eln.yaml

This package is going to be delivered via EPEL instead of RHEL in the future.
Since this package has a component in c9s, the 'unwanted' files are getting split by the eln and c9s labels so that we can distinguish between the releases.
This was formerly PR https://github.com/minimization/content-resolver-input/pull/905  I have rebased and created this new PR.

Marking nvme-stas as unwanted.

---

configs/sst_i18n-hunspell-dictionaries-eln.yaml

The sst_i18n team would like to continue supporting hunspell packages for spellchecking purposes in ELN and upcoming RHEL releases.

Add hunspell package and some missing hunspell dictionary packages

---

configs/sst_i18n-hyphenation-rules-eln.yaml

There are some packages (qt5-qtwebkit, webkit2gtk4.1, webkitgtk6.0) in ELN which needs hyphen package and sst_i18n team also want to provide hyphenation rules for different languages.

Add new workload for hyphenation packages

---

configs/sst_java-jmc-eln.yaml

- Removing the eclipse-pde and tycho packages since they're no longer needed and have been removed
- Correcting the SST name to sst_java
- Removing the JMC 7 module

sst_java: Updating the JMC ELN workload to reflect changes in packaging

---

configs/sst_container_tools.yaml
configs/sst_container_tools_eln.yaml
configs/sst_program-lorax-template-eln.yaml
configs/sst_pt_llvm_rust_go-go-toolset.yaml
configs/sst_virtualization_windows-subsystem.yaml

- Drop oscap-anaconda-addon from ELN lorax template
- Fix warnings in Windows Virt
- Fix warnings in container-tools
- Update go-toolset

ELN warning fixes, round 4

---

configs/rhel-8-appstream-comps-performance.yaml
configs/sst_i18n-langpacks-eln.yaml
configs/sst_i18n-tools.yaml

These are not used or needed anymore.

drop redundant eln-candidate labels

---

configs/sst_cs_system_management-sys-management-c9s.yaml
configs/sst_cs_system_management-sys-management.yaml

Remove opal-firmware subpackage for ELN as qemu doesn't require it any more, but keep it for c9s.

remove opal-firmware for ELN

---

configs/sst_gpu-X11-server-c9s.yaml

Upstream development of this driver has ceased, and the package was orphaned by the maintainer in Fedora:
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/AAKVIAL7ZOAZOTCSYZUWJN4XAZCQBFU6/

Drop xorg-x11-drv-v4l from ELN X11 server

---

configs/sst_cs_apps-db-mysql.yaml

This package is named community-mysql in Fedora and mysql in RHEL, with each providing the other name, but automatic renaming is not currently in place.  Avoid importing community-mysql with a placeholder.

Placehold mysql

---

configs/sst_networking-management-core.yaml
configs/sst_networking-management-desktop.yaml
configs/sst_networking-management-devel.yaml
configs/sst_networking-management-server-c9s.yaml
configs/sst_networking-management-server.yaml

Networking SST is split into several SSTs - This PR is to update the content resolver for the Network Management SST.

Rename workloads maintainer for sst_network_management

---

configs/sst_cs_apps-db-mysql.yaml
configs/sst_cs_infra_services-time-synchronization.yaml
configs/sst_cs_plumbers-base.yaml
configs/sst_desktop_applications-tigervnc.yaml
configs/sst_kernel_rts-kernel-rt-base-eln.yaml
configs/sst_kernel_rts-kernel-rt-develdebug-eln.yaml
configs/sst_logical_storage-packages.yaml
configs/sst_pt_llvm_rust_go-llvm-toolset-c9s.yaml

This should cover all ELN placeholders which are now already pulled in as real packages.  As well, update kernel-rt and libomp for downstream packaging changes.
- Drop LLVM libomp-test from ELN
- Unplacehold zram-generator
- Update storage placeholders
- Fix mysql-selinux
- Update kernel-rt placeholders
- Unplacehold tigervnc-selinux

Update some ELN placeholders

---

configs/eln_extras_meta.yaml

This package has an ExcludeArch on s390x so we need to gate it out to unbreak the workload.

Gate awscli2 out of s390x for the Meta ELN Extras config

---

configs/ssg_idm-smart-cards-unwanted.yaml

The ESC is a tool for RHCS smart cards enrollment and it should be moved to the RHCS layered product. It has very limited use in base RHEL.

Remove ESC package from base RHEL

---

configs/automotive-workload-infotainment.yaml

Added qemu-kvm-ui-dbus and packages needed to make it work even if not required by the rpm itself.

infotainment: add qemu-kvm-ui-dbus and deps

---

configs/sst_pt_libraries-vfxplatform-eln.yaml

These subpackages do not exist for qt6.

Fix ELN vfxplatform

---

configs/sst_cs_apps-unwanted-java-c9s.yaml
configs/sst_cs_apps-unwanted-java.yaml

* aopalliance is now dependency of google-guice, required by Maven workload. It will be in AppStream.
* jsoup will be in buildroot/CRB as it's a transitive build depedency of Maven.

Mark aopalliance and jsoup as wanted in ELN

---

configs/sst_cs_apps-unwanted-java.yaml

In ELN plexus-build-api >= 1.0.0 is unwanted.
Instead in ELN we want compat package plexus-build-api0 version 0.0.7.

Mark plexus-build-api as unwanted in ELN

---

configs/sst_desktop-unwanted-eln.yaml

The libsoup2-based geocode-glib-1.0 API is no longer used, and therefore has been dropped from Fedora 39 entirely; the libsoup3-based geocode-glib-2.0 API previously packaged as geocode-glib2 is now packaged as geocode-glib:
https://src.fedoraproject.org/rpms/geocode-glib/c/bb0eab3abdb68f1646967220071254cea17a3f6c
https://src.fedoraproject.org/rpms/geocode-glib/c/f6cc26c1d5af7570377feae4f4fa5e6ef3876e56
https://src.fedoraproject.org/rpms/geocode-glib/c/971bb3b5f2b446dae8e96d6291d8d44555fba551
/cc @tpopela

geocode-glib is wanted in ELN again

---

configs/sst_cs_apps-java-ant-c9s.yaml

This fixes a new warning triggered by this change in ant 1.10.13:
https://src.fedoraproject.org/rpms/ant/c/017a0402ce77df95c1d481ef33fa01e17b6cc55f
/cc @mizdebsk

ant-jakartamail replaces ant-javamail in ELN

---

configs/sst_cs_infra_services-time-synchronization.yaml

scons is being bundled in the gpsd-minimal SRPM in c9s.

Drop scons build dependency from gpsd-minimal

---

configs/sst_desktop_applications-qt6.yaml
configs/sst_desktop_applications-unwanted-eln.yaml

This is following Fedora 39 change, where QGnomePlatform and Adwaita-qt are removed in favor of Qt's default integration and partially replaced with a new client-side window decoration plugin.
Link: [Fedora 39 feature](https://fedoraproject.org/wiki/Changes/NoCustomQtThemingForWorkstation)
RedHat tracker: [DESKTOP-735](https://issues.redhat.com/browse/DESKTOP-735)

Remove QGnomePlatform with Adwaita-qt and include QAdwaitaDecorations

---

configs/sst_cs_system_management-sys-monitoring-c9s.yaml

Replace iotop with iotop-c forn ELN. Currently, iotop has often screen issues, close to zero upstream development, latest release is 10yrs old and is bigger (python). iotop-c is compatible drop-in replacement with active upstream, smaller, less issues.

replace iotop with iotop-c in ELN

---

configs/sst_security_crypto-pqc.yaml

Since there is industry demand for post-quantum cryptography, add the recently packaged liboqs and oqs-provider packages as requested for eln.

Add post-quantum crypto: liboqs, oqs-provider

---

configs/sst_security_crypto-pqc.yaml

The OpenSSL OQS Provider is packaged in oqsprovider, not oqs-provider.

post-quantum crypto: Fix package name typo

---

configs/sst_cs_apps-unwanted-java.yaml

munge-maven-plugin has been retired from Fedora rawhide and should be absent in ELN as well.

Mark munge-maven-plugin as unwanted in ELN

---

configs/sst_desktop-loupe.yaml
configs/sst_desktop_applications-unwanted-eln.yaml

See https://pagure.io/fedora-workstation/issue/348 and RH internal https://issues.redhat.com/browse/DESKTOP-738.

Replace Eye of GNOME with Loupe as the default image viewer

---

configs/sst_kernel_debug-kdump.yaml

Add drgn to kdump as a new tool for vmcore analysis, also add libkdumpfile, which is needed by drgn.

kdump: add libkdumpfile and drgn

---

configs/eln_extras_meta.yaml

Looks like this has been dropped but we need it for `git-send-email`.

Add git-email to the ELN Extras workload for Meta

---

configs/sst_networking_core-hostapd.yaml

sst networking core owns wpa_supplicant. So lets mention it here so that it gets properly assigned to us.

sst_networking_core: add wpa_supplicant

---

configs/eln_extras_music.yaml

Currently, this includes only the `gi-docgen` package.

Add ELN Extras workload for FAS account music

---

configs/sst_desktop-snapshot.yaml

Fedora Workstation will make a switch in F40, see
https://pagure.io/fedora-workstation/issue/166 and RH internal https://issues.redhat.com/browse/DESKTOP-739

Replace Cheese with Snapshot as the default webcam application in RHEL

---

configs/sst_desktop-gnome-desktop-eln.yaml
configs/sst_desktop-unwanted-eln.yaml

It's already pulled there, but make it official, see Red Hat internal https://issues.redhat.com/browse/DESKTOP-501 for more information.

Add tecla to ELN

---

configs/sst_program-unwanted.yaml

libb2 is unwanted in ELN, blake2 hashes are available in libgcrypt and openssl

---

configs/sst_coreos.yaml

Apparently this has been an issue in c9s for a while, but it came to ELN via #987.
/cc @cgwalters

sst_coreos: fix typo

---

configs/sst_desktop_applications-nautilus-eln.yaml

This will result in Windows shares to be available in GNOME. Please see https://gitlab.gnome.org/GNOME/gvfs/-/merge_requests/186 and internal to Red Hat https://issues.redhat.com/browse/DESKTOP-564 for more information.

Explicitly require wsdd for Web Service Discovery in GNOME

---

configs/sst_cs_infra_services-time-synchronization-c10s.yaml

Add copy of time sync packages for c10s, replacing gpsd-minimal with gpsd.

Add time sync packages for c10s

---

configs/sst_desktop-glade.yaml
configs/sst_desktop-unwanted-eln.yaml

Obsolete upstream for nearly 10 years and UI files are supposed to be written by hand. Relevant blog
https://blogs.gnome.org/christopherdavis/2020/11/19/glade-not-recommended/
This is currently required by GTK based Anaconda. For more information please see RH internal https://issues.redhat.com/browse/DESKTOP-752

Remove Glade workload and mark it as unwanted

---

configs/sst_cs_apps-python-crb.yaml

This package was included in RHEL 9 CRB via https://bugzilla.redhat.com/2051483
We want to keep it in CRB.

Add marshalparser to Python devel (CRB)

---

configs/sst_desktop_applications-unwanted-eln.yaml

Removing the workload for ELN wasn't enough as some packages (such as djvulibre of python-matplotlib) are pulling it through build requires.

Mark Inkscape as unwanted

---

configs/eln_extras_meta.yaml

- drop awscli2 now that it's included in ELN proper (https://github.com/minimization/content-resolver-input/commit/283d96b7a7bad87821dcc1f47054485775cfbb2)
- exa is gone, replace it with eza

Fix the ELN Extras workload for Meta

---

configs/sst_bootc-eln.yaml

The subsystem is new and the package is
just built in fedora, xref https://bugzilla.redhat.com/show_bug.cgi?id=2243345
Signed-off-by: Colin Walters <walters@verbum.org>
---

bootc: New sst

---

configs/sst_i18n-extra-fonts-eln.yaml
configs/sst_i18n-fonts-eln.yaml

The main change in this is to add langpacks font-related meta packages such as default-fonts* and sort out a bit between -fonts and -extra-fonts.

Update fonts workload against f39

---

configs/sst_desktop_applications-firefox.yaml
configs/sst_desktop_applications-thunderbird.yaml

We're using different packaging in RHEL (and in RHEL 10 those will be shipped as Flatpaks only) than in Fedora so the dependencies are not the same and the ELN is being "polluted" by packages that won't be needed in RHEL at all. On the other hand we're still interested in knowing how Thundebird and Firefox comply with all the ELN specific changes (extra hardening flags, ..) so ELN Extras is better place for these.

Move Thunderbird and Firefox from ELN to ELN Extras

---

configs/sst_bootc-eln.yaml

ostree and podman are going to centralize on this as a key underlying technology.

bootc: Add composefs to c10s/eln

---

configs/sst_desktop_applications-evolution-data-server.yaml

Temporarily disable EWS as it pulls in the whole Evolution (and thus WebKitGTK that will be removed from RHEL 10). We will look whether EWS could be reworked so it doesn't require it and then we will reenable this or if we fail, then we will remove it altogether

Temporarily remove evolution-ews from ELN

---

configs/sst_desktop_applications-devhelp.yaml

Devhelp is based on WebKitGTK that won't be in RHEL 10 and the documentation for various librariescan be found online if needed, e.g. in https://developer.gnome.org/documentation/introduction/overview/libraries.html
See internal to Red Hat https://issues.redhat.com/browse/DESKTOP-800 for more information.

Remove Devhelp from RHEL 10

---

configs/sst_gpu-GPU-drivers.yaml

The vulkan-utility-libraries package is required to build the Vulkan SDK (v1.3.268.0).
For more information please check:
https://github.com/KhronosGroup/Vulkan-Utility-Libraries#readme
JIRA issue: https://issues.redhat.com/browse/RHEL-15445
Fedora: https://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=2247640

Add vulkan-utility-libraries

---

configs/sst_gpu-X11-enviroment-c9s.yaml
configs/sst_gpu-X11-enviroment-eln.yaml
configs/sst_gpu-unwanted-c9s.yaml
configs/sst_gpu-unwanted-eln.yaml

Motif has been deprecated in RHEL 9 (see [1] and [2]) and technically even already in the RHEL 8 lifecycle (see [3]), and we're now removing this in RHEL 10.
See also Red Hat internal tracking ticket
https://issues.redhat.com/browse/GPU-621
[1]: https://access.redhat.com/solutions/6113101
[2]: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/9.0_release_notes/deprecated_functionality#JIRA-RHELPLAN-98983
[3]: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/8.5_release_notes/deprecated_functionality#JIRA-RHELPLAN-98983

Mark motif as an unwanted package

---

configs/repository-fedora-eln.yaml

java-openjdk-portable packages are built differently internally and therefore not intended to be imported into the next RHEL version.  With Fedora's build now using pandoc, which is unwanted in RHEL due to its GHC dependencies, to build documentation, we need to ignore it entirely.
/cc @asamalik

Ignore java-*-openjdk-portable in ELN

---

configs/sst_gpu-GPU-drivers.yaml

The vulkan-utility-libraries package only contains headers and a static library, therefore, only its -devel version is generated.
Replace vulkan-utility-libraries with its -devel variant.
JIRA issue: https://issues.redhat.com/browse/RHEL-15445
Fedora: https://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=2247640
Fixes: 5754e8966613 ("Add vulkan-utility-libraries")

Add vulkan-utility-libraries-devel

---

configs/repository-fedora-eln.yaml

Ignoring it from the Rawhide repo was insufficient.
This is a follow-up to #1030.
/cc @asamalik @sgallagher

Ignore java-*-openjdk-portable in ELN buildroot too

---

configs/sst_cs_plumbers-cli-tools.yaml
configs/sst_cs_plumbers-hw-tools-c9s.yaml
configs/sst_cs_plumbers-unwanted-c9s.yaml
configs/sst_cs_plumbers-unwanted.yaml

The plan is to provide these packages in EPEL 10 instead.
\cc @lnykryn

Remove `numad` and `pinfo` from ELN

---

configs/sst_arch_hw.yaml

Some of the tools from the s390utils source package are now built for all platforms, thus move the s390utils entry from the s390x section to the general one.
Related: https://issues.redhat.com/browse/RHEL-10567

s390utils is available for all arches

---

configs/sst_desktop_applications-tigervnc.yaml

As announced in [0] the Xorg server will be removed from RHEL 10 which we will take as the opportunity to remove TigerVNC from RHEL 10 as well and suggest to use RDP protocol through GNOME Remote Desktop instead (that relies on FreeRDP[2] project). As of now Xorg server source files are not planned to be shipped in RHEL 10 so technically we won't be able to build TigerVNC in RHEL 10 anyway.
With TigerVNC removal the server and client will be removed, but the ability to connect to other VNC servers (running for example on older RHEL versions) will remain through GNOME Connections[3] which is already shipped in RHEL 9.
[0] - https://www.redhat.com/en/blog/rhel-10-plans-wayland-and-xorg-server
[1] - https://gitlab.gnome.org/GNOME/gnome-remote-desktop
[2] - https://github.com/FreeRDP/FreeRDP/ …

Remove TigerVNC from RHEL 10

---

configs/sst_desktop-gnome-desktop-eln.yaml

libsoup is explictly unwanted in ELN, having been replaced by libsoup3.
/cc @tpopela

sst_desktop: libsoup3 is wanted in ELN, not libsoup

---

configs/sst_desktop-yelp.yaml

We're removing WebKitGTK[[0] from RHEL 10 and one of the applications that are using it is Yelp which is the default help viewer in GNOME[1]. We do have some plans[2] on how to rework the whole thing so the existing help is diplayed in the default browser. But until we agree on something (and implement it) we shouldn't block the WebKitGTK removal and rather temporarily remove it. It used to be required by Anaconda as well, but the dependency was dropped with [3] which is part of the ELN [4].
[0] - https://issues.redhat.com/browse/DESKTOP-670
[1] - https://issues.redhat.com/browse/DESKTOP-679
[2] - https://gitlab.gnome.org/GNOME/yelp-tools/-/merge_requests/12
[3] - https://github.com/rhinstaller/anaconda/pull/5335
[4] - https://koji.fedoraproject.org/koji/buildinfo?buildID=2325587

Drop (temporarily) Yelp from ELN/RHEL 10

---

configs/sst_gpu-multimedia-libraries.yaml

See https://bugzilla.redhat.com/show_bug.cgi?id=2186498 for the original reason we pulled in this package into RHEL 9, which probably won't go away when we launch RHEL 10.

Add gstreamer1-rtsp-server

---

configs/sst_installer-unwanted-c9s.yaml
configs/sst_installer-unwanted-eln.yaml

Remove Initial Setup and anaconda-user-help packages from RHEL-10

---

configs/eln_extras_mailman3.yaml

This is an important application for Fedora Infrastructure and needs to be tracked to ensure it can be built for EPEL in the future.

Track the Mailman 3 stack in ELN Extras

---

configs/eln_extras_initialsetup.yaml

Various Enterprise Linux setups will want to be able to do this for things like spins/remixes or mass deployments.

Add Anaconda Initial Setup to ELN Extras

---

configs/sst_security_special_projects-nbde.yaml

Replace http-parser[-devel] with llhttp[-devel]

Update ELN10 NBDE related components

---

configs/sst_cloud_experience.yaml

Once efs-utils was packaged, we realized that a SELinux policy subpackage would be required.

Add efs-utils-selinux subpackage

---

configs/sst_cs_infra_services-printing-stack-c10s.yaml
configs/sst_cs_infra_services-printing-stack.yaml

The new subpackages were created in C8S, C9S, C10S and ELN, marked them as wanted for my stack.

C9S,C10S: Introduce the new subpackages from cups-filters

---

configs/sst_security_special_projects-unwanted.yaml

Previously maintained as a dependency of tang, it was also a dependency of libgit2.  http-parser is unmaintained upstream, and tang has been ported to llhttp.  libgit2 needs to do the same so that http-parser can be dropped from ELN, but this marks it unwanted in the meantime.
This is a follow-up to https://github.com/minimization/content-resolver-input/pull/1054
/cc @sergio-correia

Mark http-parser unwanted in ELN

---

configs/sst_virtualization-all-eln.yaml
configs/sst_virtualization-all.yaml

Manages uefi boot configuration for UKIs.

c9s/eln: add uki-direct (new python3-virt-firmware sub-rpm)

---

configs/sst_desktop_applications-qt6.yaml
configs/sst_pt_libraries-vfxplatform-eln.yaml

This is the supported backend for RHEL, but was split out of the main package to better handle other use cases.
/cc @tpopela

Add qt6-qtspeech-speechd

---

configs/sst_installer-anaconda-c9s.yaml

This change is related to our priority to support Web UI of the Anaconda project in RHEL-10.
https://issues.redhat.com/browse/FRONTDOOR-48

Add anaconda-webui package into RHEL

---

configs/sst_security_crypto-authentication-c9s.yaml

The NTLM plugin has been disabled in rawhide in preparation for it being removed upstream in a future version:
https://github.com/cyrusimap/cyrus-sasl/issues/708
https://src.fedoraproject.org/rpms/cyrus-sasl/c/8a986014fe89ef82e851d5744662e201f515e146
/cc @rcritten

Drop cyrus-sasl-ntlm from ELN

---

configs/sst_desktop-gnome-desktop-eln.yaml
configs/sst_desktop-unwanted-eln.yaml

It's mostly obsoleted, many things moved into GNOME Control Center, but there are still things that need investigations:
* Minimize/maximize buttons
* Focus on hover
* Startup apps and how to integrate them into the current GNOME and RHEL 10 (not necessarily RHEL 10.0). For more information please see [0] (internal to Red Hat).
[0] - https://issues.redhat.com/browse/DESKTOP-743

Remove GNOME Tweaks from RHEL 10

---

configs/sst_java-java.yaml
configs/sst_java-unwanted.yaml

The OpenJDK team only plan to support java-21-openjdk in the next release.

Drop java-17-openjdk from ELN

---

configs/sst_high_availability-userspace.yaml

This is a new subpackage built from pcs srpm that will enable high-availability cluster management from Cockpit in RHEL 10, see: https://issues.redhat.com/browse/RHEL-23048.

Add cockpit-ha-cluster to HA workload

---

configs/sst_gpu-audio-playback-c9s.yaml
configs/sst_gpu-audio-playback-eln.yaml

Pipewire has an equivalent implementation of PulseAudio's APIs, provided by `pipewire-pulse`. With Pipewire 1.0 being released and included, we feel confident that Pipewire now works well enough to remove the PulseAudio daemon itself.
In the very worst case, we can still add it back if needed.

eln: Replace pulseaudio package with pipewire-pulse

---

configs/ssg_idm-web-extensions-c9s.yaml

mod_auth_mellon is deprecated and to be removed.  It should remain in c9s so splitting the file into one for eln and one for c9s.  The eln one has mod_auth_mellon removed.

Split idm-web-extensions to remove mod_auth_mellon

---

configs/sst_kernel_rts-sysfsutils.yaml

Removing eln from the labels, but leaving cs9. Sysfsutils is being removed from RHEL10.

[sst_kernel_rts] Remove eln from labels in sysfsutils

---

configs/sst_gpu-audio-playback-eln.yaml

It seems it was added as a dependency of SDL_sound and Qt5, so we should be good to remove this. If need be, we can always put it back.
Fixes: https://github.com/minimization/content-resolver-input/issues/861

eln: Remove openal-soft from audio workload

---

configs/sst_high_availability-userspace-c9s.yaml

In #1070, I added cockpit-ha-cluster to the HA workload. However, the intention is only to ship it in c10s, not in c9s.
Can you please check that I did this right? I cannot find any documentation on how to add a package only to an upcoming release. I just based this on previous PRs and mailing list discussions.

Only add cockpit-ha-cluster to c10s

---

configs/sst_cs_infra_services-mta-c10s.yaml
configs/sst_cs_infra_services-spam-filtering.yaml
configs/sst_cs_infra_services-unwanted-c10s.yaml
configs/sst_cs_infra_services-varnish.yaml

- restore varnish
- drop spamassassin, sendmail
- explicitly mark unwanted removed packages

Infra Services c10s workload updates:

---

configs/sst_cs_system_management-sys-management-c9s.yaml
configs/sst_cs_system_management-sys-management.yaml
configs/sst_cs_system_management-unwanted-eln.yaml

gpm provides support for using mouse on Linux text console, which is IMO a rarely used functionality and not worth maintaining.
Also split cs_system_management ELN and C9S workloads. sst_cs_system_management-sys-management.yaml had both `c9s` and `eln` labels and sst_cs_system_management-sys-management-c9s.yaml contained only the packages that are only in C9S. Make the workloads independent by copying everything from sst_cs_system_management-sys-management.yaml to sst_cs_system_management-sys-management-c9s.yaml and removing the `c9s` tag from the former. Since C9S has already branched from ELN and is independent, having separate workloads will be easier to manage than sharing the common content.

Remove `gpm` and its subpackages from ELN

---

configs/sst_cs_infra_services-development-packages-c9s.yaml
configs/sst_cs_infra_services-unwanted-c10s.yaml

This is a follow-up to #1085 which dropped the rest of sendmail.
/cc @notroj

Drop sendmail-milter-devel from ELN

---

configs/sst_cs_plumbers-base-minimal-c9s.yaml

curl and curl-minimal had converged feature-wise, so the latter was removed.  curl with libcurl-minimal is the suggested replacement.
https://bugzilla.redhat.com/show_bug.cgi?id=2262096 
https://src.fedoraproject.org/rpms/curl/c/8cec2e9cc7c18e48039a2d9dd780b0528afed8cd?branch=rawhide
/cc @jamacku @lzaoral

ELN: curl-minimal has been dropped

---

configs/sst_desktop_platform_technologies-intel-lpmd.yaml

Add intel-lpmd package to enable Low Power Mode on Intel Meteor Lake platforms.
See https://issues.redhat.com/browse/RHEL-20167.

Add intel-lpmd package

---

configs/eln_extras_kde.yaml

ELN: Extras: KDE: Drop kf6, kf6-kmoretools, and khotkeys

---

configs/sst_arch_hw.yaml
configs/sst_arch_hw_eln.yaml

Add the proper alsa file for rhel10 to the eln file.  Limit the addition of ucm files to c9s because we don't have alsa-ucm-utils there.  Supersedes pull request #1072

Alsa updates

---

configs/cee-support-workload.yaml

Content Resolver is designed to track RPMs, not containers.

support-tools-container is not an RPM

---

configs/sst_installer-anaconda.yaml

There were change of plans for RHEL-10 so we decided to remove this package c10s for now.
[FRONTDOOR-48 comment](https://issues.redhat.com/browse/FRONTDOOR-48?focusedId=24265211&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-24265211)

Don't ship anaconda-webui in RHEL-10

---

configs/sst_network_management-unwanted-c10s.yaml

Drop NetworkManager-team subpackage in ELN and c10s.

Drop NetworkManager-team subpackage in ELN and c10s

---

configs/sst_pt_llvm_rust_go-llvm-toolset-exclusion.yaml
configs/sst_pt_llvm_rust_go-llvm-toolset.yaml

libomp and lld are now enabled in 18, which is now in ELN, and expected in RHEL 10 in due course.  Also, mark 16 and 17 as unwanted.
/cc @tstellar

LLVM 18 updates

---

configs/sst_cs_apps-python-crb-c10s.yaml

sst_cs_apps-python-crb-c10s.yaml is a copy of sst_cs_apps-python-crb-eln.yaml.
- labels were adjusted (split)
- python-wheel-wheel is called python3-wheel-wheel in c10s

Fixup the Python devel (CRB) workload for c10s

---

configs/sst_cs_plumbers-hw-tools.yaml
configs/sst_program-lorax-template-eln.yaml

rust-prefixdevname (RPM: prefixdevname, previously RHEL-specific) is now in Fedora, and lorax now expects it to be available:
https://github.com/weldr/lorax/commit/ffba3078beab843c5d663f6443dca28d8e820948

Make prefixdevname a real package

---

configs/sst_program-lorax-template-eln.yaml

https://src.fedoraproject.org/rpms/lorax-templates-rhel/pull-request/9
https://gitlab.com/redhat/centos-stream/rpms/lorax-templates-rhel/-/commit/2a5ee65a6dbd2c3f868c93ee800d12c657b98ef1
/cc @sgallagher @bstinsonmhk

Drop shim-ia32 and grub2-efi-ia32-cdboot from ELN

---

configs/eln_extras_yselkowitz.yaml

This package was abandoned upstream and retired downstream.

eln-extras: drop bitstower-markets

---

configs/eln_extras_meta.yaml

The awscli2 package has replaced and provides awscli, and is in ELN. Furthermore, while noarch, it cannot be installed on s390x due to arch limiations in python-awscrt (rhbz#2180988).  Therefore, if relisted in the future, it must be limited to installable architectures in the workload.
/cc @davide125

Drop awscli from ELN Extras for Meta

---

configs/eln_extras_meta.yaml

This is no longer built as part of libxcrypt in RHEL >= 10 but is still needed by Chef, so it is now built from a separate libxcrypt-epel package:
https://koji.fedoraproject.org/koji/packageinfo?packageID=39931

eln_extras_meta: add libxcrypt-compat

---

configs/sst_pt_libraries-unwanted-eln.yaml

libxcrypt-compat (libcrypt.so.1) was dropped from c10s and ELN libxcrypt, but is still used for binary compatibility with third-party solutions.  Therefore, it is eligible for EPEL 10 and ELN Extras, but is unwanted in ELN itself.
https://src.fedoraproject.org/rpms/libxcrypt/pull-request/16
https://src.fedoraproject.org/rpms/nbdkit/pull-request/5
https://github.com/minimization/content-resolver-input/pull/1124

Mark libxcrypt-compat as unwanted in ELN

---

configs/sst_security_compliance-reporting.yaml

Having `openscap-report` in RHEL9 will help us consolidate experience across supported version.
Related: RHEL-31755

Adding openscap-report to RHEL9

---

configs/sst_desktop-gnome-desktop-eln.yaml
configs/sst_desktop-gnome-desktop.yaml

Previously it was pulled by Gedit and Mutter, but we replaced Gedit with GNOME Text Editor and the dependency was dropped from Mutter, so fix this for ELN/RHEL 11 and slowly start the PRP process for RHEL 10..

Add zenity to CR

---

configs/sst_networking_core-wireguard-tools.yaml

Somehow we forgot to add wireguard-tools to ELN. It is present on RHEL9, and we also plan to have it on RHEL10.

ELN: add wireguard-tools

---

configs/sst_network_fastdatapath-tools-lldp.yaml

Customers unable to compile internal software using functions defined in `/usr/include/lldpctl.h`. 
See Jira issue [RHEL-22127](https://issues.redhat.com/browse/RHEL-22127).

network/lldp: add devel packages

---

configs/sst_kernel_debug-kdump-c9s.yaml

We added a new subpackage makedumpfile in Fedora and RHEL-10.

Add makedumpfile subpackage to ELN and c10s.

---

configs/sst_cs_apps-ruby-c9s.yaml
configs/sst_cs_apps-ruby-eln.yaml

rubygem-racc is in buildroot 1 currently, however since it should be provided by the Ruby SRPM from c10s onward. Therefore, it should be part of the Ruby workload to be in the correct class of packages.
@voxik FYI

Update ruby workload to include rubygem-racc on C10S + ELN

---

.github/workflows/config-check.yml

This should fix the "Node.js 16 actions are deprecated" warning in our CI jobs.  The only differences between checkout@v3 and v4 is the switch to nodejs-20 and the addition of a showProgress option.

Update config-check action to checkout@v4

---

configs/sst_kernel_security-kpatch.yaml

The kpatch packages are RHEL-specific and not supported on Fedora.  Add the cs10 tag for inclusion in RHEL-10.

add cs10 tag for kpatch packages

---

configs/sst_kernel_debug-kdump.yaml

We added a new subpackage kdump-utils in Fedora and RHEL-10.

Add kdump-utils subpackage to ELN and c10s.

---

configs/sst_network_drivers-appstream-c9s.yaml
configs/sst_network_drivers-appstream.yaml
configs/sst_network_drivers-rhel-only-c9s.yaml
configs/sst_network_drivers-rhel-only.yaml

For the fabtests removal:
JIRA: https://issues.redhat.com/browse/RHEL-12293
For removing mvapich2: In our SST meting, we agreed we can't maintain multiple MPI implementations.

sst_network_drivers: drop fabtests and mvapich2 from eln and c10s

---

configs/sst_cloud_experience.yaml

We cannot package efs-utils and efs-utils-selinux any longer due to upstream changes.

Unwanted: efs-utils + efs-utils-selinux

---

configs/sst_cs_system_management-sys-management.yaml

classify `Xaw3d` only as a dependency in `c10s`

---

configs/sst_cs_infra_services-databases-c9s.yaml
configs/sst_cs_infra_services-unwanted-c10s.yaml

Update c9s workflows to reflect that libmemcached-awesome replaced libmemcached (from 9.0)
Update c10s+ workflows to remove libmemcached-awesome (RHEL-34695)

updates for libmemcached/libmemcached-awesome

---

configs/sst_arch_hw.yaml
configs/sst_arch_hw_eln.yaml

The mdadm package is required for the storage workload (which is where it should be).  It does not need to be required by arch_hw which no longer has any control over the md raid subsystem that mdadm is used to manage.

Remove mdadm from sst_arch_hw_eln.yaml

---

configs/sst_cs_system_management-unwanted-eln.yaml

OpenSLP upstream is not active and the package often suffers from security issues. Some of them are even not fixable due to protocol design flaws. However, client and devel part are still needed.

Mark openslp-server as unwanted

---

configs/sst_arch_hw_eln.yaml

This package is not maintained by arch_hw.  It is required by anaconda-install-img-deps as shown by https://tiny.distro.builders/view-rpm--view-eln--nvme-cli.html and so will still be included in the install image.  If it is wanted post-install, then likely storage_ssg should pull it in as a requirement.

Remove nvme-cli from sst_arch_hw_eln.yaml

---

configs/sst_cs_plumbers-unwanted.yaml
configs/sst_high_availability-userspace.yaml

All users of `python3-pycurl` are already patched to remove this dependency in C10S and ELN.  See the issue below for the progress.
Related: https://issues.redhat.com/browse/RHEL-26342

mark `python3-pycurl` as unwanted in C10S and ELN

---

configs/sst_gpu-unwanted-eln.yaml

Some packages that are generated from the xorg-x11-server source package have not been marked as unwanted yet, so let's do that here. The only packages that still rely on them (mostly tigervnc or some Xorg drivers) are also marked as unwanted and are slated for removal too.

eln: Mark some remaining Xorg packages as unwanted

---

configs/sst_gpu-unwanted-eln.yaml

The daemon is removed in favor of Pipewire (which contains an implementation still of the PulseAudio API)

eln: Mark pulseaudio daemon package as unwanted

---

configs/sst_network_drivers-appstream.yaml

fabtests needs to be moved to CRB, not removed entirely.
This reverts commit e3e56f354f687e7bb52c18119b36be0bd264aa06 from #1144 .
/cc @michich

Revert "sst_network_drivers: remove fabtests from Appstream"

---

configs/sst_cs_plumbers-editors-c9s.yaml

The renamed package is only present in c10s and ELN and there were no plans to to rename it also in c9s.
Fixes: 7126256bea6d2cdba01ea8640d28c8aac5756cf5 ("sst_cs_plumbers-editors: emacs-nox -> emacs-nw")
cc: @jacekmigacz

c9s: revert rename of `emacs-nox`

---

configs/sst_cs_plumbers-cli-tools.yaml

Related: https://issues.redhat.com/browse/RHEL-36785
cc: @msekletar

replace `mlocate` with `plocate` in c10s and eln

---

configs/sst_arch_hw.yaml
configs/sst_arch_hw_eln.yaml

ethtool is maintained by the sst_networking_core for quite some time, so remove from sst_arch_hw.
CC: @dledford

remove ethtool from sst_arch_hw

---

configs/sst_logical_storage-packages.yaml

This functionality has been merged into the upstream kernel and is intended to be delivered in the same manner in the next major release.
Signed-off-by: Andrew Walsh <awalsh@redhat.com>

Removed kmod-kvdo from content set for EL10

---

configs/sst_bootc-eln.yaml

At the current time the development of this is focused on Auto primarily as far as I know and the composition of the current bootc SST does not maintain it.

sst_bootc: Drop initoverlayfs

---

configs/sst_cs_system_management-sys-management.yaml

These packages got added to RHEL 9, but never got into workloads.
Correct this for ELN and RHEL 10.
udftools: https://bugzilla.redhat.com/show_bug.cgi?id=1949905
python3-pyghmi: https://bugzilla.redhat.com/show_bug.cgi?id=2023376

Add forgotten CS system management pkgs from RHEL 9

---

configs/sst_gpu-OpenCL-infrastructure.yaml

libclc is required to build Intel drivers with mesa >= 24.1.0
JIRA issue: https://issues.redhat.com/browse/RHELPLAN-170068

Add libclc

---

configs/repository-fedora-eln.yaml

We do not need to filter exim, esmtp, etc. here because we use hints in fedora-release to choose postfix as the provider of smtpdaemon.  But we can use this filtering to block certain unwanted packages which are frequent culprits in pulling in hundreds or even a thousand-some more unwanted packages into ELN.

ELN: enhance unwanted repository filtering

---

configs/sst_csi_client_tools.yaml

This RHEL-only package exists already in 7, 8, and 9, and it was forgotten from 10. Hence, let's add it as placeholder package.

sst_csi_client_tools: add redhat-cloud-client-configuration

---

configs/repository-fedora-eln-extras.yaml
configs/view-eln-extras.yaml

The packages we want to exclude from ELN might still belong in ELN Extras.

Separate repository for ELN Extras

---

configs/eln_extras_kde.yaml
configs/eln_extras_qt5.yaml
configs/eln_extras_qt6.yaml

Updating KDE and qt6.
Adding qt5 packages.
We will be supporting qt5 packages in epel10 as long as they are supported in RHEL9 and/or Fedora.

Update kde, qt6 and qt5 in eln_extras

---

configs/sst_gpu-OpenCL-infrastructure.yaml

This reverts commit baf3898c851f960a19fcf8ec3877cf4d42cc980a.
It was decided to build libclc as part of mesa for the moment:
https://issues.redhat.com/browse/RHELPLAN-170071?focusedId=24850231&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-24850231

Revert "Add libclc"

---

configs/repository-fedora-eln.yaml

Until split repositories for addons are working, ELN Extras is still dependent on the ELN config, particularly the Extras repo.

Drop excludes from Extras

---

configs/eln_extras_hyperscale.yaml
configs/repository-fedora-rawhide.yaml
configs/sst_cs_infra_services-development-packages-c9s.yaml
configs/sst_cs_infra_services-development-packages.yaml
configs/sst_cs_infra_services-i2c-tools.yaml
configs/sst_cs_infra_services-power-management.yaml
configs/sst_cs_plumbers-hw-tools.yaml
configs/sst_cs_system_management-sys-management-c9s.yaml
configs/sst_cs_system_management-sys-management.yaml
configs/sst_desktop_firmware_bootloaders-efibootmgr.yaml
configs/sst_desktop_firmware_bootloaders-efivar.yaml
configs/sst_desktop_firmware_bootloaders-gnu-efi.yaml
configs/sst_desktop_firmware_bootloaders-os-prober.yaml
configs/sst_desktop_firmware_bootloaders-pesign.yaml
configs/sst_desktop_platform_technologies-gnome-desktop-eln.yaml
configs/sst_desktop_platform_technologies-gnome-desktop.yaml
configs/sst_network_drivers-appstream-c9s.yaml
configs/sst_network_drivers-appstream.yaml
configs/sst_network_drivers-baseos.yaml
configs/sst_pt_gcc-gcc-toolset.yaml
configs/sst_pt_llvm_rust_go-llvm-toolset-c9s.yaml
configs/sst_pt_perf_debug-debuggers-unwanted.yaml
configs/sst_pt_perf_debug-debuggers.yaml
configs/sst_pt_perf_debug-performance-tools.yaml

C10S and ELN are dropping all i686 builds, and even in C9S i686 was built only for multilibs and not separately composed.  32-bit ARM was never a supported platform in RHEL or CentOS Stream.
/cc @tdawson @sgallagher

Drop i686 and armv7hl

---

configs/sst_network_management-main.yaml
configs/sst_network_management-unwanted-c10s.yaml
configs/sst_network_management-usb_modeswitch.yaml

No reasonably modern hardware should require this.
Also, it's a fairly oddball thing -- written TCL, bundling a TCL interpreter.

Remove usb_modeswitch from c10s & eln

---

configs/sst_pt_llvm_rust_go-rust-toolset-c9s.yaml

The srpm-macros subpackage needed to be renamed to provide a clean upgrade path from RHEL 9: https://src.fedoraproject.org/rpms/rust/c/230ae0c65c9c719221d668037e4400bdeac9ee40
/cc @cuviper

Update rust packages for RHEL 10

---

configs/sst_high_availability-userspace.yaml

This PR contains the up-to-date 1:1 mapping to Requires and BuildRequires in pcs spec file. I noticed that nobody updated the dependencies here since pcs became a placeholder. So I came to the conclusion that I, as a maintainer, should keep them up to date also here. I don't know how many placeholders exist, but I think that it would be nice to remind other maintainers that they should update their dependencies too. 
I switched to requiring virtual provides for pkgconfig in pcs spec file where possible. I suppose that Content Resolver doesn't support resolving that, so I left those dependencies as they were before.
I noticed that some dependencies were missing completely, like python or ruby for the srpm. Also, gcc and gcc-c++ were missing, these are needed for compiling python module and …

Bring pcs dependenies up to date

---

configs/sst_cs_system_management-sys-management.yaml
configs/sst_cs_system_management-unwanted.yaml

We decided to keep it in EPEL due to its low usage.
This reverts part of commit e3c186bcce96e21aa8bf8805d9d889b68187d361

Remove udftools from C10S and ELN

---

configs/sst_cs_system_management-text-processing.yaml
configs/sst_cs_system_management-unwanted.yaml

Due to a licensing issue, we are dropping the docbook5-schemas support from RHEL. This is a test to see if that is a possibility or if it is still a hard requirement.
Related: RHELMISC-5885, BZ#2260534

Drop docbook5-schemas

---

configs/sst_program-lorax-template-x11.yaml
configs/sst_program-lorax-template.yaml

This following packages are no longer in the runtime-install.tmpl:
dbus-x11
gdisk
tigervnc-server-minimal
tigervnc-server-module
xorg-x11-xauth
xorg-x11-drivers
xorg-x11-server-Xorg
Related: RHEL-38741

lorax-templates: Update the list for lorax-templates-rhel-10.0-49

---

configs/sst_i18n-extra-fonts.yaml

The sst_i18n team found that they have ownership entry for open-sans-fonts package ownership but no other sst_i18n package needs that font package.
Hence, we would like to remove it from Extra Fonts workload.
The open-sans-fonts package is already required by ssg_idm team in their 3 workloads.

Remove open-sans-fonts package from Extra fonts workload

---

configs/sst_program-lorax-template.yaml
configs/sst_security_crypto-unwanted.yaml

libreport is being removed from RHEL 10:
https://gitlab.com/redhat/centos-stream/rpms/lorax-templates-rhel/-/merge_requests/51
https://src.fedoraproject.org/rpms/lorax-templates-rhel/pull-request/10

Drop libreport

---

configs/sst_cs_infra_services-http-ftp-cli-clients-c10s.yaml

wget2 is not ready to be deployed in RHEL10 so we are replacing it with the original wget.

Replacing wget2 with wget in RHEL10

---

configs/sst_virtualization_cloud-3rdparty_hypervisors.yaml

These are now being built and shipped for aarch64, except for open-vm-tools-sdmp and hypervfcopyd.
/cc @LaneWolf

Add open-vm-tools and hyperv-daemons for aarch64

---

configs/sst_cs_infra_services-redis.yaml

redis has been retired from F41:  https://fedoraproject.org/wiki/Changes/Replace_Redis_With_Valkey
/cc @notroj

Drop redis from ELN

---

configs/sst_cs_apps-java-bootstrap.yaml

Add workload with buildroot-only packages required to build Java packages in bootstrap mode.
These need to be pulled into ELN/C10S explicitly because in normal conditions bootstrapping is disabled, so RPM dependencies on bootstrap packages are absent, and bootstrap packages are not pulled-in by Content Resolver via dependency resolution mechanism.

Add sst_cs_apps-java-bootstrap workload

---

configs/repository-fedora-eln-extras.yaml

ELN repos are not always completely clean of Extras content.  Also, those packages which provide an alternative implementation to certain components in RHEL are acceptable for Extras if they do not conflict.

Reduce filtering in eln-extras repo

---

configs/sst_coreos.yaml

xref https://gitlab.com/redhat/centos-stream/release-engineering/pungi-centos/-/merge_requests/537 too

coreos: bootupd is on all architectures

---

configs/eln_extras_kde.yaml

This updates some package names for Plasma 6, drops deprecated components, and adds the rest of the Gear apps and a few other recent additions.
/cc @tdawson

Update KDE Extras workload

---

configs/sst_openstack.yaml

Remove obsolete packages, properly limit arch-specific packages, and exclude the virt stack on ppc64le.
/cc @amoralej

Fix openstack workload

---

configs/sst_openstack.yaml

While this subpackage is noarch, grub2 as a whole is not built for s390x and therefore this isn't shipped therefor.

Fix arches of grub2-efi-x64-modules for openstack

---

configs/eln_extras_kde.yaml

kaidan depends on qtwebengine.  plasma-nm-l2tp transitively depends on xl2tpd which requires kmod(l2tp_ppp.ko), which is not included in the RHEL kernel for s390x.
/cc @tdawson

Fix arches of kaidan and plasma-nm-l2tp

---

configs/sst_openstack.yaml

driverctl is not available for s390x.  redis has been replaced by valkey.
/cc @amoralej

Fix driverctl and redis for openstack

---

configs/sst_i18n-extra-fonts.yaml

We plan to include the sil-nuosu-fonts package in RHEL 10 for compatibility.

Add sil-nuosu-fonts package to extra fonts

---

configs/sst_cs_apps-python-crb-c10s.yaml

Those are intentionally not listed in the ELN workload,
as we do not want to pull them into ELN,
we just acknowledge them in CRB as they are already ours.
cc @frenzymadness @torsava

Add more Python packages to c10s CRB workflow

---

configs/sst_sap.yaml

SAP team decided that compat-locales-sap and compat-locales-sap-common packages will NOT be present in RHEL 10.

Remove reference of compat-locales-sap and compat-locales-sap-common packages

---

configs/sst_security_special_projects-usbguard.yaml

catch1 is a C++-native, test framework for unit-tests. The usbguard component is not strictly dependant on the catch1 development files. We purely use it for some very basic testing purposes, mostly upstream but we have it enabled downstream as well. We could remove it any time and usbguard would be still properly functioning.

Remove catch1-devel from usbguard

---

configs/sst_desktop-brasero.yaml
configs/sst_desktop-loupe.yaml
configs/sst_desktop-snapshot.yaml

Reflect that status quo from RHEL 8+ here as well

Snapshot, Loupe and Brasero are not shipped on s390x/aarch64

---

configs/sst_cs_apps-unwanted-java.yaml

postgresql-jdbc depends on ongres-stringprep which depends on exec-maven-plugin which depends on apache-comons-exec.

Make the dependencies of postgresql-jdbc wanted.

---

configs/eln_extras_kde.yaml

While Qt5 is planned for EPEL 10, its WebEngine component is not.  cantor and kaidan show no signs of being close to Qt6 conversion, so this disables them in the meantime.  ghostwriter will move to Qt6 in 24.08, and marble's usage is optional and can be disabled in spec.
FWIW Qt5WebKit is even more unwanted, but so far the only dependents are kexi/kreport (which is about to be disabled in spec) and kdevelop (which is also moving to Qt6 in 24.08).
/cc @tdawson

Drop Qt5WebEngine dependent packages from Extras

---

configs/sst_container_tools.yaml

Moving this here from https://github.com/containers/podman/pull/23588
---
xref https://issues.redhat.com/browse/RHELMISC-4891
And earlier: https://issues.redhat.com/browse/RHEL-18157
Basically the decision earlier was this was owned by the container_tools SST.

sst_container_tools: Add composefs

---

configs/sst_kernel_security-intel-qat.yaml

xxhash is not required by any of QAT packages.
dwz and rsync have dropped xxhash requirement too.

Drop xxhash package from RHEL10

---

configs/sst_desktop_applications-unwanted.yaml

sst_i18n now depends on this for ibus-panel and is planning to ship in CRB.
https://issues.redhat.com/browse/RHEL-36250
/cc @tpopela

Do not mark libdbusmenu as unwanted

---

configs/sst_i18n-gnome-desktop-testing.yaml

This is intended for IBus CI testing: https://issues.redhat.com/browse/RHEL-54599
/cc @fujiwarat

Add gnome-shell-extension-no-overview

---

configs/eln_buildroot.yaml

python-rpmautospec will be buildroot-only in RHEL, and is therefore needed in EPEL to allow packages to be built.
/cc @sgallagher

Add rpmautospec to ELN Extras

---

configs/sst_gpu-X11-enviroment.yaml

It makes sense to ship this while we still have support for X11 clients, and is actively used by other packages that we still ship for configuration of their drawing (Xt, Xaw, etc).
Related: https://issues.redhat.com/browse/GPU-1145

sst_gpu-X11-environment: Add xrdb

---

configs/ssg_idm-unwanted.yaml

The upstream project is no longer maintained and the package will be replaced by python3-ifaddr.

ssg_idm-unwanted: Remove python3-netifaces

---

configs/sst_arch_hw.yaml

https://src.fedoraproject.org/rpms/acpica-tools/c/bada08a9e12545c2332d6df5f31d31cf81d97606
/cc @ahs3

Exclude acpica-tools on s390x

---

configs/sst_cs_software_management-package-manager.yaml

A new subpackage of dnf-plugins-core, complement to python3-dnf-plugin-post-transaction-actions, which is already in the workloads.
https://issues.redhat.com/browse/RHEL-38831
https://issues.redhat.com/browse/ENGCMP-4445

Add python3-dnf-plugin-pre-transaction-actions

---

configs/sst_gpu-X11-server.yaml

It's needed for things like listening to a TCP socket.

sst_gpu: Add xhost to X11 server workload

---

configs/sst_cs_software_management-package-manager-dnf5.yaml
configs/sst_cs_software_management-package-manager.yaml

libdnf is compiled without RHSM support in CentOS Stream, but with the support in RHEL. This difference is intetional to prevent CentOS Stream systems from accidentally accessing RHEL repositories.
To stop content resolver from reporting "unneeded librhsm", add librhsm to DNF workloads.

Enable RHSM support in RHEL

---

configs/sst_csi_client_tools.yaml

This RHEL-only package exists already in 8 and 9, and it was forgotten from 10

sst_csi_client_tools: add yara

---

configs/repository-c10s.yaml
configs/repository-fedora-eln-extras.yaml
configs/repository-fedora-eln.yaml

This variant has been disabled in c10s:
https://gitlab.com/redhat/centos-stream/release-engineering/pungi-centos/-/merge_requests/825

Drop ResilientStorage repositories

---

configs/sst_container_tools-unwanted.yaml
configs/sst_container_tools.yaml

libvirt has switched to json-c, and crun uses an embedded yajl as of RHEL 10.
https://src.fedoraproject.org/rpms/crun/pull-request/72
https://github.com/containers/crun/pull/1583
https://gitlab.com/redhat/centos-stream/rpms/crun/-/merge_requests/102
/cc @jnovy @cgwalters

Remove yajl

---

configs/sst_cs_base_utils-sys-management.yaml

add new subpackage opencryptoki-ccatok for rhel-10.0/c10s

add new subpackage opencryptoki-ccatok for rhel-10.0/c10s

---

configs/sst_cs_base_utils-text-processing.yaml

This was replaced with separate count1to and multitoc subpackages in texlive 2024.
/cc @ngothan

Drop obsolete texlive-ms

---

configs/eln_extras_kde.yaml

EPEL 10 will include parts of Qt5 but not KF5.  Some of these will be ported to KF6 in KDE Gear 24.12, at which point they can be re-enabled.
/cc @tdawson

KDE: disable apps still based on KF5

---

configs/sst_container_tools.yaml

This replaces libslirp in the containers stack as of RHEL 9.
/cc @jnovy @cgwalters

Add gvisor-tap-vsock

---

configs/repository-fedora-eln.yaml

cargo-c is sometimes (e.g. librsvg2) used to create shared libraries from Rust code, and cbindgen is used by Mozilla products (mozjs128, firefox, and thunderbird); both are intended to be vendored in RHEL.  Also, expand the list of unwanted documentation tools to include fop.

Add ELN exclusions

---

configs/sst_display_hardware-libcamera.yaml

Create a new workload for libcamera which is needed to support MIPI Cameras in RHEL.
Related to https://issues.redhat.com/browse/RHEL-58621.

Add workload for libcamera

---

configs/eln_extras_kde.yaml

These have migrated to KF6 in KDE Gear 24.12.
/cc @tdawson

Restore kmix, kwave, marble to Extras

---

configs/repository-fedora-eln.yaml
configs/sst_csi_client_tools.yaml
configs/sst_high_availability-userspace.yaml

This was removed upstream in pacemaker 3.0.0~rc1:
https://src.fedoraproject.org/rpms/pacemaker/c/394383f0ffe98652f064be9fc234523cd4dbdac4
/cc @feist @CtrlZmaster

Remove pacemaker-nagios-plugins-metadata

---

configs/sst_display_hardware_multimedia-HID-drivers.yaml
configs/sst_display_hardware_multimedia-audio-playback.yaml
configs/sst_display_hardware_multimedia-codecs.yaml
configs/sst_display_hardware_multimedia-graphics-development-libraries.yaml
configs/sst_display_hardware_multimedia-multimedia-libraries.yaml
configs/sst_display_hardware_multimedia-multimedia-sharing.yaml
configs/sst_display_hardware_multimedia-unwanted.yaml
configs/sst_display_window_management-Wayland-Infrastructure.yaml
configs/sst_display_window_management-X11-enviroment.yaml
configs/sst_display_window_management-X11-server.yaml
configs/sst_display_window_management-unwanted.yaml
configs/sst_gpu-unwanted.yaml

Some components got shuffled around, so it makes sense that we also align the content workloads with the new org structure.
For the unwanted packages, splitting this up over the multiple SSTs was a bit harder since they contains for example some very historical dependencies of e.g. Xorg or some multimedia libraries. I tried to move those the most appropriate SST where possible.

Realign Content Resolver workloads post Dev/QE merger

---

configs/eln_extras_meta.yaml

rust-eza was retired due to "license shenanigans":
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/PHL4R4AQPKOR6QTNRFAKHCHIMWRFAW6C/#MDMTSAPU7XOKY2LLZMPIBPBJY2O6AXJ7
/cc @davide125 @michel-slm

Drop eza from Extras

---

configs/eln_extras_fedora-packager.yaml
configs/eln_extras_meta.yaml

This requires dnf4 which is no longer available for rawhide and ELN.

Skip rpmdistro-repoquery temporarily

---

configs/sst_cs_databases-db-mariadb.yaml
configs/sst_cs_databases-embedded.yaml

Fix typos in sst_cs_databases workload descriptions

---

configs/eln_extras_libreoffice.yaml

The maintainer does not wish to have this package in EPEL:
https://src.fedoraproject.org/rpms/grammalecte/pull-request/2

Drop grammalecte

---

configs/eln_extras_fedora-packager.yaml
configs/eln_extras_meta.yaml

rpmdistro-repoquery can now use dnf5:
https://pagure.io/rpmdistro-repoquery/c/2dd813432d5c832704077c4555f3d0e459e438c9 https://src.fedoraproject.org/rpms/rpmdistro-repoquery/c/7f8259593cf8c62ff41595209c11eb893ea40066
This reverts commit 3412737297dd9489449104422b23d7ceed1e81b0.

Revert "Skip rpmdistro-repoquery temporarily"

---

configs/eln_extras_fedora-packager.yaml

This depends on python-fedora which was recently retired for lack of a maintainer.

Skip fedora-easy-karma temporarily

---

configs/sst_pt_llvm_rust_go-rust-toolset.yaml

Unversioned wasm32-wasi deprecation:
https://blog.rust-lang.org/2024/04/09/updates-to-rusts-wasi-targets.html
Re-enable aarch64-unknown-none-softfloat target:
https://src.fedoraproject.org/rpms/rust/c/f737b8c4dddc2d64481479aec6c85bead138c1af
/cc @cuviper

Update rust components

---

configs/sst_virtualization-all.yaml

virtualization-all: Add trustee-guest-components

---

configs/sst_image_builder-composer.yaml

The cockpit-image-builder-package will replace cockpit-composer.
Resolves: RHELPLAN-171387

configs/sst_image_builder: add cockpit-image-builder package

---

configs/eln_extras_meta.yaml
configs/eln_extras_meta_cloud.yaml

This minimizes the blast radius when it fails to build

eln_extras_meta: Move azure-cli to separate workload

---

configs/repository-fedora-eln-extras.yaml
configs/repository-fedora-eln.yaml

pipewire-jack should be used instead for RHEL 10+.
https://bugzilla.redhat.com/show_bug.cgi?id=2313997

Exclude jack-audio-connection-kit

---

configs/repository-fedora-eln.yaml

This is a build dependency of the Fedora build of libguestfs, which occasionally gets pulled into the ELN buildroot when things are broken.

Exclude ocaml-ounit from ELN

---

configs/sst_display_desktop_foundation-gnome-desktop.yaml
configs/sst_display_desktop_foundation-unwanted.yaml

This was correct for ELN but not for C10S.  Now that tinysparql/localsearch has been built for ELN, they will still be used as they provide the old tracker names.
Reverts minimization/content-resolver-input#1369
/cc @AdamWill @tpopela

Revert "Update for tracker->tinysparql and tracker-miners->localsearch"

---

configs/eln_extras_meta.yaml

ncdu 2.x is a complete rewrite in Zig.  The Zig compiler currently requires an LLVM with all default targets enabled, which RHEL's llvm does not. Therefore, the only ways to build zig for EPEL would be for a compat llvm version to be built for EPEL with all targets enabled (and limit zig to llvm versions which are not the default version in RHEL, which is continuously rebased), or for zig to be patched to not support all arches.
Neither possibility seems likely, and as ncdu is more of a "nice to have" it's probably best to simply expect it won't be possible for EPEL 11.
/cc @davide125 @michel-slm

Drop ncdu from Extras

---

configs/sst_display_hardware_multimedia-unwanted.yaml

As noted in the comment, the pulseaudio SRPM is not completely unwanted; the various libs subpackages are still needed, while the server and modules are not, and in fact are no longer built for RHEL.
/cc @nielsdg

Fix unwantedness of pulseaudio

---

configs/eln_extras_kde.yaml

This is a Plasma 5 QML applet which cannot be compatible with Plasma 6 and has not had an upstream release in years.
This should probably be retired from Fedora and EPEL 10 (!) as well.
/cc @tdawson

Drop plasma-applet-translator

---

configs/sst_display_i18n-icu-compat.yaml
configs/sst_display_i18n-icu.yaml

This is intended to avoid the usual breakage in ELN when icu gets a major version bump.
/cc @juhp

List icu, add compat upgrade helper

---

configs/eln_extras_meta.yaml
configs/eln_extras_meta_hw.yaml

Move these from the main workload to a `meta_hw` one
Also start tracking `aer-inject` and `mce-inject`

meta: split off hardware related packages

---

configs/sst_kernel_maintainers-kernel-unwanted.yaml
configs/sst_program-lorax-template.yaml

Handling for the old (per-chip) firmware package names was recently removed from rawhide, and is unneeded for c10s.
https://src.fedoraproject.org/rpms/linux-firmware/c/25343c359bc51d30b1792a80b5d4c29e29c7ac14
/cc @bstinsonmhk

Cleanup obsolete firmware package names

---

configs/sst_rhel_lightspeed.yaml

RHEL Lightspeed team got a new subpackge for selinux policy. This patch updates the yaml file for the sst_rhel_lightspeed to include this new subpackage.

Add CLA selinux subpackage

---

configs/sst_high_availability-userspace.yaml

- we unbundled Tornado in RHEL 9.6&10.0GA+
- findutils and tar were used before, just not declared
- systemd-rpm-macros is now used instead of systemd per Fedora Packaging Guidelines example for systemd scriptlet macros
@yselkowitz I have a question about what actually goes in this file... Is it just the BuildRequires declared in the spec file? Or the output of `rpm -q --requires <rpm>` (for Requires) and `rpm -q --requires <srpm>` (for BuildRequires)? There is a difference since the latter also contains dependencies automatically generated by RPM.
And what about `BuildRequires: pkgconfig(booth)`? I changed to this style of dependency to indicate that we only need the pkgconfig of the package and to make sure if the pc file is ever split from the main package, we won't have to make …

Update pcs dependencies to match the current state

---

configs/sst_cs_net_perf_services-geoip-c10s.yaml

These free versions are not planned to be provided in RHEL 11; users will need to get the databases themselves (often commercially).  libmaxminddb remains as a bind dependency for that purpose.

Drop geolite2 databases from ELN

---

configs/sst_display_productivity-thunderbird.yaml

thunderbird is being built again on s390x in both Fedora and ELN Extras.
Reverts minimization/content-resolver-input#1376
/cc @tdawson @tpopela

Revert "thunderbird is not build on s390x"

---

configs/view-eln-extras.yaml

This is required for eln-extras to view buildroot packages.
This can, and should, be merged before the patch goes into content-resolver.
It will just be ignored if the patch isn't in content-resolver.

Add buildroot strategy to eln-extras view

---

configs/sst_virtualization-all.yaml

This is the leaf package for TDX confidential VMs that will pull in all the other dependent SGX related packages.
The TDX feature is limited to Intel x86_64 hardware.

Add tdx-qgs package to sst_virtualization

---

configs/sst_network_fastdatapath-fast-packet-processing.yaml
configs/sst_network_fastdatapath-openvswitch-exclusion.yaml
configs/sst_network_fastdatapath-tools-lldp.yaml

Rename network-fastdatapath to network-fastdatapath-ovsdpdk as part of the splitting of the network fastdatapath SST.

Rename network-fastdatapath to network-fastdatapath-ovsdpdk

---

configs/eln_extras_automotive.yaml

This is the leaf package for `vhost-device-gpu` support which will pull in all needed dependencies
(`virglrenderer` is already in the list):
- `aemu`
- `gfxstream`

Add vhost-device-gpu to eln_extras_automotive

---

configs/rhel-sst-display-i18n--input-methods-c10s.yaml

https://fedoraproject.org/wiki/Changes/IBusChewingForZhTW

Adapt the Fedora 41 Change, ibus-chewing default IM for zh_TW locale

---

configs/eln_extras_meta_data_science.yaml

This might pull in a lot of dependencies, so we want to keep it separate.
That will help with bringing this up in EPEL as well.

[meta] add new data science workload containing conda

---

configs/rhel-sst-cockpit--web-console-c10s.yaml

RHEL 4 Edge was only a RHEL 9 thing, and does not exist in RHEL 10 any more. This extension is undermaintained, seems to have no significant user base, and does not make much sense with bootc images. So drop it for RHEL 11.

sst-cockpit: Drop cockpit-ostree

---

configs/repository-fedora-eln.yaml

The first step of bundling, which copies these dependencies from the buildroot into the package, has already landed in Fedora.  The second step, which is bundling them in the sources so as not to need standalone versions even in the buildroot, has only landed in RHEL 10 so far; RHEL 11 will certainly do the same, either in Fedora or ELN prior to branching, or in RHEL during branching.

Block dogtak-pki logging dependencies

---

configs/repository-fedora-eln.yaml

It is a weak dependency of ibus-table and ibus-typing-booster which is not shipped in RHEL.
https://github.com/fedora-eln/eln/issues/242

Block python3-simpleaudio

---

configs/eln_extras_meta.yaml

We use below instead of atop
Also track colorized-logs, useful for dealing with output of tools that do not intelligently strip ANSI formatting when piped to other tools

Meta: drop atop, add colorized-logs

---

configs/rhel-sst-security-crypto--pqc.yaml

openssl 3.5 includes native support for post-quantum crypto algorithms.
/cc @neverpanic

Remove oqsprovider from ELN

---

configs/rhel-sst-pt-python-ruby-nodejs--python-crb-c10s.yaml
configs/rhel-sst-pt-python-ruby-nodejs--python-crb-eln.yaml
configs/rhel-sst-pt-python-ruby-nodejs--python.yaml

This does not make any difference,
but indicates for our team where we want it to land.
This is meant for RHEL 11+, however since it has no real effect, I made the change for c10s+eln both (as it is easier).

Move python3-setuptools to Python CRB workload

---

configs/eln_extras_meta.yaml

The replacement is `sq cert lint`:
https://src.fedoraproject.org/rpms/rust-sequoia-keyring-linter/c/94784a2dbe293ceefba3d1cd24150f96d7a734cf
/cc @davide125 @michel-slm

meta-sig: sequoia-keyring-linter was retired

---

configs/rhel-sst-virtualization-cloud--cloud_azure.yaml

Azure in general only supports 2 arches (x86_64, aarch64) currently, so after discussion in team, we only add the supported 2 arches (x86_64, aarch64) currently.

rhel-sst-virtualization-cloud--cloud_azure: add azure-vm-utils

---

configs/repository-fedora-eln.yaml

ibus-typing-booster recently gained an (optional?) dependency on python-rapidfuzz, which BuildRequires: python3-scikit-build-core which pulls in ~200 unwanted dependencies.

Block python3-scikit-build-core from ELN

---

configs/eln_extras_meta_config_mgmt.yaml

Start by tracking dummy-package-canary which we use to verify that DNF is healthy

[extras] add a config management workload for Meta

---

configs/rhel-sst-security-crypto--crypto-policies.yaml

The PQ policies have been merged into the main package:
https://src.fedoraproject.org/rpms/crypto-policies/c/20e322ef5720fa51b6056dae87f5b2b18a406854?branch=eln
Reverts minimization/content-resolver-input#1411

Revert "Add crypto-policies-pq-preview"

---

configs/rhel-sst-pt-python-ruby-nodejs--python-crb-eln.yaml

It is no longer needed for python and virtualenv and it will no longer be built.
See https://src.fedoraproject.org/rpms/python-wheel/pull-request/40
See https://pagure.io/pungi-fedora/pull-request/1487
See https://pagure.io/fedora-comps/pull-request/1117

Drop python-wheel-wheel from Python CRB workload

---

configs/eln_extras_hyperscale.yaml

This has yet to be ported away from OpenSSL ENGINE and has not been built in EPEL 10 or CBS as a result.
/cc @michel-slm per discussion in ELN SIG today.

hyperscale: drop fsverity-utils

---

configs/repository-fedora-eln.yaml

Many of these are BRs of python-urllib3 in Fedora but not RHEL.

Filter more unwanted Python build dependencies from ELN

---

configs/eln_extras_kde.yaml

audiotube and yt-dlp have now been rebuilt for Python 3.14.
This reverts commit fef8ee3750657232d5da22710c3d4cf7cf8e9c40.
/cc @tdawson

Revert "Disable audiotube temporarily"

---

configs/eln_extras_meta.yaml

This has yet to be rebuilt for Python 3.14, and is holding back the rest of this config from Extras.
/cc @michel-slm

meta: temporarily delist python3-testslide

---

configs/rhel-sst-csi-client-tools--all.yaml

- insights-core-selinux is a new package that will be added to RHEL 9.7/10.1. It's required when installing the insights-client.
- Jira: RHELPLAN-172287

Add insights-core-selinux to insights-client dependencies

---

configs/rhel-sst-pt-llvm-rust-go--rust-toolset.yaml

We are adding these command-line tools, but notably **not** any of Fedora's `*-devel` subpackages.

Add bindgen-cli and cbindgen to rust-toolset

---

configs/rhel-sst-storage-io--packages.yaml

This was previously a requirement of python-configshell, but no longer:
https://github.com/open-iscsi/configshell-fb/commit/7513c74d92f755c0debb10b95ffec1c3815647ee
/cc @maurizio-lombardi

Drop python-urwid

---

configs/eln_extras_meta.yaml

This is now built for Python 3.14:
https://koji.fedoraproject.org/koji/taskinfo?taskID=134758562

[meta] Re-enable python-testslide

---

configs/eln_extras_kde.yaml

As discussed in KDE SIG today.
/cc @tdawson

kde: drop obsolete ksnip, kuserfeedback

---

configs/eln_extras_kde.yaml

Beta has landed in rawhide. More applications have been ported to Qt6/KF6, and cervisia has been dropped.
/cc @tdawson

kde: Gear 25.08 updates

---

configs/rhel-sst-cs-bootloaders--secvarctl.yaml

secvarctl is a suite of tools to manage Secure Boot variables on POWER, and is needed for dynamic key management, which is finally being added to RHEL.

Add secvarctl to el9 and el10

---

configs/eln_extras_mailman3.yaml

python-django42 was retired from Fedora, but this has yet to be ported to newer versions of Django.
/cc @michel-slm

mailman3: disable mailman-web

---

configs/rhel-sst-csi-client-tools--all.yaml

- insights-core is a new package for RHEL 9.8/10.2. It's required when installing the insights-client.
- Resolves: RHELMISC-14526

Add insights-core to insights-client dependencies

---

configs/rhel-sst-cs-databases--db-postgresql-extensions.yaml
configs/rhel-sst-cs-databases--db-postgresql.yaml

postgresql18 has been added and now provides the unversioned (default) packages, but the extensions have yet to be rebuilt and therefore still depend on 16.
https://fedoraproject.org/wiki/Changes/PostgreSQL_18

cs-databases: PostreSQL 18 update

---

configs/rhel-sst-cs-base-utils--unwanted-java.yaml
configs/rhel-sst-cs-base-utils--unwanted.yaml
configs/rhel-sst-cs-databases--unwanted.yaml
configs/rhel-sst-cs-plumbers--unwanted.yaml
configs/rhel-sst-display-hardware-multimedia--unwanted.yaml
configs/rhel-sst-filesystems--userspace-unwanted.yaml
configs/rhel-sst-pt-gcc--unwanted.yaml
configs/rhel-sst-rh-ceph-storage--unwanted.yaml
configs/rhel-sst-security-selinux--python-networkx-unwanted.yaml

There have been various uses of the "unwanted" designation in CR.  Some SSTs have used it to say that *they* don't want to maintain the package (but the package is ultimately needed), others have used it to say that a package should be buildroot only (iow it's unwanted in shipped repos, but is ultimately needed in the buildroot).  This is the first step in moving towards a single definition: the package should not be in RHEL at all.
This group of packages are shipped and are clearly not going anywhere; some of these are simply obsolete unwantedness, as new packages have begun to require them.
/cc @bstinsonmhk

Unwanted list cleanup, part 1

---

configs/rhel-sst-pt-python-ruby-nodejs--python-crb-eln.yaml
configs/rhel-sst-pt-python-ruby-nodejs--unwanted-python3-eln.yaml

See https://github.com/fedora-eln/eln/issues/284
---
Note that the package is listed in configs/rhel-sst-high-availability--userspace.yaml as a build dependency of pcs. I don't know if the package can be wanted and unwanted at the same time, but we don't want it.

Mark python3-wheel unwanted in ELN

---

configs/rhel-sst-networking-core--unwanted.yaml
configs/rhel-sst-security-crypto--unwanted.yaml

cloud-init started pulling in BSD netcat, but that is unwanted and should be temporary.
https://github.com/fedora-eln/eln/issues/239

Mark netcat, libretls unwanted

---

configs/rhel-sst-csi-client-tools--all.yaml

See https://github.com/RedHatInsights/insights-client/pull/397

insights-client should not runtime-require python3-setuptools

---

configs/rhel-program--image-azure-cvm.yaml
configs/rhel-program--image-azure.yaml
configs/rhel-program--image-ec2-ha.yaml
configs/rhel-program--image-ec2.yaml
configs/rhel-program--image-qcow2-c10s.yaml
configs/rhel-program--image-qcow2.yaml

There were several warnings from the original workloads.  This fixes those.

Fix up image workloads

---

configs/rhel-sst-pt-libraries--tbb.yaml

The doc subpackage was removed in 2022.2.0:
https://src.fedoraproject.org/rpms/tbb/c/1f933b6e919ab88d5addabed3db218954f56f597
/cc @codonell

Drop tbb-doc

---

configs/rhel-sst-cs-base-utils--scm.yaml

golang-*-devel build dependencies are now being filtered, and git-lfs should move soon to vendored dependencies:
https://src.fedoraproject.org/rpms/git-lfs/pull-request/6

List git-lfs as a real package

---

configs/eln_extras_ci.yaml

beakerlib is necessary for TMT tests, and is present in EPEL.
/cc @thrix

Add fedora-ci config to Extras

---

configs/rhel-program--image-wsl-c10s.yaml
configs/rhel-program--image-wsl.yaml

GObject Introspection has been merged (with a new library version and renamed tools) into the glib sources.  While the original standalone version is still a dependency of some components and will continue to be pulled in as a result, it will eventually go away.
https://docs.gtk.org/girepository/migrating-gi.html

Remove gobject-introspection from WSL lists

---

configs/rhel-sst-csi-client-tools--all.yaml

* Resolves: RHELMISC-18048
Since rhc-playbook-verifier will be a new RPM for RHEL 10.2, this package should be a dependency of rhc-worker-playbook.

Add rhc-playbook-verifier as a dependency for rhc-worker-playbook
